### ISSUE TITLE
graceful handling of missing guava/jsr305 fails in Eclipse (some versions?)

### ISSUE THREAD

**Issue by elucash** [immutables/immutables#103]
If I include only value-2.0.6, Ant seems to handle things fine. However Eclipse builds java code that requires Guava. Then when I add Guava to the classpath, the annotation processor starts failing because it can't find jsr305 annotations. Is it required to provide jsr305 if you include Guava in value-2.0.x? 

Here is the exception from the Eclipse log: 
```
org.immutables.value.internal.$processor$.$Processor threw org.eclipse.jdt.internal.compiler.problem.AbortCompilation: Pb(324) The type javax.annotation.ParametersAreNonnullByDefault cannot be resolved. It is indirectly referenced from required .class files 
        at org.eclipse.jdt.internal.compiler.problem.ProblemHandler.handle(ProblemHandler.java:157) 
        at org.eclipse.jdt.internal.compiler.problem.ProblemHandler.handle(ProblemHandler.java:222) 
        at org.eclipse.jdt.internal.compiler.problem.ProblemReporter.handle(ProblemReporter.java:2378) 
        at org.eclipse.jdt.internal.compiler.problem.ProblemReporter.isClassPathCorrect(ProblemReporter.java:4700) 
        at org.eclipse.jdt.internal.compiler.lookup.UnresolvedReferenceBinding.resolve(UnresolvedReferenceBinding.java:104) 
        at org.eclipse.jdt.internal.compiler.lookup.BinaryTypeBinding.resolveType(BinaryTypeBinding.java:187) 
        at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.getType(LookupEnvironment.java:1191) 
        at org.eclipse.jdt.internal.compiler.apt.model.ElementsImpl.getTypeElement(ElementsImpl.java:615) 
        at org.immutables.value.internal.$generator$.$ClasspathAvailability$1.apply($ClasspathAvailability.java:44) 
...
```

**Comment by elucash** [comment]
Citing: _As far as my IDE, I have Eclipse 4.5m6-ish. I think the critical extra component is the FindBugs plug-in. This may be where Immutables is sensing the presence of the extra annotations._

**Comment by elucash** [comment]
Some minor safety was added in 2.0.7 release, but as reported this was a problem of other rogue annotation processor (annotation processing classpath pollution)

**Comment by pushbit** [comment]
Was this fully resolved?  I still need to include jsr305 in my dependencies (which also include guava) for `Nullable` to resolve.

**Comment by elucash** [comment]
Please provide some specifics. As reported above, the issue was with rogue annotation processing or other unusual dependencies in Eclipse. The best is to have reproducible case with Javac or ECJ where the problem can be clearly seen; as an example you can use https://bugs.eclipse.org/bugs/attachment.cgi?id=261387
