### ISSUE TITLE
Criteria annotation and JacksonCodecs

### ISSUE THREAD

**Issue by moujan** [immutables/immutables#1090]
I am trying to use the @Criteria to connect to a mongo database instance with a Spring boot web starter. 

I setup the connection based on the [documentation with the Jackson library](https://immutables.github.io/criteria.html#jacksonbson-integration). 

However, when I run the application and attempt to get an item from a document I get an error:

> Caused by: java.lang.IllegalStateException: Cannot build Programme, some of required attributes are not set [id, name, department, university, uniAcronym, lastUpdated, type]
	at com.hellu.mysep.mysepservice.model.ImmutableProgramme$Builder.build(ImmutableProgramme.java:547) ~[main/:na]
	at com.hellu.mysep.mysepservice.model.ImmutableProgramme.fromJson(ImmutableProgramme.java:369) ~[main/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_71]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_71]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_71]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_71]
	at com.fasterxml.jackson.databind.introspect.AnnotatedMethod.call1(AnnotatedMethod.java:114) ~[jackson-databind-2.9.8.jar:2.9.8]
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator._createUsingDelegate(StdValueInstantiator.java:524) ~[jackson-databind-2.9.8.jar:2.9.8]
	... 35 common frames omitted

The collection has documents, and I get data when I use the spring boot - mongo library. 

Is there something I am missing in the configuration for the Jackson mapper?

The code: 

Immutable class
```java
@Value.Immutable
@Criteria
@Criteria.Repository
@JsonSerialize(as = ImmutableProgramme.class)
@JsonDeserialize(as = ImmutableProgramme.class)
public interface Programme {

  @Criteria.Id
  @JsonProperty("_id")
  String getId();

  String getName();

  String getDepartment();

  String getUniversity();

  @JsonProperty("uni_acronym")
  String getUniAcronym();

  @JsonProperty("last_updated")
  LocalDateTime getLastUpdated();

  String getType();
}
```
MongoBackend:
```java
@Bean
public MongoBackend getMongoBackend() {
    ObjectMapper mapper = new ObjectMapper()
        .registerModule(new BsonModule())  // register default codecs like Jsr310, BsonValueCodec, ValueCodecProvider etc.
        .registerModule(new GuavaModule()) // for Immutable* classes from Guava (eg. ImmutableList)
        .registerModule(new Jdk8Module()) // used for java 8 types like Optional / OptionalDouble etc.
        .registerModule(new IdAnnotationModule()); // used for Criteria.Id to '_id' attribute mapping

    CodecRegistry registry = JacksonCodecs.registryFromMapper(mapper); // create CodecRegistry (adapter) from ObjectMapper

    ConnectionString connectionString = new ConnectionString("mongodb://localhost:27017");
    MongoClient mongoClient = MongoClients.create(connectionString);
    MongoDatabase database = mongoClient.getDatabase("mysep")
        .withCodecRegistry(fromRegistries(MongoClients.getDefaultCodecRegistry(), registry));

    return new MongoBackend(MongoSetup.of(database));
  }
```

```java
@Service
public class ProgrammeService {
  private final static Logger log = LoggerFactory.getLogger(ProgrammeService.class);
  private final ProgrammeRepository programmes;

  @Autowire
  public ProgrammeService(MongoBackend mongoBackend) {
    this.programmes = new ProgrammeRepository(mongoBackend);
    log.info("Fetch a programme : {}", programmes.findAll().fetch().get(0));
  }
```

**Comment by asereda-gs** [comment]
1. Don't use both `@Criteria.Id` and `@JsonProperty("_id")`. Former is sufficient.
2. The following should be sufficient to setup `MongoBackend`:

```java
    final ObjectMapper mapper = new ObjectMapper()
            .registerModule(new BsonModule())
            .registerModule(new GuavaModule())
            .registerModule(new Jdk8Module())
            .registerModule(new IdAnnotationModule());

    this.registry = JacksonCodecs.registryFromMapper(mapper);
    this.backend = new MongoBackend(MongoSetup.of(this.resolver));
```

**Comment by asereda-gs** [comment]
Also make sure that your document (in mongo) has all required fields (`_id`, `name`, `department` etc.),  otherwise you need to declare them `@Nullable` or `Optional`

**Comment by moujan** [comment]
Thanks for the response! 

The connection is working when I use the spring boot mongo starter.

I changed the configuration for the database connection to this but still get the same result:

```java
@Bean
  public MongoBackend getMongoBackend() {
    ObjectMapper mapper = new ObjectMapper()
        .registerModule(new BsonModule())
        .registerModule(new GuavaModule())
        .registerModule(new Jdk8Module())
        .registerModule(new IdAnnotationModule());

    CodecRegistry registry = JacksonCodecs.registryFromMapper(mapper);
    MongoDatabase database = getMongoDatabase(); // database connection
    CollectionResolver resolver = CollectionResolver.defaultResolver(database, registry);
    return new MongoBackend(MongoSetup.of(resolver));
  }
```

Interestingly, when I put all the fields to @Nullable I get another error: 

> Caused by: org.bson.BsonInvalidOperationException: ReadBSONType can only be called when State is TYPE, not when State is VALUE.
	at org.bson.AbstractBsonReader.throwInvalidState(AbstractBsonReader.java:669) ~[bson-3.8.2.jar:na]
	at org.bson.BsonBinaryReader.readBsonType(BsonBinaryReader.java:89) ~[bson-3.8.2.jar:na]
	at com.mongodb.operation.CommandResultArrayCodec.decode(CommandResultArrayCodec.java:47) ~[mongodb-driver-core-3.8.2.jar:na]
	at com.mongodb.operation.CommandResultDocumentCodec.readValue(CommandResultDocumentCodec.java:60) ~[mongodb-driver-core-3.8.2.jar:na]
	at org.bson.codecs.BsonDocumentCodec.decode(BsonDocumentCodec.java:84) ~[bson-3.8.2.jar:na]
	at org.bson.codecs.BsonDocumentCodec.decode(BsonDocumentCodec.java:41) ~[bson-3.8.2.jar:na]
	at org.bson.codecs.configuration.LazyCodec.decode(LazyCodec.java:47) ~[bson-3.8.2.jar:na]
	at org.bson.codecs.BsonDocumentCodec.readValue(BsonDocumentCodec.java:101) ~[bson-3.8.2.jar:na]
	at com.mongodb.operation.CommandResultDocumentCodec.readValue(CommandResultDocumentCodec.java:63) ~[mongodb-driver-core-3.8.2.jar:na]
	at org.bson.codecs.BsonDocumentCodec.decode(BsonDocumentCodec.java:84) ~[bson-3.8.2.jar:na]
	at org.bson.codecs.BsonDocumentCodec.decode(BsonDocumentCodec.java:41) ~[bson-3.8.2.jar:na]
	at com.mongodb.internal.connection.ReplyMessage.<init>(ReplyMessage.java:48) ~[mongodb-driver-core-3.8.2.jar:na]

**Comment by asereda-gs** [comment]
Can you show your BSON document (the way it is stored in Mongo) ?

### Example
```java
Flowable.fromPublisher(collection.withDocumentClass(BsonDocument.class).find())
   .toList().blockingGet();
```

**Comment by moujan** [comment]
BSON document: 
> [{ "_id" : { "$oid" : "5cceea243ec6fa34a80da1d2" }, "name" : "English Language", "department" : "Filosofiki Scholi", "university" : "National Kapodistrian University of Athens", "uni_acronym" : "EKPA", "last_updated" : { "$date" : 1537228800000 }, "type" : "bachelor" }

I am using `Jackson v2.9.8`

**Comment by moujan** [comment]
I found the issue. I had to change the id from `String` to `ObjectId`.
