### ISSUE TITLE
NullPointerException after Clean Build in Eclipse

### ISSUE THREAD

**Issue by marc-guenther** [immutables/immutables#1268]
After a Clean Build, I just got the following NPE in Eclipse (see below for full error message), which caused generation of classes to fail and lead to tons of compile errors due to missing classes:
```
org.immutables.value.internal.$processor$.$Processor threw java.lang.NullPointerException
	at org.immutables.value.internal.$generator$.$SourceOrdering$1CollectedOrdering.compare($SourceOrdering.java:260)
	at org.immutables.value.internal.$generator$.$SourceOrdering$1CollectedOrdering.compare($SourceOrdering.java:183)
	at java.util.TimSort.countRunAndMakeAscending(TimSort.java:355)
	at java.util.TimSort.sort(TimSort.java:220)
	at java.util.Arrays.sort(Arrays.java:1438)
	at org.immutables.value.internal.$guava$.collect.$Ordering.immutableSortedCopy($Ordering.java:888)
	at org.immutables.value.internal.$generator$.$SourceOrdering.getAllAccessorsProvider($SourceOrdering.java:268)
...
```

I only noticed this after a while, as it worked fine during Incremental Build. Also `javac` is not affected, and works just fine.

The workaround currently is to checkout an older version of the sources, do the full build there, then checkout current version, and only use incremental compiler from now on. This is of course not a useable workaround. Another workaround might be to check in the generated sources into version control?

I have done quite a lot of changes in the last commit, and will try to figure out which specific change causes this behaviour, but that will probably take a while. In the meantime, maybe someone has seen this before?

The full error message from Eclipse:
```
eclipse.buildId=4.11.0.I20190307-0500
java.version=1.8.0_275
java.vendor=AdoptOpenJDK
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=en_DE
Framework arguments:  -product org.eclipse.epp.package.java.product -keyring /Users/ias/.eclipse_keyring
Command-line arguments:  -os macosx -ws cocoa -arch x86_64 -product org.eclipse.epp.package.java.product -keyring /Users/ias/.eclipse_keyring

org.eclipse.jdt.apt.pluggable.core
Info
Wed Feb 24 14:25:05 CET 2021
org.immutables.value.internal.$processor$.$Processor threw java.lang.NullPointerException
	at org.immutables.value.internal.$generator$.$SourceOrdering$1CollectedOrdering.compare($SourceOrdering.java:260)
	at org.immutables.value.internal.$generator$.$SourceOrdering$1CollectedOrdering.compare($SourceOrdering.java:183)
	at java.util.TimSort.countRunAndMakeAscending(TimSort.java:355)
	at java.util.TimSort.sort(TimSort.java:220)
	at java.util.Arrays.sort(Arrays.java:1438)
	at org.immutables.value.internal.$guava$.collect.$Ordering.immutableSortedCopy($Ordering.java:888)
	at org.immutables.value.internal.$generator$.$SourceOrdering.getAllAccessorsProvider($SourceOrdering.java:268)
	at org.immutables.value.internal.$processor$.meta.$AccessorAttributesCollector.collectGeneratedCandidateMethods($AccessorAttributesCollector.java:108)
	at org.immutables.value.internal.$processor$.meta.$AccessorAttributesCollector.collect($AccessorAttributesCollector.java:78)
	at org.immutables.value.internal.$processor$.meta.$ValueTypeComposer.compose($ValueTypeComposer.java:67)
	at org.immutables.value.internal.$processor$.meta.$Round.composeValue($Round.java:181)
	at org.immutables.value.internal.$processor$.meta.$Round.collectValues($Round.java:95)
	at org.immutables.value.internal.$processor$.$Processor.process($Processor.java:79)
	at org.immutables.value.internal.$generator$.$AbstractGenerator.process($AbstractGenerator.java:87)
	at org.immutables.processor.ProxyProcessor.process(ProxyProcessor.java:72)
	at org.eclipse.jdt.internal.compiler.apt.dispatch.RoundDispatcher.handleProcessor(RoundDispatcher.java:142)
	at org.eclipse.jdt.internal.compiler.apt.dispatch.RoundDispatcher.round(RoundDispatcher.java:124)
	at org.eclipse.jdt.internal.compiler.apt.dispatch.BaseAnnotationProcessorManager.processAnnotations(BaseAnnotationProcessorManager.java:171)
	at org.eclipse.jdt.internal.apt.pluggable.core.dispatch.IdeAnnotationProcessorManager.processAnnotations(IdeAnnotationProcessorManager.java:138)
	at org.eclipse.jdt.internal.compiler.Compiler.processAnnotations(Compiler.java:940)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:450)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:426)
	at org.eclipse.jdt.internal.core.builder.AbstractImageBuilder.compile(AbstractImageBuilder.java:386)
	at org.eclipse.jdt.internal.core.builder.BatchImageBuilder.compile(BatchImageBuilder.java:214)
	at org.eclipse.jdt.internal.core.builder.AbstractImageBuilder.compile(AbstractImageBuilder.java:318)
	at org.eclipse.jdt.internal.core.builder.BatchImageBuilder.build(BatchImageBuilder.java:79)
	at org.eclipse.jdt.internal.core.builder.JavaBuilder.buildAll(JavaBuilder.java:262)
	at org.eclipse.jdt.internal.core.builder.JavaBuilder.build(JavaBuilder.java:180)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:833)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:220)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:263)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:316)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:319)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:371)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:392)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:154)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:244)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by marc-guenther** [comment]
As in the referenced issue #961, I have cycles in my type references. I removed a type argument from a common superclass, and now have to cast to the correct type in several places, but at least full build in Eclipse works again.

I could try to extract this into a reproducible example, but it seems the code from the other issue is already enough to reproduce this issue. Has that one ever been fixed, or is this something new?

**Comment by elucash** [comment]
I've just made yet another (or rather last ditch) attempt to fix the symptoms. If you can try latest master (fix is in f7dd7ec9) and see if there are any differences. It's hard to arrange proper test fixture for that, that's why I'm sort of throwing this over the wall, but if this can be triaged that's great. Thanks!

**Comment by marc-guenther** [comment]
I just tested this, but the results are peculiar.
- The NPE is gone. This is the good news.
- Unfortunately, Eclipse now becomes very very slow, compilation takes forever, and eventually it will popup an OutOfMemory alert, or simply crawl to a halt.

I have checked out the repository with the commit you mentioned (current `master`), and did a `mvn package`. I then copied the `value/target/value-2.8.9-SNAPSHOT.jar` to replace my existing `immutables-value-2.8.8.jar`. I didn't know what is the difference between:
- `value/target/value-2.8.9-SNAPSHOT-annotations.jar` and
- `value-annotations/target/value-annotations-2.8.9-SNAPSHOT.jar`
but that one didn't seem to make a difference.

To double check if it's a problem with my build, I tried to build 2.8.8, but that one didn't compile:
```
Authentication failed for https://repo.spring.io/libs-milestone/com/atlassian/fugue/fugue/2.6.1/fugue-2.6.1.pom 401 Unauthorized
```

**Comment by marc-guenther** [comment]
I just spend some considerable time trying to _git bisect_ the slowness. It wasn't easy, as "slowness" wasn't well defined, sometimes it would crash, sometimes it would even finish successfully, and only take 1min longer than usual.

Anyway, it seems that this commit introduced the problem: 2b9a79ce

**Comment by elucash** [comment]
sounds scary. Thank you for digging this, will look into it

**Comment by marc-guenther** [comment]
Thanks. I just tried to cherry-pick your fix into 2.8.8, and that works perfectly fine, no problems with Eclipse, and the NPE is gone as well.

**Comment by elucash** [comment]
That's interesting finding, that that sluggishness/oom problem is orthogonal problem potentially introduces with seemingly innocent fix, yet it may not necessarily be the case, but a good lead. @SimY4 can you please look just in case you might have any ideas of possible performance regressing in Eclipse (commit 2b9a79c), I know this might be a bit out of context and this is not a definite cause of the problem (and also some developers never use Eclipse or ECJ), just inviting any ideas on that. Thank you!

**Comment by SimY4** [comment]
Can't find anything suspicious. @marc-guenther can you share more details of your setup? Which version of ECJ you're using? What other compiler arguments and annotation processors involved?

**Comment by marc-guenther** [comment]
Sorry for delay. I don't know, show we open a new issue, as it has nothing do to with this one?

Due to a legacy plugin that I need for work, I am unfortunately stuck with an old Eclipse version:
_Eclipse IDE for Java Developers: Version: 2019-03 (4.11.0) Build id: 20190314-1200_

There are no other annotation processors involved, but that legacy plugin adds its own Builders to the build, and we also launch some external shell scripts as Builders. Maybe there is some interconnection between these and immutables?

Have you tried it with current version of Eclipse, and it didn't slow down your build? Can I do anything to isolate this problem?

**Comment by elucash** [comment]
Agree that that could deserve another issue and maybe not directly connected, maybe I'll create one, just later
>> Is there a way to run ECJ from the command line?
yes, download the jdt, I'm puzzled what's on the Maven Central, but I've found the good old way is a download page of JDT released, like this one https://download.eclipse.org/eclipse/downloads/drops4/R-4.18-202012021800/  
under "JDT Core Batch Compiler"  https://download.eclipse.org/eclipse/downloads/drops4/R-4.18-202012021800/download.php?dropFile=ecj-4.18.jar

Then you can use this jar pretty much the same way as `javac` command `java -jar <downloaded jdt jar> <javac style command line options>`

**Comment by hennekey** [comment]
For what it's worth, using `org.immutables:value:2.9.1` as the processor in Eclipse 2024-06 resolved this error for me.
