### ISSUE TITLE
How to avoid the use of Guavas collections

### ISSUE THREAD

**Issue by hupfdule** [immutables/immutables#1284]
As the user guide states: "Collection attributes are backed by Guava immutable collections if Guava is available on the classpath."

Unfortunately Guava is even then considered if Guava is only in "provided" scope in a maven project.

For example:

```xml
<dependencies>
   <dependency>
     <groupId>com.example</groupId>
     <artifactId>dummy</artifactId>
     <version>1.0.0</version>
     <scope>provided</scope>
   </dependency>

   <dependency>
     <groupId>org.immutables</groupId>
     <artifactId>value</artifactId>
     <version>2.7.5</version>
     <scope>provided</scope>
   </dependency>
</dependencies>
```

com.example:dummy depends on Guava, but is not needed at runtime. Therefore Guava will not be available at runtime. But still immutables generates code using Guavas collections. At runtime this leads to 

```
Exception in thread "main" java.lang.NoClassDefFoundError: com/google/common/collect/ImmutableList
	at whatever.method(SomeClass.java:129)
Caused by: java.lang.ClassNotFoundException: com.google.common.collect.ImmutableList
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:606)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:168)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
```

Is there a way to explicitly tell immutables to not use Guava at all?

Actually it would be better if immutables would not take compile-time only dependencies into account, but I suspect that this is just not possible.

**Comment by hupfdule** [comment]
Nevermind.

Right after posting this I found it mentioned in a different issue.

`Style(jdkOnly=true)` is what I am searching for.
