### ISSUE TITLE
javac compilation error when using immutables concrete class as record property type

### ISSUE THREAD

**Issue by Tristan971** [immutables/immutables#1331]
Using: Immutables 2.8.8 on Java 16.0.2 on Linux

When using an immutables concrete class as type of a record property, javac fails with the error:
```
An exception has occurred in the compiler (16.0.2). Please file a bug against the Java compiler via the Java bug reporting page (http://bugreport.java.com) after checking the Bug Database (http://bugs.java.com) for duplicates. Include your program, the following diagnostic, and the parameters passed to the Java compiler in your report. Thank you.
java.lang.AssertionError: typeSig ERROR
        at jdk.compiler/com.sun.tools.javac.code.Types$SignatureGenerator.assembleSig(Types.java:5168)
        at jdk.compiler/com.sun.tools.javac.jvm.PoolWriter$SharedSignatureGenerator.assembleSig(PoolWriter.java:298)
        at jdk.compiler/com.sun.tools.javac.jvm.PoolWriter.typeSig(PoolWriter.java:492)
        at jdk.compiler/com.sun.tools.javac.jvm.PoolWriter.putDescriptor(PoolWriter.java:139)
        ...
```

Similarly to https://github.com/immutables/immutables/issues/1323 if you attempt compilation a second time without cleaning in-between, it succeeds

Reproducer at https://github.com/Tristan971/javac-typesig-error

For now I submitted a bug with javac since I'm not sure who's at fault, but here's one here too for completeness sake 🙂

**Comment by elucash** [comment]
Not 100% sure, but it seems that the problem is usage of not-yet-generated type for the record parameter. While it might work, I don't think this is something compiler strongly guarantees (sort of falls into the grey area between JLS and annotation processing rounds). Switching to abstract value types (i.e. the interfaces/abstract class which are manually written / have no prefixes with default styles etc.) might be the simplest fix, yet not necessarily possible to switch to abstract value types all over the place.
Well, Javac can learn to handle these not-yet-generated types of any annotation processor, this is not exclusive to Immutables if types to be used are not present but suppose to appear on later rounds of the compilation /w annotation processing. But I don't know if/how they will decide to handle it.

**Comment by Tristan971** [comment]
Yeah that does fix it (alongside the other similar issue). Too bad but understandable...

Guess I will have to get used to `@JsonSerialize(as = ...)` annotations all around :/
