### ISSUE TITLE
Eclipse fails to compile immutables with mixins

### ISSUE THREAD

**Issue by hwellmann** [immutables/immutables#1351]
Code sample:

```java
@Value.Immutable
public interface Foo extends Mixin<ImmutableFoo> {

    String bar();

    @Override
    default ImmutableFoo withProperty(String key, Object value) {
        return null;
    }
}

public interface Mixin<T> {

    T withProperty(String key, Object value);

    default List<String> warnings() {
        return Arrays.asList("foo", "bar");
    }
}

```

This compiles without problems using `javac`, but with the Eclipse compiler (or the Java Language Server used by VS Code), compilation fails with the following error

```
!MESSAGE org.immutables.value.internal.$processor$.$Processor threw java.lang.NullPointerException: Cannot read field "rank" because "leftIntratype" is null
	at org.immutables.value.internal.$generator$.$SourceOrdering$1CollectedOrdering.compare($SourceOrdering.java:260)
	at org.immutables.value.internal.$generator$.$SourceOrdering$1CollectedOrdering.compare($SourceOrdering.java:183)
	at java.base/java.util.TimSort.countRunAndMakeAscending(Unknown Source)
	at java.base/java.util.TimSort.sort(Unknown Source)
	at java.base/java.util.Arrays.sort(Unknown Source)
	at org.immutables.value.internal.$guava$.collect.$Ordering.immutableSortedCopy($Ordering.java:888)
	at org.immutables.value.internal.$generator$.$SourceOrdering.getAllAccessorsProvider($SourceOrdering.java:268)
	at org.immutables.value.internal.$processor$.meta.$AccessorAttributesCollector.collectGeneratedCandidateMethods($AccessorAttributesCollector.java:108)
	at org.immutables.value.internal.$processor$.meta.$AccessorAttributesCollector.collect($AccessorAttributesCollector.java:78)
	at org.immutables.value.internal.$processor$.meta.$ValueTypeComposer.compose($ValueTypeComposer.java:67)
	at org.immutables.value.internal.$processor$.meta.$Round.composeValue($Round.java:181)
	at org.immutables.value.internal.$processor$.meta.$Round.collectValues($Round.java:95)
	at org.immutables.value.internal.$processor$.$Processor.process($Processor.java:79)
	at org.immutables.value.internal.$generator$.$AbstractGenerator.process($AbstractGenerator.java:87)
	at org.immutables.processor.ProxyProcessor.process(ProxyProcessor.java:72)
	at org.eclipse.jdt.internal.compiler.apt.dispatch.RoundDispatcher.handleProcessor(RoundDispatcher.java:142)
	at org.eclipse.jdt.internal.compiler.apt.dispatch.RoundDispatcher.round(RoundDispatcher.java:124)
	at org.eclipse.jdt.internal.compiler.apt.dispatch.BaseAnnotationProcessorManager.processAnnotations(BaseAnnotationProcessorManager.java:172)
	at org.eclipse.jdt.internal.apt.pluggable.core.dispatch.IdeAnnotationProcessorManager.processAnnotations(IdeAnnotationProcessorManager.java:138)
	at org.eclipse.jdt.internal.compiler.Compiler.processAnnotations(Compiler.java:950)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:450)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:426)
```

See https://github.com/hwellmann/immutable-jdt/ for a minimal sample project.

As a workaround, `maven-processor-plugin` can be used to delegate annotation processing to `javac`.

**Comment by elucash** [comment]
I've tried it with 2.9.0-rc1 and seems to be working there, while the error is reproducible with 2.8.8
