### ISSUE TITLE
Documented method of using Wrapper types fails with Java 17 library target

### ISSUE THREAD

**Issue by mglazer** [immutables/immutables#1379]
I have created a minimal reproduction of this issue here:

https://github.com/mglazer/repro-javaseventeen-immutables

The crux of the issue, is that when using Java 17 as a library target, if you have a Wrapper type, using:

```javaa
@Value.Style(
        typeAbstract = "*Wrapper",
        typeImmutable = "*",
        visibility = Value.Style.ImplementationVisibility.PUBLIC,
        defaults = @Value.Immutable(builder = false, copy = false))
public @interface Wrapped {}
```

and:

```java
import com.fasterxml.jackson.annotation.JsonValue;
import org.immutables.value.Value;

public abstract class Wrapper<T> {
    @JsonValue
    @Value.Parameter
    abstract T value();

    @Override
    public final String toString() {
        return value().toString();
    }
}
```

And then attempt to use that construction, only with Java 17 will you get compilation errors:

```
> Task :repro-javaseventeen-immutables-core:compileJava FAILED
Round 1:
	input files: {com.palantir.reprojavaseventeenimmutables.UseRepro, com.palantir.reprojavaseventeenimmutables.Wrapper, com.palantir.reprojavaseventeenimmutables.Wrapped, com.palantir.reprojavaseventeenimmutables.ReproIssueWrapper}
	annotations: [org.immutables.value.Value.Immutable, com.fasterxml.jackson.annotation.JsonValue, org.immutables.value.Value.Parameter, java.lang.Override, org.immutables.value.Value.Style, com.palantir.reprojavaseventeenimmutables.Wrapped]
	last round: false
Processor org.gradle.api.internal.tasks.compile.processing.TimeTrackingProcessor matches [/org.immutables.value.Value.Immutable] and returns false.
Processor org.gradle.api.internal.tasks.compile.processing.SupportedOptionsCollectingProcessor matches [/com.palantir.reprojavaseventeenimmutables.Wrapped, /com.fasterxml.jackson.annotation.JsonValue, java.base/java.lang.Override, /org.immutables.value.Value.Immutable, /org.immutables.value.Value.Parameter, /org.immutables.value.Value.Style] and returns false.
warning: Was unable to read source file for com.palantir.reprojavaseventeenimmutables.UseRepro[com.sun.tools.javac.code.Symbol$ClassSymbol.class]: java.io.FileNotFoundException: com/palantir/reprojavaseventeenimmutables/UseRepro.java
Round 2:
	input files: {com.palantir.reprojavaseventeenimmutables.ImmutableUseRepro, com.palantir.reprojavaseventeenimmutables.ReproIssue}
	annotations: [org.immutables.value.Generated, java.lang.SuppressWarnings, javax.annotation.ParametersAreNonnullByDefault, javax.annotation.processing.Generated, javax.annotation.concurrent.Immutable, javax.annotation.CheckReturnValue, javax.annotation.concurrent.NotThreadSafe, javax.annotation.Nullable, com.google.errorprone.annotations.CanIgnoreReturnValue, java.lang.Override]
	last round: false
warning: Was unable to read source file for com.palantir.reprojavaseventeenimmutables.UseRepro[com.sun.tools.javac.code.Symbol$ClassSymbol.class]: java.io.FileNotFoundException: com/palantir/reprojavaseventeenimmutables/UseRepro.java

Processor org.gradle.api.internal.tasks.compile.processing.TimeTrackingProcessor matches [] and returns false.
Processor org.gradle.api.internal.tasks.compile.processing.SupportedOptionsCollectingProcessor matches [/javax.annotation.concurrent.NotThreadSafe, /javax.annotation.Nullable, /com.google.errorprone.annotations.CanIgnoreReturnValue, /javax.annotation.CheckReturnValue, java.compiler/javax.annotation.processing.Generated, /javax.annotation.concurrent.Immutable, /org.immutables.value.Generated, java.base/java.lang.SuppressWarnings, java.base/java.lang.Override, /javax.annotation.ParametersAreNonnullByDefault] and returns false.
Round 3:
	input files: {}
	annotations: []
	last round: true
error: warnings found and -Werror specified
1 error
1 warning
error: warnings found and -Werror specified
```

The most noticeable error which occurs when verbose processor logging is disabled is the:

```
warning: Was unable to read source file for com.palantir.reprojavaseventeenimmutables.UseRepro[com.sun.tools.javac.code.Symbol$ClassSymbol.class]: java.io.FileNotFoundException: com/palantir/reprojavaseventeenimmutables/UseRepro.java
```

Otherwise, I have been unable to find anything that sticks out from the compilation messages.

I have attempted this with both Immutables 2.8.8 and 2.9.0 and it reproduces on both.

**Comment by carterkozak** [comment]
I think this comment from @elucash is relevant https://github.com/immutables/immutables/issues/1323#issuecomment-892324669, in particular I think this is one of the "more complex cases" described:
> Most of the time this should not be an issue, but it may result in some more complex cases not working

The warning was removed in https://github.com/immutables/immutables/commit/1bf9e63077708869be2302d82d70a5f9d1dfd529 which makes it a bit harder to work backward from failing compilation to a root cause.

**Comment by Magotchi** [comment]
The minimal reproduction example referenced here can be made to compile (with an unrelated warning about the usage of `@Value.Style`), by:

changing from:
```java
@Value.Immutable
public interface UseRepro {
    ReproIssue issue();
}
```

to:
```java
@Value.Immutable
public interface UseRepro {
    ReproIssueWrapper issue();
}
```

In other words, it can be fixed, at least very trivially, by referencing the interface (or abstract class) rather than the generated concrete class.

My general strategy to fix these kinds of issues has been to do away with referencing the concrete, generated classes, especially in other Immutables-using code, but really just everywhere, and to use the "sandwich" style as shown on the [current README for this project](https://github.com/immutables/immutables/blob/b21e6bbfbb9038100532416c81e8270951c3e03a/README.md#modern-usage-style-aka-sandwich).  You'll also see lots of examples of @elucash mentioning the "sandwich" style, and its benefits relating to issues like this, if you [search Issues for "sandwich"](https://github.com/immutables/immutables/issues?q=is%3Aissue+sandwich). IMO the main Immutables website's documentation could use some updating at some point to explain the benefits of the "sandwich" style, or generally not referencing the concrete classes, in light of Java 16+ changes.

**Comment by elucash** [comment]
Sorry for joining the discussion only now. I'm trying to understand if something can be done here aside any workarounds. I would totally agree that avoiding using not-yet-generated types is a good thing and we need to check if documentation is sufficiently clear on that, but sometimes there some processor code fixes/improvements can be made (as some other issues shown).
Tried to use repro, but for some reason when java 17 is used (no workarounds and no change to 11, only change is Retention.SOURCE for `Wrapped` so no compile error)

```
$ echo $JAVA_HOME
/Library/Java/JavaVirtualMachines/zulu-17.jdk/Contents/Home
$ java -version
openjdk version "17.0.1" 2021-10-19 LTS
OpenJDK Runtime Environment Zulu17.30+15-CA (build 17.0.1+12-LTS)
OpenJDK 64-Bit Server VM Zulu17.30+15-CA (build 17.0.1+12-LTS, mixed mode, sharing)
$ ./gradlew compileJava

> Task :repro-javaseventeen-immutables-core:compileJava
Round 1:
        input files: {com.palantir.reprojavaseventeenimmutables.ReproIssueWrapper, com.palantir.reprojavaseventeenimmutables.Wrapper, com.palantir.reprojavaseventeenimmutables.UseRepro, com.palantir.reprojavaseventeenimmutables.Wrapped}
        annotations: [org.immutables.value.Value.Immutable, com.palantir.reprojavaseventeenimmutables.Wrapped, com.fasterxml.jackson.annotation.JsonValue, org.immutables.value.Value.Parameter, java.lang.Override, java.lang.annotation.Retention, org.immutables.value.Value.Style]
        last round: false
Processor org.gradle.api.internal.tasks.compile.processing.TimeTrackingProcessor matches [/org.immutables.value.Value.Immutable] and returns false.
Processor org.gradle.api.internal.tasks.compile.processing.SupportedOptionsCollectingProcessor matches [/com.palantir.reprojavaseventeenimmutables.Wrapped, /com.fasterxml.jackson.annotation.JsonValue, java.base/java.lang.Override, /org.immutables.value.Value.Immutable, /org.immutables.value.Value.Parameter, java.base/java.lang.annotation.Retention, /org.immutables.value.Value.Style] and returns false.
Round 2:
        input files: {com.palantir.reprojavaseventeenimmutables.ReproIssue, com.palantir.reprojavaseventeenimmutables.ImmutableUseRepro}
        annotations: [org.immutables.value.Generated, java.lang.SuppressWarnings, javax.annotation.ParametersAreNonnullByDefault, javax.annotation.processing.Generated, javax.annotation.concurrent.Immutable, javax.annotation.CheckReturnValue, java.lang.Override, javax.annotation.Nullable, javax.annotation.concurrent.NotThreadSafe, com.google.errorprone.annotations.CanIgnoreReturnValue]
        last round: false
Processor org.gradle.api.internal.tasks.compile.processing.TimeTrackingProcessor matches [] and returns false.
Processor org.gradle.api.internal.tasks.compile.processing.SupportedOptionsCollectingProcessor matches [/javax.annotation.concurrent.NotThreadSafe, /javax.annotation.Nullable, /com.google.errorprone.annotations.CanIgnoreReturnValue, /javax.annotation.CheckReturnValue, java.compiler/javax.annotation.processing.Generated, /javax.annotation.concurrent.Immutable, /org.immutables.value.Generated, java.base/java.lang.SuppressWarnings, java.base/java.lang.Override, /javax.annotation.ParametersAreNonnullByDefault] and returns false.
Round 3:
        input files: {}
        annotations: []
        last round: true

BUILD SUCCESSFUL in 3s
3 actionable tasks: 2 executed, 1 up-to-date
```

**Comment by carterkozak** [comment]
> I cannot reproduce the issue

It's certainly odd -- when I use jetbrains idea with gradle integratoin, it fails, however a full compile from the command line succeeds. I'm also setting compiler args for incremental compilation, although it seemed to reproduce even without this option: `-Aimmutables.gradle.incremental`

**Comment by Magotchi** [comment]
@elucash is correct.  I was mistaken.  I can only reproduce the `Retention.SOURCE` for `Wrapped` warning with `./gradlew compileJava` on the original reproduction code above.  I cannot reproduce any compile errors.  It builds fine when the `-Werror` compiler option is removed from build.gradle.  The first time, I had first made the "fix" as I described, it still wasn't building, and **then** I removed `-Werror`.

**Comment by Magotchi** [comment]
@carterkozak: Just now, I opened your repo's clone URL directly as a new IDEA CE project, said I trusted the project, did Build Project, and it gave me the warning-as-error via `-Werror`.  After removing the compile options in build.gradle, it gives me nothing but the following warning:
```
warning: Was unable to read source file for com.palantir.reprojavaseventeenimmutables.UseRepro[com.sun.tools.javac.code.Symbol$ClassSymbol.class]: java.io.FileNotFoundException: com/palantir/reprojavaseventeenimmutables/UseRepro.java
```

I'm using IntelliJ IDEA 2022.2.2 (Community Edition), Build #IC-222.4167.29.

**Comment by carterkozak** [comment]
Sorry, I think my failure was slightly different, based on the [Tuple pattern in the docs](https://immutables.github.io/immutable.html#tuple-style):

Working reproducer here: https://github.com/carterkozak/immutables-jdk17-repro

**Comment by elucash** [comment]
I've tried the new repro (and the old one with IDEA). For the command line `./gradlew compileJava` everything seems to work correctly. I was able to see the problem within IDE. For some reason, the sources are not made available to the annotation processor when run by IDEA. This is probably related to internal compiler setup. I would expect something like that can be a problem in incremental/isolated mode with restrictions on writing / reading files and resources. In the case of the first repro there's just warning which fails together with `-Werror`. See if the problem is gone in Immutables 2.9.2, the warning was removed / changed (IIRC, might be wrong). With the second repo (`One.java:20: error: cannot find symbol`), the problem is that `Two` is not get generated and not resolved, we only insert `import net.ckozak.immutables.repro.two.Two;` in the generated file if Immutables can read the source of `One` it will see the import and will add one, otherwise `Two` stays as it is in the source form and there is no remedy for that. Rebuilding on the command can "fix" this. Moreover if `options.sourcepath = files(sourceSets.findByName("main").allJava.srcDirs)` makes it work in the IDE (and as I've tried - seems to work), then I would conclude it is a valid, correct way to solve it.

**Comment by elucash** [comment]
The using `TwoTuple` is a key difference. When compiling ` One {... TwoTuple issue()`, the class/interface `TwoTuple` is known to compiler, it knows the package it comes from, full name/path etc. In the generated code all imports are processed properly. But when using ` One {... Two issue()`, the compiler says to us (to Immutables processor), "—  look, here's some broken and not available type called Two, I wash my hands", then processor says to itself, "— Oki-doki, we'll use this type anyway in case it will be generated, but if it comes from another package we're busted, only if there would be source code available, we could try to parse imports from there...", and the annotation processor uses ~dark magic~ javac/ecj specific ways to access the underlying source code and if it succeeds and founds import from another package for `Two` it will put such an import into generated file, but if it's not – then type name `Two` copied in the generated code as is (if it's in the same package – that will work).

**Comment by carterkozak** [comment]
Oh gosh, I see the difference between the command-line and javac cases: running within idea, we're missing some exports that are necessary for immutables, so despite both using javac, running within idea uses the SourceExtractor.DefaultExtractor while on the command line we get the SourceExtractor.JavacSourceExtractor` due to:
```
java.lang.IllegalAccessError: class org.immutables.value.internal.$generator$.$Compiler (in unnamed module @0x732ce05b) cannot access class com.sun.tools.javac.code.Symbol$ClassSymbol (in module jdk.compiler) because module jdk.compiler does not export com.sun.tools.javac.code to unnamed module @0x732ce05b
	at org.immutables.value.internal.$generator$.$Compiler.detectCompilers($Compiler.java:38)
	at org.immutables.value.internal.$generator$.$Compiler.<clinit>($Compiler.java:31)
	..etc
```

Why does this only occur in the IDE? A gradle plugin in my default template uses error-prone static analysis, which requires some compiler exports to function, which allow the SourceExtractor code to work correctly in jdk-17. :hot_pepper: The plugin doesn't apply error-prone when it detects intellij for historical reasons :hot_pepper:

I've pushed a commit to my repro which opts out of error-prone, allowing a repro from the command line.
I suspect we may want to bring back the compiler warning where we can recommend adding exports to support the annotation processor.

**Comment by elucash** [comment]
Great finding! Additional detail is that after failing with javac access (missing exports) processor proceeds to attempt to read sources from sourcepath, explaining why it works with sourcepath in the IDE.

Should we then require javac args to have `--add-exports`, and would it be less of a burden than sourcepath setting? Anyway it worth adding to the docs somewhere.

**Comment by carterkozak** [comment]
Thanks! I think we could detect the javac access error and provide a warning suggesting add-exports in addition to documentation improvements.
Warning feels right because there’s a fallback that works in many configurations.

**Comment by talios** [comment]
I wonder if IDEA is somehow putting it on the module path, vs CLI at the
class path (or vice versa)?
-- 
"Great artists are extremely selfish and arrogant things" — Steven Wilson,
Porcupine Tree

**Comment by elucash** [comment]
There's configuration option, to use module path or just classpath, but anyway, they have IDE custom environment, it's hard to say what exactly goes there.
<img width="578" alt="idea-annotation" src="https://user-images.githubusercontent.com/1692611/195129550-c6a7e141-e455-4813-b497-35799b1e3f0a.png">
