### ISSUE TITLE
Non-termination or generation with 2.9.1

### ISSUE THREAD

**Issue by talios** [immutables/immutables#1397]
Under the newly released 2.9.1, on _some_ modules in my project (one so far) I seem to end up with the non-terminating compile phase in maven, with no classes being generated under `target/generated-sources/annotations`.

This runs fine under 2.9.0 - what's the best way to debug what immutables is doing?

Are there any debug flags I can enable to provide more information?

**Comment by talios** [comment]
I seem to have traced this down to my usage of a custom annotation:

```java
@Target(ElementType.TYPE)
@Value.Style(jdkOnly = true, typeAbstract = "*Def", typeImmutable = "*", allParameters = true, defaultAsDefault = true,
             visibility = Value.Style.ImplementationVisibility.PUBLIC,
             defaults = @Value.Immutable(builder = false, copy = false, intern = false, prehash = true))
public @interface ImmutableValue {
}
```

when my code uses:

```java
@ImmutableValue
public interface RuleSetDef {
  Integer id();
  String name();
}
```

The compilation hangs, when switching that to:

```java
@Value.Immutable(
    builder = false,
    copy = false,
    intern = false,
    prehash = true
)
@Value.Style(
    jdkOnly = true,
    typeAbstract = {"*Def"},
    typeImmutable = "*",
    allParameters = true,
    defaultAsDefault = true,
    visibility = Value.Style.ImplementationVisibility.PUBLIC)
public interface RuleSetDef {
  Integer id();
  String name();
}
```

compilation succeeds. Unfortunately, when splitting this out to a standalone project - it compiled file using the custom annotation (much like several other modules in my project).

**Comment by elucash** [comment]
Hi Mark, I'm trying to check what changes might have caused this. I'm wondering, if it really hangs, if there any chance to capture JVM thread dump of the build process, chances are there could be some classloading deadlock. In a meantime I'm trying to create some repro, it's happening under Maven, right? Is custom annotation in the same module as the annotated type or it is imported from another artifact?

**Comment by talios** [comment]
```
2022-08-25 09:59:28
Full thread dump OpenJDK 64-Bit Server VM (25.342-b07 mixed mode):

"Attach Listener" #17 daemon prio=9 os_prio=31 tid=0x00007fe7ef7d6800 nid=0xa203 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"resolver-5" #16 daemon prio=5 os_prio=31 tid=0x00007fe7a814c000 nid=0xa303 waiting on condition [0x0000700007e44000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000005c03b3718> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2044)
	at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)

"resolver-4" #15 daemon prio=5 os_prio=31 tid=0x00007fe7a814b000 nid=0xa503 waiting on condition [0x0000700007d41000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000005c03b3718> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2044)
	at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)

"resolver-3" #14 daemon prio=5 os_prio=31 tid=0x00007fe7693a8800 nid=0x5903 waiting on condition [0x0000700007c3e000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000005c03b3718> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2044)
	at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)

"resolver-2" #13 daemon prio=5 os_prio=31 tid=0x00007fe7693a7800 nid=0xa703 waiting on condition [0x0000700007b3b000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000005c03b3718> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2044)
	at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)

"resolver-1" #12 daemon prio=5 os_prio=31 tid=0x00007fe768b8c000 nid=0x3407 waiting on condition [0x0000700007a38000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000005c03b3718> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2044)
	at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)

"Service Thread" #9 daemon prio=9 os_prio=31 tid=0x00007fe80101e800 nid=0xa903 runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C1 CompilerThread3" #8 daemon prio=9 os_prio=31 tid=0x00007fe7ff028000 nid=0x3c03 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread2" #7 daemon prio=9 os_prio=31 tid=0x00007fe80081a800 nid=0x3b03 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread1" #6 daemon prio=9 os_prio=31 tid=0x00007fe7ff027800 nid=0x3f03 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread0" #5 daemon prio=9 os_prio=31 tid=0x00007fe7ff84e800 nid=0x3903 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Signal Dispatcher" #4 daemon prio=9 os_prio=31 tid=0x00007fe7ff015800 nid=0x3703 runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Finalizer" #3 daemon prio=8 os_prio=31 tid=0x00007fe800817000 nid=0x4703 in Object.wait() [0x000070000711a000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x00000005c0010018> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:144)
	- locked <0x00000005c0010018> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:165)
	at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:216)

"Reference Handler" #2 daemon prio=10 os_prio=31 tid=0x00007fe7ff00d000 nid=0x3103 in Object.wait() [0x0000700007017000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x00000005c0020a50> (a java.lang.ref.Reference$Lock)
	at java.lang.Object.wait(Object.java:502)
	at java.lang.ref.Reference.tryHandlePending(Reference.java:191)
	- locked <0x00000005c0020a50> (a java.lang.ref.Reference$Lock)
	at java.lang.ref.Reference$ReferenceHandler.run(Reference.java:153)

"main" #1 prio=5 os_prio=31 tid=0x00007fe801009000 nid=0x2803 runnable [0x00007000063f0000]
   java.lang.Thread.State: RUNNABLE
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1718)
	at org.immutables.value.internal.$processor$.meta.$Proto$MetaAnnotated.from($Proto.java:248)
	at org.immutables.value.internal.$processor$.meta.$Proto$MetaAnnotated.encodings($Proto.java:138)
	at org.immutables.value.internal.$processor$.meta.$ImmutableProto$MetaAnnotated.access$101($ImmutableProto.java:47)
	at org.immutables.value.internal.$processor$.meta.$ImmutableProto$MetaAnnotated$InitShim.encodings($ImmutableProto.java:123)
	at org.immutables.value.internal.$processor$.meta.$ImmutableProto$MetaAnnotated.<init>($ImmutableProto.java:71)
	at org.immutables.value.internal.$processor$.meta.$ImmutableProto$MetaAnnotated.of($ImmutableProto.java:524)
	at org.immutables.value.internal.$processor$.meta.$Proto$MetaAnnotated.lambda$from$0($Proto.java:248)
	at org.immutables.value.internal.$processor$.meta.$Proto$MetaAnnotated$$Lambda$578/1458088096.apply(Unknown Source)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
	- locked <0x00000007164ade50> (a java.util.concurrent.ConcurrentHashMap$ReservationNode)
	at org.immutables.value.internal.$processor$.meta.$Proto$MetaAnnotated.from($Proto.java:248)
	at org.immutables.value.internal.$processor$.meta.$Proto$AbstractDeclaring.metaAnnotated($Proto.java:630)
	at org.immutables.value.internal.$processor$.meta.$ImmutableProto$DeclaringType.metaAnnotated($ImmutableProto.java:2539)
	- locked <0x00000007164ad540> (a org.immutables.value.internal.$processor$.meta.$ImmutableProto$DeclaringType)
	at org.immutables.value.internal.$processor$.meta.$Proto$DeclaringType.isEnclosing($Proto.java:1105)
	at org.immutables.value.internal.$processor$.meta.$ImmutableProto$DeclaringType.isEnclosing($ImmutableProto.java:3025)
	- locked <0x00000007164ad540> (a org.immutables.value.internal.$processor$.meta.$ImmutableProto$DeclaringType)
	at org.immutables.value.internal.$processor$.meta.$Proto$DeclaringType.validate($Proto.java:1203)
	at org.immutables.value.internal.$processor$.meta.$ImmutableProto$DeclaringType.validate($ImmutableProto.java:3250)
	at org.immutables.value.internal.$processor$.meta.$ImmutableProto$DeclaringType.access$2800($ImmutableProto.java:2094)
	at org.immutables.value.internal.$processor$.meta.$ImmutableProto$DeclaringType$Builder.build($ImmutableProto.java:3352)
	at org.immutables.value.internal.$processor$.meta.$Round.declaringTypeFrom($Round.java:171)
	at org.immutables.value.internal.$processor$.meta.$Round$ProtoclassCollecter.collectIncludedAndDefinedBy($Round.java:303)
	at org.immutables.value.internal.$processor$.meta.$Round$ProtoclassCollecter.collect($Round.java:202)
	at org.immutables.value.internal.$processor$.meta.$Round$ProtoclassCollecter.collect($Round.java:191)
	at org.immutables.value.internal.$processor$.meta.$Round.collectProtoclasses($Round.java:112)
	at org.immutables.value.internal.$processor$.meta.$Round.collectValues($Round.java:66)
	at org.immutables.value.internal.$processor$.$Processor.process($Processor.java:79)
	at org.immutables.value.internal.$generator$.$AbstractGenerator.process($AbstractGenerator.java:94)
	at org.immutables.processor.ProxyProcessor.process(ProxyProcessor.java:72)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:968)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:884)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$2200(JavacProcessingEnvironment.java:108)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1206)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1315)
	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1246)
	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:922)
	at com.sun.tools.javac.api.JavacTaskImpl.lambda$doCall$0(JavacTaskImpl.java:100)
	at com.sun.tools.javac.api.JavacTaskImpl$$Lambda$494/479162791.call(Unknown Source)
	at com.sun.tools.javac.api.JavacTaskImpl.handleExceptions(JavacTaskImpl.java:142)
	at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:96)
	at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:90)
	at com.google.errorprone.BaseErrorProneCompiler.run(BaseErrorProneCompiler.java:143)
	at com.google.errorprone.BaseErrorProneCompiler.run(BaseErrorProneCompiler.java:114)
	at com.google.errorprone.ErrorProneCompiler.run(ErrorProneCompiler.java:121)
	at org.codehaus.plexus.compiler.javac.errorprone.JavacCompilerWithErrorProne$CompilerInvoker.compile(JavacCompilerWithErrorProne.java:223)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.compiler.javac.errorprone.JavacCompilerWithErrorProne.performCompile(JavacCompilerWithErrorProne.java:91)
	at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:1209)
	at org.apache.maven.plugin.compiler.CompilerMojo.execute(CompilerMojo.java:198)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2(MojoExecutor.java:370)
	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute(MojoExecutor.java:351)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:215)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:171)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:163)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:294)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:960)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:293)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)

"VM Thread" os_prio=31 tid=0x00007fe7ff844800 nid=0x4903 runnable 

"ParGC Thread#0" os_prio=31 tid=0x00007fe801015800 nid=0x1b07 runnable 

"ParGC Thread#1" os_prio=31 tid=0x00007fe7ff80e800 nid=0x1d03 runnable 

"ParGC Thread#2" os_prio=31 tid=0x00007fe7ff80f000 nid=0x5403 runnable 

"ParGC Thread#3" os_prio=31 tid=0x00007fe7ff810000 nid=0x2b03 runnable 

"ParGC Thread#4" os_prio=31 tid=0x00007fe800808800 nid=0x5103 runnable 

"ParGC Thread#5" os_prio=31 tid=0x00007fe800809800 nid=0x5003 runnable 

"ParGC Thread#6" os_prio=31 tid=0x00007fe80080a000 nid=0x4e03 runnable 

"ParGC Thread#7" os_prio=31 tid=0x00007fe80080b000 nid=0x4c03 runnable 

"ParGC Thread#8" os_prio=31 tid=0x00007fe80080b800 nid=0x4a03 runnable 

"ParGC Thread#9" os_prio=31 tid=0x00007fe80080c800 nid=0x2e03 runnable 

"VM Periodic Task Thread" os_prio=31 tid=0x00007fe800853800 nid=0x5703 waiting on condition 

JNI global references: 1786
```

Interesting - there seems to be a concurrent map issue:

```
"main" #1 prio=5 os_prio=31 tid=0x00007fe801009000 nid=0x2803 runnable [0x00007000063f0000]
   java.lang.Thread.State: RUNNABLE
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1718)
	at org.immutables.value.internal.$processor$.meta.$Proto$MetaAnnotated.from($Proto.java:248)
	at org.immutables.value.internal.$processor$.meta.$Proto$MetaAnnotated.encodings($Proto.java:138)
	at org.immutables.value.internal.$processor$.meta.$ImmutableProto$MetaAnnotated.access$101($ImmutableProto.java:47)
```


The custom annotation is in a separate jar, with it's classname mentioned in `META-INF/annotation/org.immutables.value.immutable`.

**Comment by talios** [comment]
I should note I'm running this from maven, using the `javac-with-errorprone` compilerId plugin (using the [NullAway](https://github.com/uber/NullAway) project.

**Comment by elucash** [comment]
The interesting about concurrent map is that `computeIfAbsent` call seems to be recursive, and if this is happening on the same map instance - this can be part of the issue / sort of deadlock (computing entry while computing another entry). looking into it. Thank you for the dump, definitely we have some pointers for now

**Comment by talios** [comment]
I see that was added on 10484c987a617a:

```
@@ -235,9 +246,8 @@ public class Proto {
       String name = element.getQualifiedName().toString();
+      return metaAnnotatedCache()
+          .computeIfAbsent(name, n -> ImmutableProto.MetaAnnotated.of(element, name, environment));
+    }
```

I've still not been able to reproduce this in a standalone project tho - which is kinda annoying.

**Comment by elucash** [comment]
Quick idea is to just replace "fancy" `computeIfAbsent` to the old way of lazy creation, where `MetaAnnotated.of(` construction was happening outside of CHM internals.

**Comment by talios** [comment]
@elucash Reverting to the version from a0010e93e41402 (and slightly adapting to current code - `cache` replaced with `metaAnnotatedCache()`):

```java
    public static MetaAnnotated from(AnnotationMirror mirror, Environment environment) {
      TypeElement element = (TypeElement) mirror.getAnnotationType().asElement();
      String name = element.getQualifiedName().toString();

      @Nullable MetaAnnotated metaAnnotated = metaAnnotatedCache().get(name);
      if (metaAnnotated == null) {
        metaAnnotated = ImmutableProto.MetaAnnotated.of(element, name, environment);
        @Nullable MetaAnnotated existing = metaAnnotatedCache().putIfAbsent(name, metaAnnotated);
        if (existing != null) {
          metaAnnotated = existing;
        }
      }

      return metaAnnotated;
    }
```

after rebuilding 1.9.1 locally, my build works.

**Comment by elucash** [comment]
yep, I did just that...
a sign of a soon 2.9.2
     ..summer wind

**Comment by talios** [comment]
I won't submit my PR then :)  Cheers.

**Comment by XN137** [comment]
thanks for fixing this!
we might want to mark this issue as closed.

wondering: did this only affect custom annotations?
if yes maybe issue name should reflect this.

> The interesting about concurrent map is that computeIfAbsent call seems to be recursive, and if this is happening on the same map instance - this can be part of the issue / sort of deadlock (computing entry while computing another entry).

javadoc of `ConcurrentMap.compute*` methods explicitly state:

> The mapping function should not modify this map during computation.

the recursion comes from `$Proto$MetaAnnotated.from` (see 2nd and last line):
```
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1718)
	at org.immutables.value.internal.$processor$.meta.$Proto$MetaAnnotated.from($Proto.java:248)
	at org.immutables.value.internal.$processor$.meta.$Proto$MetaAnnotated.encodings($Proto.java:138)
	at org.immutables.value.internal.$processor$.meta.$ImmutableProto$MetaAnnotated.access$101($ImmutableProto.java:47)
	at org.immutables.value.internal.$processor$.meta.$ImmutableProto$MetaAnnotated$InitShim.encodings($ImmutableProto.java:123)
	at org.immutables.value.internal.$processor$.meta.$ImmutableProto$MetaAnnotated.<init>($ImmutableProto.java:71)
	at org.immutables.value.internal.$processor$.meta.$ImmutableProto$MetaAnnotated.of($ImmutableProto.java:524)
	at org.immutables.value.internal.$processor$.meta.$Proto$MetaAnnotated.lambda$from$0($Proto.java:248)
	at org.immutables.value.internal.$processor$.meta.$Proto$MetaAnnotated$$Lambda$578/1458088096.apply(Unknown Source)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
	- locked <0x00000007164ade50> (a java.util.concurrent.ConcurrentHashMap$ReservationNode)
	at org.immutables.value.internal.$processor$.meta.$Proto$MetaAnnotated.from($Proto.java:248)
```
so the loading function did not obey this contract by trying to modify the map at the same time as computing a new value for it.

**Comment by elucash** [comment]
that was an unintended effect, was hard to trace all code paths while making the change. A deadlock may have effected other functionality or certain combination of annotations, but no such cases were reported, only the one with custom immutable annotation
