### ISSUE TITLE
Error processing type with annotated type argument

### ISSUE THREAD

**Issue by tobyhammett** [immutables/immutables#1454]
Consider an interface with an accessor that has an annotated type argument like this:

```
@Value.Immutable
public interface ValueObject {

  MyGenericType<@Size(min = 1, max = 99) String> getValue();

}
```
Under Java 11+ the annotation processor fails to process this interface.  (Interestingly, it succeeds on Java 8.)

The error on Java 17 is:
```
 org.immutables.value.internal.$processor$.$Processor threw org.immutables.value.internal.$guava$.base.$VerifyException: [T] =/> [@com.example.Size(min=1, max=99)java.lang.String]
        at org.immutables.value.internal.$guava$.base.$Verify.verify($Verify.java:125)
        at org.immutables.value.internal.$generator$.$TypeHierarchyCollector$TypevarContext.<init>($TypeHierarchyCollector.java:59)
        at org.immutables.value.internal.$generator$.$TypeHierarchyCollector.collectHierarchyMirrors($TypeHierarchyCollector.java:106)
        at org.immutables.value.internal.$generator$.$TypeHierarchyCollector.collectFrom($TypeHierarchyCollector.java:69)
        at org.immutables.value.internal.$processor$.meta.$TypeIntrospectionBase.collectTypeHierarchy($TypeIntrospectionBase.java:155)
        at org.immutables.value.internal.$processor$.meta.$TypeIntrospectionBase.introspectTypeMirror($TypeIntrospectionBase.java:147)
        at org.immutables.value.internal.$processor$.meta.$ValueAttribute.introspectType($ValueAttribute.java:837)
        at org.immutables.value.internal.$processor$.meta.$TypeIntrospectionBase.ensureTypeIntrospected($TypeIntrospectionBase.java:81)
        at org.immutables.value.internal.$processor$.meta.$ValueAttribute.initTypeKind($ValueAttribute.java:1397)
        at org.immutables.value.internal.$processor$.meta.$ValueAttribute.initAndValidate($ValueAttribute.java:1166)
        at org.immutables.value.internal.$processor$.meta.$AccessorAttributesCollector.collect($AccessorAttributesCollector.java:85)
        at org.immutables.value.internal.$processor$.meta.$ValueTypeComposer.compose($ValueTypeComposer.java:67)
        at org.immutables.value.internal.$processor$.meta.$Round.composeValue($Round.java:181)
        at org.immutables.value.internal.$processor$.meta.$Round.collectValues($Round.java:95)
        at org.immutables.value.internal.$processor$.$Processor.process($Processor.java:79)
        at org.immutables.value.internal.$generator$.$AbstractGenerator.process($AbstractGenerator.java:87)
        at org.immutables.processor.ProxyProcessor.process(ProxyProcessor.java:72)
        at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:1023)
        at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:939)
        at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1267)
        at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1382)
        at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1234)
        at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:916)
        at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.lambda$doCall$0(JavacTaskImpl.java:104)
        at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.invocationHelper(JavacTaskImpl.java:152)
        at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:100)
        at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:94)
        at org.codehaus.plexus.compiler.javac.JavaxToolsCompiler.compileInProcess(JavaxToolsCompiler.java:136)
        at org.codehaus.plexus.compiler.javac.JavacCompiler.performCompile(JavacCompiler.java:183)
        at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:1140)
        at org.apache.maven.plugin.compiler.CompilerMojo.execute(CompilerMojo.java:193)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:957)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:289)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:193)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)

```

The issue stems from incorrect parsing in `SourceTypes` which thinks that the `, ` separating the annotation properties is separating two different type arguments.

**Comment by elucash** [comment]
I'm definitely think this might be not the best thing to do (fixing ad-hoc parsing), but also quite terrified to change this thing as it caused a number of problems previously and I cannot fully evaluate reliably if any of the old workarounds are obsolete now. Fixed version should be a lot better with annotations and their elements (including string and char literals). This will be in the next release, available in master now.

**Comment by tobyhammett** [comment]
Thank you for the fix! I can appreciate that fixing the ad-hoc parsing is safer than relying on the (potentially super old) compiler.

**Comment by tobyhammett** [comment]
I tried the using code on master to build one of our projects and found another case where the ad-hoc parsing fails: where there are multiple annotations on the type argument. Here's a minimal reproduction:

```
package org.immutables.fixture;

import javax.validation.constraints.Email;
import javax.validation.constraints.Size;
import org.immutables.value.Value;

@Value.Immutable
public interface HasTypeAnnotationWithAttributes {

  interface Container<T> {}
  Container<@Size(min = 1, max = 99) @Email String> container();
}
```

I found that Collections seem to have special handling and don't exercise the ad-hoc parsing code, so the bug only appears when using a non-standard generic type as the outer type.

Digging into this a little bit, the String representation that's passed to `TypevarContext` actually isn't what I expected.  The String the parser sees is actually `org.immutables.fixture.HasMultipleAnnotations.Container<@javax.validation.constraints.Size(min=1, max=99),@javax.validation.constraints.Email java.lang.String>` not what's actually in the source code. The difference is the comma between the two annotations. This string comes from `TypeMirror.toString()`, called from `TypeHierarchyCollector` line 69.

In case the behavior of `TypeMirror.toString()` varies across compilers, I should add that the implementation of TypeMirror where I'm seeing this is `com.sun.tools.javac.code.Type.ClassType` using Java version: 11.0.11, vendor: AdoptOpenJDK.

Would you consider using the TypeMirror's typeArguments directly as in the PR #1455 if that behavior was added as a fallback to the existing parsing, or vice versa?

**Comment by elucash** [comment]
I've added some new code to handle the situation. Per my current understanding, the PR would not work either, because it uses `TypeMirror.toString()`, which have this defect. The defect (at least in Javac 11) is placing comma instead of space between annotations:  `@javax.validation.constraints.Size(min=1, max=99),@javax.validation.constraints.Email java.lang.String`. Too many ad-hoc routines we have for all of this, but a lot of issues were with not-yet-generated-types and compiler bugs like the "wrong" `.toString()` on types, but I will be able to consolidate all of this if dropping a lot of compatibility, including Java versions and problematic features of Immutables, which will only be possible in a new major version.
