### ISSUE TITLE
Criteria ClassCastException: ReactorFetcherDelegate -> ReactorFetcher$DistinctLimitOffset

### ISSUE THREAD

**Issue by Drevsh** [immutables/immutables#1456]
When Using a Mongo or InMemoty backend and trying to execute a `find` followed by a `select` a ClassCastException is thrown:

Example code:
```
public Mono<ExistingAndMissingQueryResult<String>> findAvailableAndMissingIds(Collection<String> ids) {
        Criterion<LabelEntity> criterion = idMatcher().in(ids);

        return readRepository().find(criterion)
                .select(LabelEntityCriteria.labelEntity.id)
                .fetch()
                .collect(Collectors.toSet())
                .map(existing -> computeAvailableAndAbsent(ids, existing));
    }

    private ExistingAndMissingQueryResult<String> computeAvailableAndAbsent(Collection<String> all,
            Set<String> existing) {
        Set<String> missing = new HashSet<>(all);
        missing.removeIf(existing::contains);
        return _ExistingAndMissingQueryResult.of(existing, missing);
    }
``` 

```
Original Stack Trace:
		at org.immutables.criteria.reactor.ReactorMappers$Mapper1.<init>(ReactorMappers.java:59)
		at org.immutables.criteria.reactor.ReactorMappers$Mapper1.<init>(ReactorMappers.java:54)
		at org.immutables.criteria.reactor.ReactorMappers$Mapper1.<init>(ReactorMappers.java:50)
		at org.immutables.criteria.reactor.ReactorReader.select(ReactorReader.java:60)
```

Exception is thrown in `ReactorMappers` in 
```
        private Mapper1(ReactiveMapper1<T1> mapper, ReactorFetcher<T1> fetcher) {
            this.mapper = mapper;
            this.fetcher = (ReactorFetcher.DistinctLimitOffset)fetcher;
        }
```

**Comment by elucash** [comment]
Thank you for reporting this! I will look into it, unless @asereda-gs you have some time and immediately understand the issue - will appreciate your help

**Comment by asereda-gs** [comment]
I will take a look.

**Comment by Drevsh** [comment]
If you need some further information I'm happy to Help. I tried to figure out what exactly is happening but was not really able to understand how and when the appropriate DistinctLimitOffset interfaces are generated or rather which class is implementing them.

**Comment by Drevsh** [comment]
Is there any update?

**Comment by asereda-gs** [comment]
Hi.

Can you please try the latest `HEAD`? be599d4 should fix it.
