### ISSUE TITLE
Criteria ClassCastException: IterableMatcher$1Local -> PetCriteriaTemplate

### ISSUE THREAD

**Issue by Drevsh** [immutables/immutables#1457]
A ClassCastException is thrown when a criteria is applied to a collection. 

Code:
```
@Criteria
@Criteria.Repository
@Value.Immutable
public interface Person {
    @Criteria.Id
    String id();
    String fullName();
    Optional<String> nickName();
    int age();
    Collection<Pet> pets();
    Optional<Friend> bestFriend();
}


@Criteria
@Value.Immutable
public interface Pet {
    enum PetType {parrot, panda, iguana, gecko}
    PetType type();
    String name();
}


public class Test {

    public static void main(String[] args) {
        InMemoryBackend backend = new InMemoryBackend();
        PersonRepository repository = new PersonRepository(backend);

        List<Pet> pets = List.of(//
                ImmutablePet.builder()
                        .name("Gecko")
                        .type(Pet.PetType.gecko)
                        .build(), //
                ImmutablePet.builder()
                        .name("Panda")
                        .type(Pet.PetType.panda)
                        .build());
        ImmutablePerson person = ImmutablePerson.builder()
                .id("1")
                .fullName("John")
                .age(23)
                .pets(pets)
                .build();
        repository.insert(person);

        // Exception is thrown here
        // Exception in thread "main" java.lang.ClassCastException: class org.immutables.criteria.matcher.IterableMatcher$1Local cannot be cast to class de.stahlmann.immutables.model.PetCriteriaTemplate
        PersonCriteria criteria = PersonCriteria.person.pets.any().name.contains("Panda");

        Person person1 = repository.find(criteria)
                .one();

        System.out.println(person1);
    }
}
```

I tried to reproduce the example given in: https://immutables.github.io/criteria.html#more-complex-logical-expressions
The exception is thrown when the `Criteria` is created.  

When a `Set` or `List` are used a different exception is thrown:
```
Exception in thread "main" java.lang.IllegalArgumentException: object is not an instance of declaring class
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.immutables.criteria.reflect.Reflections$MethodExtractor.apply(Reflections.java:77)
	at org.immutables.criteria.reflect.Reflections$ReflectionExtractor.extract(Reflections.java:52)
	at org.immutables.criteria.inmemory.ReflectionExtractor$NullSafe.extract(ReflectionExtractor.java:61)
	at org.immutables.criteria.inmemory.ReflectionExtractor$UnwrapOptional.extract(ReflectionExtractor.java:76)
	at org.immutables.criteria.inmemory.ReflectionExtractor.extract(ReflectionExtractor.java:43)
	at org.immutables.criteria.inmemory.ExpressionInterpreter$LocalVisitor.visit(ExpressionInterpreter.java:267)
	at org.immutables.criteria.expression.Expressions$1.visit(Expressions.java:88)
	at org.immutables.criteria.expression.Expressions$1.visit(Expressions.java:75)
	at org.immutables.criteria.expression.Path.accept(Path.java:137)
	at org.immutables.criteria.expression.Expression.accept(Expression.java:35)
	at org.immutables.criteria.inmemory.ExpressionInterpreter$LocalVisitor.visit(ExpressionInterpreter.java:164)
	at org.immutables.criteria.expression.Expressions$1.visit(Expressions.java:78)
	at org.immutables.criteria.expression.Expressions$1.visit(Expressions.java:75)
	at org.immutables.criteria.expression.Call.accept(Call.java:58)
	at org.immutables.criteria.expression.Expression.accept(Expression.java:35)
	at org.immutables.criteria.inmemory.ExpressionInterpreter$LocalVisitor.visit(ExpressionInterpreter.java:169)
	at org.immutables.criteria.expression.Expressions$1.visit(Expressions.java:78)
	at org.immutables.criteria.expression.Expressions$1.visit(Expressions.java:75)
	at org.immutables.criteria.expression.Call.accept(Call.java:58)
	at org.immutables.criteria.expression.Expression.accept(Expression.java:35)
	at org.immutables.criteria.inmemory.ExpressionInterpreter.apply(ExpressionInterpreter.java:76)
	at org.immutables.criteria.inmemory.ExpressionInterpreter.lambda$asPredicate$0(ExpressionInterpreter.java:71)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178)
	at java.base/java.util.concurrent.ConcurrentHashMap$ValueSpliterator.tryAdvance(ConcurrentHashMap.java:3620)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at org.immutables.criteria.inmemory.InMemoryBackend$Session.query(InMemoryBackend.java:171)
	at org.immutables.criteria.inmemory.InMemoryBackend$Session.executeInternal(InMemoryBackend.java:99)
	at org.immutables.criteria.inmemory.InMemoryBackend$Session.execute(InMemoryBackend.java:94)
	at org.immutables.criteria.repository.reactive.ReactiveFetcherDelegate.validateAsList(ReactiveFetcherDelegate.java:92)
	at org.immutables.criteria.repository.reactive.ReactiveFetcherDelegate.one(ReactiveFetcherDelegate.java:70)
	at org.immutables.criteria.repository.sync.SyncFetcherDelegate.one(SyncFetcherDelegate.java:50)
	at org.immutables.criteria.repository.sync.SyncReader.one(SyncReader.java:97)
	at de.stahlmann.immutables.Test.main(Test.java:41)
```

An demo can be found here: https://github.com/Drevsh/immutables-iterable-classcast

**Comment by asereda-gs** [comment]
Thanks for reporting this.

We do need to have a better support for sub-collections.

I believe even without `ClassCastException`  none of the backends support `ANY` / `NONE` / `ALL` operator(s).
