### ISSUE TITLE
Better Support for Jackson's @JsonSubTypes

### ISSUE THREAD

**Issue by harmenweber** [immutables/immutables#1514]
In our project, we have been using Immutables Criteria with a MongoDB backend for some time now. Recently, we tried to use Immutables Criteria for a model that uses Jackson's `@JsonSubTypes` for inheritance. We found that this use case is not fully supported yet.

We were able to make it work, but not without patching some of the Immutables Criteria code. And the patches we had to make are not ideal.

With this issue, I hope to

* either point the way to better support for models that use Jackson's `@JsonSubTypes',
* or learn how to store and retrieve polymorphic models in a better supported way, but still using Jackson.

To demonstrate the problems we face, I created the following commit https://github.com/immutables/immutables/commit/4cdc52ca9190483612b994181850576de3dd6c71.
I added a simple polymorphic model and a test that tries to insert and fetch this model into a MongoDB.

Here is the model:

```java
@JsonTypeInfo(
    use = JsonTypeInfo.Id.NAME,
    include = JsonTypeInfo.As.PROPERTY,
    property = "@type")
@JsonSubTypes({
    @JsonSubTypes.Type(
        value = ImmutableErrorEvent.class,
        name = "org.immutables.criteria.jsonsubtypesmodel.ImmutableErrorEvent")
})
public interface Event<DATA> {
  @Criteria.Id
  UUID id();
  Instant instant();
  DATA data();
}

@Value.Immutable
@JsonSerialize(as = ImmutableErrorEvent.class)
@JsonDeserialize(as = ImmutableErrorEvent.class)
public interface ErrorEvent extends Event<Error> {
  @Override
  Error data();
}

@Value.Immutable
@JsonSerialize(as = ImmutableError.class)
@JsonDeserialize(as = ImmutableError.class)
public interface Error {
  String message();
  List<String> stacktrace();
}
```

And here is the test:

```java
@ExtendWith(MongoExtension.class)
public class MongoEventTest {
  …

  @Test
  void insertAndFindOne() {
    ErrorEvent errorEvent = ImmutableErrorEvent.builder()
        .id(UUID.randomUUID())
        .instant(Instant.now().truncatedTo(ChronoUnit.MILLIS))
        .data(toError(getRandomException()))
        .build();
    
    this.syncWritable.insert(errorEvent);
    Event<?> loadedEvent = this.syncReadable.find(EventCriteria.event.id.is(errorEvent.id())).one();
    
    assertEquals(errorEvent, loadedEvent);
  }

  …
}
```

The test succeeds against an in-memory database. However, it fails when run against a real MongoDB instance with the following error message:

```
Caused by: java.lang.ClassCastException: class com.fasterxml.jackson.core.util.JsonParserSequence cannot be cast to class org.immutables.criteria.mongo.bson4jackson.Wrapper (com.fasterxml.jackson.core.util.JsonParserSequence and org.immutables.criteria.mongo.bson4jackson.Wrapper are in unnamed module of loader 'app')
	at org.immutables.criteria.mongo.bson4jackson.JacksonCodecs$1.deserialize(JacksonCodecs.java:101)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:310)
```

To run the test against a real local MongoDB instance, set the system property `-Dmongo=mongodb://localhost` as described in the `MongoExtension`.

The exception that occurs is due to the false assumption in the `JacksonCodecs` that the `JsonParser` can be cast into a `Wrapper<BsonReader>`. This assumption is false as soon as `@JsonSubTypes` is used, because Jackson wraps the `BsonParser` with a `JsonParserSequence`. As a result, the `JsonParser` can no longer be cast into a `Wrapper<BsonReader>`.

**Comment by elucash** [comment]
Thank you for reporting this! I cannot promise to look into this soon. I would encourage to create a PR as it seems like the cause of the issue and the fix is known

**Comment by harmenweber** [comment]
Hi

For some time we could avoid the problem mentioned above.  However, this week it popped up again.

My team spent some time trying to figure out a way to resolve the problem. Unfortunately, without success.

The problem remains in the `org.immutables.criteria.mongo.bson4jackson.JacksonCodecs`. Specifically in these lines of code:

```java
  private static <T> JsonDeserializer<T> deserializer(final Codec<T> codec) {
    Objects.requireNonNull(codec, "codec");
    return new JsonDeserializer<T>() {
      @Override
      public T deserialize(JsonParser parser, DeserializationContext ctxt) {
        @SuppressWarnings("unchecked")
        final BsonReader reader = ((Wrapper<BsonReader>) parser).unwrap();
        return codec.decode(reader, DecoderContext.builder().build());
      }
    };
  }
```

The code falsly assumes that the `parser` passed by Jackson can always be cast into a `Wrapper<BsonReader>`. However, this is not always the case.  And seemingly, working with Jackson's `@JsonSubTypes` leads Jackson to pass a `JsonParserSequence` that cannot be cast into a `Wrapper<BsonReader>`.

The `JsonParserSequence` internally contains an array of parsers. One those is an instance of `Wrapper<BsonReader>`. So, we even tried a dirty hack in which we pulled that `Wrapper<BsonReader>` out of the `JsonParserSequence`. Apart from the fact that this would be a horrible workaround, it also didn't help but only led to other problems. Seemingly, the two parsers inside the `JsonParserSequence` are not in sync. While Jackson is currently about to read some token X, the `Wrapper<BsonReader>` inside the `JsonParserSequence` might point to another Token Y.

The proper solution would be to replace that cast to `Wrapper<BsonReader>`. However, so far we fail to see the solution.

We would appreciate it, if someone could take a look into it.
