### ISSUE TITLE
Missing annotation for a superclass causes immutables to fail unexpectedly

### ISSUE THREAD

**Issue by mmorrisontx** [immutables/immutables#1529]
If a class in the current project extends a superclass from a library, and that superclass is annotated with an annotation which is missing from the classpath, the immutables annotation processor fails compilation for the entire project, even if immutables was not used on any of the classes involved.

**Comment by mnisius** [comment]
Same problem here

**Comment by lukaseder** [comment]
For the record, this was discussed also here:

- https://github.com/jOOQ/jOOQ/issues/17912

And I've found that it's possible to reproduce such errors without immutables in the loop:

- https://github.com/jOOQ/jOOQ/issues/17912#issuecomment-2607426782

This uses jOOR (from jOOQ) to compile example code in memory. `UDTImpl` is annotated with `org.jetbrains.annotations.ApiStatus.Internal`, which is an optional transitive dependency of jOOQ, not available to this test:

```java
    @Test
    public void testProcessor() throws Exception {
        Compile.compile("com.example.Test", """
            package com.example;
            
            class Test extends org.jooq.impl.UDTImpl {
                Test() {
                    super((org.jooq.Name) null, null, null, false);
                }
            }
            """,
            new CompileOptions()
                .options("-proc:only")
                .processors(new AProcessor())
        );
    }

    static class AProcessor implements Processor {
        @Override
        public Set<String> getSupportedOptions() {
            return Collections.emptySet();
        }

        @Override
        public Set<String> getSupportedAnnotationTypes() {
            return Collections.singleton("*");
        }

        @Override
        public SourceVersion getSupportedSourceVersion() {
            return SourceVersion.RELEASE_8;
        }

        @Override
        public void init(ProcessingEnvironment processingEnv) {
        }

        @Override
        public boolean process(Set<? extends TypeElement> annotations, RoundEnvironment roundEnv) {
            return false;
        }

        @Override
        public Iterable<? extends Completion> getCompletions(Element element, AnnotationMirror annotation, ExecutableElement member, String userText) {
            return Collections.emptyList();
        }
    }
```

This produces the following compilation error:

```
Kein Zugriff auf org.jetbrains.annotations.ApiStatus
  Klassendatei für org.jetbrains.annotations.ApiStatus nicht gefunden


org.jooq.tools.reflect.ReflectException: Compilation error: 

	at org.jooq.mcve.test.java.oracle.Compile.compile(Compile.java:119)
	at org.jooq.mcve.test.java.oracle.Compile.compile(Compile.java:54)
	at org.jooq.mcve.test.java.oracle.JavaTest.testProcessor(JavaTest.java:53)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:232)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:55)
```
