### ISSUE TITLE
MultiMap does not work with Gson Adapters when Key is non primitive

### ISSUE THREAD

**Issue by digitalbuddha** [immutables/immutables#356]
Created a project (which is actually going to be a demo for a Meetup talk) demonstrating how to use Immutables.

I have a few data models `School` `Student` & `Classroom`:
```
@Value.Immutable
public abstract class School {

    public abstract String schoolName();

    public abstract Multimap<Classroom, Student> classroomsAndStudents();

    public abstract List<Classroom> classrooms();

    @Value.Default
    public String mascotName() {
        return "No Mascot";
    }
}

@Value.Immutable
public interface Classroom {
    Long id();
    String location();
    int capacity();
}

@Value.Immutable
public interface Student {
    String name();
}
```

When I run the following code I get an error:
```
 Student bob = ImmutableStudent.builder()
                .name("bob").build();
        Student heather = ImmutableStudent.builder()
                .name("heather").build();
        Classroom classroom = ImmutableClassroom.builder()
                .id(2l).capacity(25).location("1st Floor").build();


        School school = ImmutableSchool.builder().schoolName("Cass High")
                .putClassroomsAndStudents(classroom, heather, bob)
                .addClassrooms(classroom)
                .build();

        String literal = gson.toJson(school);
```

Stacktrace:
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{friendlyrobot.nyc.friendlyimmutables/friendlyrobot.nyc.friendlyimmutables.MainActivity}: java.lang.UnsupportedOperationException: JsonObject
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2625)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2686)
                                                       at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1440)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:154)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5969)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:801)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:691)
                                                    Caused by: java.lang.UnsupportedOperationException: JsonObject
                                                       at com.google.gson.JsonElement.getAsString(JsonElement.java:191)
                                                       at friendlyrobot.nyc.friendlyimmutables.vo.GsonAdaptersVo$SchoolTypeAdapter.writeSchool(GsonAdaptersVo.java:257)
                                                       at friendlyrobot.nyc.friendlyimmutables.vo.GsonAdaptersVo$SchoolTypeAdapter.write(GsonAdaptersVo.java:235)
                                                       at friendlyrobot.nyc.friendlyimmutables.vo.GsonAdaptersVo$SchoolTypeAdapter.write(GsonAdaptersVo.java:210)
                                                       at com.google.gson.Gson.toJson(Gson.java:661)
                                                       at com.google.gson.Gson.toJson(Gson.java:640)
                                                       at com.google.gson.Gson.toJson(Gson.java:595)
                                                       at com.google.gson.Gson.toJson(Gson.java:575)
                                                       at friendlyrobot.nyc.friendlyimmutables.MainActivity.start(MainActivity.java:49)
```

The problem seems to be in this generated method
```
  private void writeSchool(JsonWriter out, School instance)
        throws IOException {
      out.beginObject();
      out.name("schoolName");
      out.value(instance.schoolName());
      Multimap<Classroom, Student> classroomsAndStudentsMapping = instance.classroomsAndStudents();
      out.name("classroomsAndStudents");
      out.beginObject();
      for (Map.Entry<Classroom, Collection<Student>> e : classroomsAndStudentsMapping.asMap().entrySet()) {
        String key = classroomsAndStudentsTypeAdapter.toJsonTree(e.getKey()).getAsString();
        out.name(key);
        out.beginArray();
        for (Student value : e.getValue()) {
          classroomsAndStudentsSecondaryTypeAdapter.write(out, value);
        }
        out.endArray();
      }
      out.endObject();
      List<Classroom> classroomsElements = instance.classrooms();
      out.name("classrooms");
      out.beginArray();
      for (Classroom e : classroomsElements) {
        classroomsTypeAdapter.write(out, e);
      }
      out.endArray();
      out.name("mascotName");
      out.value(instance.mascotName());
      out.endObject();
    }
```
particularly this line: 
`        String key = classroomsAndStudentsTypeAdapter.toJsonTree(e.getKey()).getAsString();`
It seems like the generate code is creating a `JsonElement` and then trying to do a `getAsString` on it.  JsonElement has the following impl for `getAsString`

```
  /**
   * convenience method to get this element as a string value.
   *
   * @return get this element as a string value.
   * @throws ClassCastException if the element is of not a {@link JsonPrimitive} and is not a valid
   * string value.
   * @throws IllegalStateException if the element is of the type {@link JsonArray} but contains
   * more than a single element.
   */
  public String getAsString() {
    throw new UnsupportedOperationException(getClass().getSimpleName());
  }
```

**Comment by elucash** [comment]
Maybe it's not totally clear what happens here, but it was designed to work in this way.
`JsonElement.getAsString` is overridden by scalar subclasses (it will also work for arrays of a single element). I would like to improve error reporting here, but it may get tricky.

As you know, JSON cannot have keys other than strings. For example `Multimap<String, Integer>` will be serialized like a struct with array values

```javascript
{ "key": [0, 2, 3],
  "otherkey": [4, 5, 6] }
```
Gson TypeAdapter generation in Immutables was designed for straightforward serialization, but not for freeform mappings with sophisticated on-the-fly transformations. So If I want to serialize multimap with complex object as key,  I have to be honest about actual structure which should directly map to a JSON representation without translations. And this should be expressed in a model. Immutables provide `@Derived` and `@Lazy` attributes to help create alternative views if needed.

Here's and example encoding multimaps:

```java
@Immutable(builder = false) // with builder=false this would map to array or arguments:  [k, [v, v, v]]
interface StudentsOfClassroom {
   @Parameter Classroom classroom();
   @Parameter List<Student> students();
}

@Immutable
public abstract class School {
    public abstract String schoolName();
    public abstract Set<StudentsOfClassroom> classroomsAndStudents();
    public abstract List<Classroom> classrooms();

    @Lazy Multimap<Classroom, Student> studentsByClassroom() {
         ImmutableMultimap.Builder<Classroom, Student> builder = ImmutableMultimap.builder(); 
         for (StudentsOfClassroom e : classroomsAndStudents()) {
             builder.putAll(e.classroom(), e.students());
         }
         return builder.build();
     }

    @Value.Default
    public String mascotName() {
        return "No Mascot";
    }
}
```
In theory it should also work with generic entry, but there may be bugs in Gson support, so I'll try to test and fix it, so would not recommend to use now, but once fleshed out it should work fine also. 

```java
	@Immutable(builder = false)
	interface Multientry<K, V> {
		@Parameter K getKey();
		@Parameter List<V> getValues();
	}
```

Another, simpler option here is to have special `ClassroomId` object that would map to and from string representation, it can then be used as a key in a multimap. Even `Long id();` may be used as a key instead of `Classroom`:  `Multimap<Long, Student>`.

Hope this helps
