### ISSUE TITLE
Optional Collections (reprise)

### ISSUE THREAD

**Issue by Zteve** [immutables/immutables#363]
This is a re-opening of issue [181][1].

We would like the option of writing, for example, `Optional<Map<String,Object>>` and still be able to use the singular (additive) attribute settings.

This has become a serious concern for us as we move away from `null` values altogether (in line with the Immutables philosophy).  There are many collection fields in our classes and we construct many of them in tests. Previously we were expecting `null` when not added to (thanks to previous changes to support `@Nullable`, thank you) but we are now moving to a no-NPE environment, and this feature is precisely what we need to fill the remaining gaps.

There were objections on the grounds that it is hard to explain. Admittedly it may be slightly more complex, but no more complex than the `@Nullable` option on collections:  the attribute is `Optional.empty()` if never set; if it is added to and is `empty`, then it becomes non-empty.  This is just the same explanation as a `@Nullable` attribute, but with the word `null` replaced by `empty`.

The only issue to keep straight is that an empty `Optional` is **_not_** the same as an empty `Collection`.

[1]: https://github.com/immutables/immutables/issues/181

**Comment by elucash** [comment]
Thank you @Zteve for the feature request! Let me think about it. I would agree that it's seems to be easy to add just this case, but we have to analyze of impact of this (surprisingly, the support for nullable/default-able/collection had quite a large impact on a lot of cases and the codebase in general). One of the interesting solution for this and many, many other cases would be implementation of special extensibility for properties/builders which can be expressed in java (rather than codegen templates or annotation processor/plugins).

**Comment by Zteve** [comment]
I wonder if this issue is anywhere near being resolved?  If it is positive, it might have a profound affect on the signatures in our API, so we are interested in an early resolution.

**Comment by elucash** [comment]
@Zteve if fact we are working on this, probably, half way through. ETA for early solution would be early next week. We are trying to cover any desired combination of container types and it seems it's quite feasible and powerful.

**Comment by Zteve** [comment]
@elucash That's great news. Thank you.  I look forward to trying this out.

**Comment by elucash** [comment]
(just as an update: having a good progress on this, but having to do a bunch of other things, ETA is moving for about a week from now)
For this we are developing new "encoding" functionality. This functionality will enable custom types integration. And custom types can be a combination of other types, just like `Optional<List<T>>` etc. Certain encodings, maybe these optional collections included, will be added as a samples/available out of the box (most probably via separate module). How would it look like? Details are not fully settled out yet but it will look something like this: https://github.com/immutables/immutables/blob/master/encode/test/org/immutables/encode/fixture/TableEncoding.java

**Comment by nebhale** [comment]
Sounds like a great plan.  Looking forward to seeing it in action.

**Comment by elucash** [comment]
It was pretty hard to find time to get back to this, but now I'm quite excited to tell that we got quite a good skeleton walking with this functionality.
Caveats are that it is not released yet (so snapshots/build from source) and there's no documentation yet, even javadocs not yet written. But at the same time there's enough to start playing with and evaluate if there's any good use of it.
I expect to write javadocs + more examples soon, as well as some more elaborate documentation article on this. But in nutshell:

0) Need to have separate compilation module (like maven jar module whatever)
   it uses annotation from `org.immutables:encode` and processor `org.immutables.value` as usual

1) Create there a class to describe "encoding" for attributes of a certain type. like `MyEncoding` and annotate with annotations in `org.immutables.encode.Encoding.*` It will generate `MyEncodingEnabled` annotation which will carry the essence of the encoding compiled in.

2) Once compiled, you can import that encoding module in a compilation class-path (no runtime classpath needed) and put `@MyEncodingEnabled` on a type, package or style meta-annotation to enable the encoding. Once enabled, an encoding will intercept any immutable attributes it matches and customized code will be generated in Immutable implementation class.

As we discussed optional collections here, I've, of course, tried to create OptionalMap, and here's of example of how it could be "encoded":

https://github.com/immutables/immutables/blob/master/encode/test/org/immutables/encode/fixture/OptionalMap.java
https://github.com/immutables/immutables/blob/master/value-fixture/src/org/immutables/fixture/encoding/UseOptionalMap.java
https://github.com/immutables/immutables/blob/master/value-fixture/test/org/immutables/fixture/encoding/EncodingTest.java

**Comment by nebhale** [comment]
I'm giving this a try this afternoon and running into the following stack trace when compiling:

```
Error:java: org.immutables.value.internal.$processor$.encode.$Processor threw java.lang.RuntimeException: java.lang.ClassNotFoundException: org.immutables.value.internal.$processor$.encode.Generator_$Encodings
  	at org.immutables.value.internal.$guava$.base.$Throwables.propagate($Throwables.java:160)
  	at org.immutables.value.internal.$generator$.$AbstractGenerator.newTemplate($AbstractGenerator.java:62)
  	at org.immutables.value.internal.$processor$.encode.$Processor.process($Processor.java:12)
  	at org.immutables.value.internal.$generator$.$AbstractGenerator.process($AbstractGenerator.java:97)
  	at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:794)
  	at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:705)
  	at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)
  	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1035)
  	at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1176)
  	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
  	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:856)
  	at com.sun.tools.javac.main.Main.compile(Main.java:523)
  	at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:129)
  	at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:138)
  	at org.jetbrains.jps.javac.JavacMain.compile(JavacMain.java:166)
  	at org.jetbrains.jps.incremental.java.JavaBuilder.compileJava(JavaBuilder.java:423)
  	at org.jetbrains.jps.incremental.java.JavaBuilder.compile(JavaBuilder.java:290)
  	at org.jetbrains.jps.incremental.java.JavaBuilder.doBuild(JavaBuilder.java:197)
  	at org.jetbrains.jps.incremental.java.JavaBuilder.build(JavaBuilder.java:168)
  	at org.jetbrains.jps.incremental.IncProjectBuilder.runModuleLevelBuilders(IncProjectBuilder.java:1237)
  	at org.jetbrains.jps.incremental.IncProjectBuilder.runBuildersForChunk(IncProjectBuilder.java:911)
  	at org.jetbrains.jps.incremental.IncProjectBuilder.buildTargetsChunk(IncProjectBuilder.java:983)
  	at org.jetbrains.jps.incremental.IncProjectBuilder.buildChunkIfAffected(IncProjectBuilder.java:870)
  	at org.jetbrains.jps.incremental.IncProjectBuilder.buildChunks(IncProjectBuilder.java:696)
  	at org.jetbrains.jps.incremental.IncProjectBuilder.runBuild(IncProjectBuilder.java:387)
  	at org.jetbrains.jps.incremental.IncProjectBuilder.build(IncProjectBuilder.java:194)
  	at org.jetbrains.jps.cmdline.BuildRunner.runBuild(BuildRunner.java:138)
  	at org.jetbrains.jps.cmdline.BuildSession.runBuild(BuildSession.java:294)
  	at org.jetbrains.jps.cmdline.BuildSession.run(BuildSession.java:125)
  	at org.jetbrains.jps.cmdline.BuildMain$MyMessageHandler$1.run(BuildMain.java:232)
  	at org.jetbrains.jps.service.impl.SharedThreadPoolImpl$1.run(SharedThreadPoolImpl.java:44)
  	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
  	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  	at java.lang.Thread.run(Thread.java:745)
  Caused by: java.lang.ClassNotFoundException: org.immutables.value.internal.$processor$.encode.Generator_$Encodings
  	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
  	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
  	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
  	at org.immutables.value.internal.$generator$.$AbstractGenerator.newTemplate($AbstractGenerator.java:59)
  	... 34 more
```

My classpath indicates that this is in fact there, but I'm the first to note that I have no idea how annotation processor class paths work.

**Comment by elucash** [comment]
My bad, never tried with shaded jar. Fixed in 6ff94e590d4f2577d71f042682acd4409543581c

**Comment by nebhale** [comment]
Waiting for a Travis run and then I'll continue along.

**Comment by nebhale** [comment]
I'm seeing two warnings during compilation of the encoder:

```
Unrecognized Builder member '<init>' will be ignored
Unrecognized encoding member '<init>' will be ignored
```

Is it possible to eliminate those warnings from my code?

**Comment by elucash** [comment]
Those will go away, just haven't filtered synthetic constructors yet.

**Comment by nebhale** [comment]
I've got an encoder that looks like the following:

```java
@Encoding
final class OptionalList<T> {

    @Encoding.Impl
    private final List<T> list = null;

    @Encoding.Expose
    public Optional<List<T>> get() {
        return Optional.ofNullable(this.list);
    }

    @Encoding.Init
    static <T> List<T> init(Optional<? extends List<T>> list) {
        return list
            .map(ArrayList::new)
            .orElse(null);
    }

    @Encoding.Builder
    static final class Builder<T> {

        private List<T> list = null;

        @Encoding.Naming("add*")
        @Encoding.Init
        void add(T element) {
            getOrCreate().add(element);
        }

        @Encoding.Naming("addAll*")
        @Encoding.Init
        void addAll(List<? extends T> elements) {
            getOrCreate().addAll(elements);
        }

        @Encoding.Build
        List<T> build() {
            return this.list;
        }

        @Encoding.Naming("set*")
        @Encoding.Init
        @Encoding.Copy
        void set(Optional<? extends List<? extends T>> elements) {
            this.list = null;

            elements
                .ifPresent(e -> getOrCreate().addAll(e));
        }

        private List<T> getOrCreate() {
            if (this.list == null) {
                this.list = new ArrayList<>();
            }

            return this.list;
        }

    }

}
```

The goal was to add a builder method for `Optional<List<String>> getName()` that was `addName(String)` in addition to the `setNames(List<String>)`.  However, it doesn't seem like this code is being added to the generated type.  I've got the annotation specified, as specified above, so I don't think it's that the encoder is missing...

```java
@OptionalListEnabled
@Value.Style(
    add = "*",
    defaults = @Value.Immutable(copy = false),
    depluralize = true,
    depluralizeDictionary = "status:statuses",
    put = "*",
    typeAbstract = "_*",
    typeImmutable = "*",
    visibility = ImplementationVisibility.PUBLIC
)
```

**Comment by elucash** [comment]
Great! I'm applying the encoding and was able to compile it in, but there are problem with compiling generated type there's some troubles but it'm not figured out what the p.
Where exactly did you put `@OptionalListEnabled`. Try to put it on a type, then on a package, parent-package, then on meta annotation. It's interesting at which point it stops to work )

**Comment by nebhale** [comment]
Works on the type but not the package or parent package.  Didn't try the meta annotation.  Now, the code generated doesn't work, but that's another issue for me to address. 😄

**Comment by elucash** [comment]
There are at least 2 issues (not counting package annotation doesn't work) with the code generation. Static init method doesn't get type parameters interpolated correctly. And then, impl field name is strange. Need some time to debug/fix

**Comment by nebhale** [comment]
Just ran into the implementation field name issue (they're certainly not pretty, but the big issue is that the constructor has different values than the actual field names), so good to know that it's on your radar.

Is there anything I need to do to fit into the de-pluralization scheme? I'm getting an `addNames(String)` method which is an odd hybrid.

**Comment by elucash** [comment]
Currently, depluralization is not implemented yet. I'm thinking of something like 
`@Encoding.Naming(value="add*", depluralize = true)` wdyt?

**Comment by elucash** [comment]
Fixed problem when fields from value and builder overlap, fixed also overlap of field and method namespaces (so now fields can be named as methods and resolved separately), also added support for `this::methodRef`. Annotation on package should work now. Added `depluralize` attribute to naming as shown above.
Thank you for messing with early snapshots, much appreciated! That really helps to focus and resolve issues to get it work.

I refined a bit sample optional list encoding, mainly added `hashCode`, `toString` and `equals` to handle `null` (as automatically added implementation doesn't consider field can be null)

```java
@Encoding
final class OptionalList<T> {

  @Encoding.Impl
  private final List<T> list = null;

  @Encoding.Expose
  public Optional<List<T>> get() {
    return Optional.ofNullable(this.list);
  }

  @Encoding.Init
  static <T> List<T> init(Optional<? extends List<T>> lst) {
    return lst.<List<T>>map(ArrayList<T>::new).orElse(null);
  }

  @Override
  public String toString() {
    return get().toString();
  }

  // just as an example, can be coded more efficiently
  @Override
  public int hashCode() {
    return get().hashCode();
  }

  public boolean equals(OptionalList<T> obj) {
    return Objects.equals(list, obj.list);
  }

  @Encoding.Builder
  static final class Builder<T> {

    private List<T> list = null;

    @Encoding.Naming(value = "add*", depluralize = true)
    @Encoding.Init
    void add(T element) {
      getOrCreate().add(element);
    }

    @Encoding.Naming("addAll*")
    @Encoding.Init
    void addAll(List<? extends T> elements) {
      getOrCreate().addAll(elements);
    }

    @Encoding.Build
    List<T> build() {
      return this.list;
    }

    @Encoding.Init
    @Encoding.Copy
    void set(Optional<? extends List<? extends T>> elements) {
      this.list = null;

      elements.ifPresent(e -> getOrCreate().addAll(e));
    }

    private List<T> getOrCreate() {
      if (this.list == null) {
        this.list = new ArrayList<>();
      }

      return this.list;
    }
  }
}
```

**Comment by nebhale** [comment]
@elucash Just back in this morning and looking over the depluralize suggestion.  Ideally, I'd want the depluralization to "just work" with the same rules as they currently do; in other words, all of my contributed methods are considered and the same ruleset is applied to them as is currently applied to other collections. But that being said, maybe I'm working at such a low-level abstraction with encoders, that I don't realize your equivalent support for collections (which I'm guessing you'd convert to encoders like this eventually?) opts in using some older mechanism.  Assuming that at the low-level all of the "encoding implementations" opt in, this seems like a perfectly reasonable way to do it.

As to the missing methods, I had them in place but stripped them as I was trying to get to the minimum possible example for trouble shooting.  They'll go back in with these latest fixes.  Thanks and I'll work on this some more today to see if I can tease any other issues out.

**Comment by elucash** [comment]
@nebhale you're right that it shoulld not be so involved, and also right about lower-lever of abstraction working with encodings. Encodings allows us to describe methods like addPerson and addAllPeople, in some cases depluralization is needed, in some cases not. I don't see a way to derive this without assistance of annotation attribute, but suggestions are welcome

**Comment by nebhale** [comment]
Depluralization and internal naming improvements look good.

We do a stripped down naming of our builder methods (as mentioned above a `Style` of `add = "*",`).  It's clear to me how I would make that change in the encoder, but I'd have expected the encoder to be overlaid with the style specified else where.  Is that a reasonable (but not yet implemented) assumption, or do you feel that encoders should be written to exactly what I'd like.  My perspective comes again from the idea that all of the current support could be re-written as encoders.

**Comment by elucash** [comment]
> My perspective comes again from the idea that all of the current support could be re-written as encoders.
It would be nice to eventually do this

> We do a stripped down naming of our builder methods (as mentioned above a Style of add = "*",). It's clear to me how I would make that change in the encoder, but I'd have expected the encoder to be overlaid with the style specified else where.

We already do this when it is clear how we should handle this. For example "expose" methods are forced to be named after abstract accessor method, auto-generated "with-copy" or the one with omitted/default naming will follow styles, also "init/copy" in builder without explicit naming will also follow styles for setters in builders. For cases when you want to have arbitrary non-straight-copy initializers like "add*" or "append*" it is clear that we have a hard time auto-aligning them with styles. Even if we match them with default values for styles and swap them to changed in style ones, it, certainly, would be  more of a guessing.

**Comment by nebhale** [comment]
I guess the real question I'm asking is in the encoder land, can any of the `add()` method, an `add*` naming, or some new `@Encoder.Add` annotation cause the `@Style(add = "<VALUE>")` to kick in?

Separately from that question though, I end up the following:

```
@Encoding.Naming(value = "add*", depluralize = true)
@Encoding.Init
void add(T element) {
    getOrCreate().add(element);
}
```

Generates `addName(String)`.  However:

```
@Encoding.Naming(value = "*", depluralize = true)
@Encoding.Init
void add(T element) {
    getOrCreate().add(element);
}
```

Only generates `names(String)`.  It doesn't seem like de-pluralization is acting on that second case.

**Comment by elucash** [comment]
> @Encoding.Naming(value = "*", depluralize = true)

this is a bug, when I check that value is default "*", I do not check for depluralize flag. so it can be fixed. 

> I guess the real question I'm asking is in the encoder land, can any of the add() method, an add* naming, or some new @Encoder.Add annotation cause the @Style(add = "<VALUE>") to kick in?

This is actually a good idea! I'm thinking of creating an enum of styles/namings so you can specify
`@Encoding.Naming(style = NamingStyle.ADD)`. If there's constant for what you want you just stick to default style, otherwise specify a custom pattern.

**Comment by nebhale** [comment]
The naming style enumeration would fit our needs perfectly.  And, for us at least, it avoids the bug in the first part 😄.

**Comment by nebhale** [comment]
@elucash If it's at all helpful for you, I've been attempting to flesh out an [`Encoder` that reproduces both the collections builder and the optional builder](https://github.com/cloudfoundry/cf-java-client/blob/immutables-encoding/immutables-encodings/src/main/java/org/cloudfoundry/immutables/OptionalList.java) combined.  I've included `TODO`s where I've experienced problems that prevent me from replicating this.  I don't actually need all of this support to proceed, but I figured that it provided some pointers about what would be required to get to parity.

**Comment by elucash** [comment]
Standard naming enum is implemented. Released as "preview" in 2.2.11. When there will be enough documentation and some experience using it including fixes, we might refine it and re-release as 2.3

Some notes:

> // TODO: @Encoding.Init duplicate method 'initFromVarargs'. Cannot have more than one init method

to create multiple `with` or `set` overloads, just define them

```java
@Encoding.Copy
List<T> withIterable(Iterable<T> elements) {
   return ...
}
@Encoding.Copy
List<T> withVarargs(T... elements) {
   return ...
}
...
class Builder {
  @Encoding.Init
  void setIterable(Iterable<T> elements) {
     ...
  }
  @Encoding.Init
  void setVarargs(T... elements) {
     ...
  }
}
```

>  Objects.requireNonNull(optional, "optional");  // TODO: Adding this line causes methods to be created twice in generated code

Will see if it's correct behavior or accidental duplicate: one liners are usually inlined, adding a line forces method to be created. Anyway, you can use one-liner:

```java
return Objects.requireNonNull(optional, "optional")
            .map(elements -> createSafeList(elements))  // TODO: Method reference name mangling doesn't happen in generated code
            .orElse(null);
```

>  // TODO: Method reference name mangling doesn't happen in generated code

Only `this::ref` supported as of now, so yeah, this is a limitation

> // TODO: Adding this method results in a silent generation failure; the class just doesn't get created

Found a bug in handling varargs, thanks!

> `private static <T> List<T> createSafeList(Iterable<T> iterable) {`

this one is not translated correctly currently for me, looking into

**Comment by elucash** [comment]
Fixed many stuff mentioned above.
Notes:
* Among method references only `this::ref` supported as of now, other are not interpolated.
* Type parameters of the helper methods which shadow type parameters of encoding are being translated in a special way.

**Comment by nebhale** [comment]
Great, I'll take a look.

**Comment by vorburger** [comment]
If I understand this issue correctly, it would make it possible for others to contribute plug-in/add-on solutions for the [kind of issues currently tagged as encodings_should_solve](https://github.com/immutables/immutables/labels/encodings_should_solve)?  Perhaps you'd like to tag this issue itself with "encodings_should_solve", so it can be found/seen from that filter? (I have just glanced over the Immutables.org issue list, and peaked at those issues, but not seen this one until you mentioned it in #471.)

**Comment by elucash** [comment]
tagged, thanks for the hint!

**Comment by elucash** [comment]
JFYI the guide/tutorial is in progress, early access: http://immutables.github.io/encoding.html
