### ISSUE TITLE
Jackson 2.8.3 breaks immutable deserialization.

### ISSUE THREAD

**Issue by ericsantosnascimento** [immutables/immutables#491]
Hi Guys, i just got an issue here using immutables 2.1.14(also 2.3.4) + jackson 2.8.3 when i try to deserialize and immutable class I get the following error

```
Class com.fasterxml.jackson.databind.deser.impl.MethodProperty can not access a member of class com.ifood.merchant.model.ImmutableStore$Json with modifiers "public"
 at [Source: java.io.BufferedReader@2f7c2f4f; line: 1, column: 47] (through reference chain: com.ifood.merchant.model.Json["description"]) reading GET http://localhost:10282/merchant/stores/7400b21f-d337-49da-88d6-3f4373ae97ac
	at feign.FeignException.errorReading(FeignException.java:49)
	at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:140)
	at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:76)
	at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:103)
	at com.sun.proxy.$Proxy5.getStoreById(Unknown Source)
	at com.ifood.merchant.Main.main(Main.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Class com.fasterxml.jackson.databind.deser.impl.MethodProperty can not access a member of class com.ifood.merchant.model.ImmutableStore$Json with modifiers "public"
 at [Source: java.io.BufferedReader@2f7c2f4f; line: 1, column: 47] (through reference chain: com.ifood.merchant.model.Json["description"])
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:268)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty._throwAsIOE(SettableBeanProperty.java:546)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty._throwAsIOE(SettableBeanProperty.java:527)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:105)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:276)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:178)
	at com.fasterxml.jackson.module.afterburner.deser.SuperSonicBeanDeserializer.deserialize(SuperSonicBeanDeserializer.java:121)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1192)
	at com.fasterxml.jackson.module.afterburner.deser.SuperSonicBeanDeserializer.deserializeFromObject(SuperSonicBeanDeserializer.java:236)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:148)
	at com.fasterxml.jackson.module.afterburner.deser.SuperSonicBeanDeserializer.deserialize(SuperSonicBeanDeserializer.java:117)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3789)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2892)
	at feign.jackson.JacksonDecoder.decode(JacksonDecoder.java:65)
	at feign.SynchronousMethodHandler.decode(SynchronousMethodHandler.java:161)
	at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:129)
	... 9 more
Caused by: java.lang.IllegalAccessException: Class com.fasterxml.jackson.databind.deser.impl.MethodProperty can not access a member of class com.ifood.merchant.model.ImmutableStore$Json with modifiers "public"
	at sun.reflect.Reflection.ensureMemberAccess(Reflection.java:102)
	at java.lang.reflect.AccessibleObject.slowCheckMemberAccess(AccessibleObject.java:296)
	at java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:288)
	at java.lang.reflect.Method.invoke(Method.java:491)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:103)
	... 21 more
```

I know, maybe is more a jackson problema than an immutables problem but I would like to share with you and see if you are aware of this and how are you guys working around this.

**Comment by elucash** [comment]
Thank you for reporting this. I'll try to reproduce it. Is there any Jackson bug filed similar to this?

**Comment by ericsantosnascimento** [comment]
I found some bugs similar but using very old jackson versions eg: 2.4.5, in my case to continue my work I had to downgrade my jackson version from 2.8.3 to 2.7.3.

**Comment by ericsantosnascimento** [comment]
Hey Guys any news ?

**Comment by elucash** [comment]
Our tests were upgraded to use Jackson 2.8.5 for Immutables 2.4.x and there were no issues like this. Can you provide repro case, please?

**Comment by ericsantosnascimento** [comment]
Hi, for sure? what could be useful for you? the immutable class?

**Comment by elucash** [comment]
I dunno, just java file + pom. So I can `mvn test` and instantly see the error. Need to have pom so can reliably get deps.

**Comment by ericsantosnascimento** [comment]
`
@Value.Immutable
@JsonSerialize(as = ImmutableJacksonTest.class)
@JsonDeserialize(as = ImmutableJacksonTest.class)
public interface JacksonTest {


    String name();

    Optional<String> corporateName();

    Optional<String> description();

    Optional<String> shortDescription();

    Optional<String> slogan();

    BigDecimal averageTicket();

    @Value.Default
    default Boolean closed() {
        return Boolean.FALSE;
    }

    @Value.Default
    default Boolean enabled() {
        return Boolean.TRUE;
    }
}
`

`/**
 *
 * Created by eric-nascimento on 27/10/16.
 */
@RunWith(MockitoJUnitRunner.class)
public class JacksonTest {

    @Test
    public void convert() throws Exception {

        ObjectMapper objectMapper = new ObjectMapper();

        ImmutableJacksonTest immutableJacksonTest =
            ImmutableJacksonTest.builder().name("Eric").description("Teste").averageTicket(BigDecimal.ONE).build();

        String json = objectMapper.writeValueAsString(immutableJacksonTest);
        ImmutableJacksonTest immutableJacksonTest1 = objectMapper.readValue(json, ImmutableJacksonTest.class);
        System.out.println(immutableJacksonTest1);
    }

}
`

`<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>teste</groupId>
    <artifactId>test-service-merchant</artifactId>
    <packaging>pom</packaging>
    <version>1.0.8-SNAPSHOT</version>
   
      <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <java.version>1.8</java.version>

        <slf4j.version>1.7.18</slf4j.version>
        <log4j.version>2.4.1</log4j.version>
        <jackson.version>2.8.6</jackson.version>
        <disruptor.version>3.3.2</disruptor.version>
        <raven.version>7.2.3</raven.version>
        <joda-money.version>0.10.0</joda-money.version>
        <ifood-commons.version>1.5</ifood-commons.version>
        <jolokia.version>1.3.3</jolokia.version>
        <immutables.version>2.4.0</immutables.version>
        <junit.version>2.1.14</junit.version>
    </properties>

    <dependencies>

        <dependency>
            <groupId>org.immutables</groupId>
            <artifactId>value</artifactId>
            <version>${immutables.version}</version>
            <scope>provided</scope>
        </dependency>

        
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-annotations</artifactId>
            <version>${jackson.version}</version>
        </dependency>

        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>${jackson.version}</version>
        </dependency>

        <dependency>
            <groupId>com.fasterxml.jackson.datatype</groupId>
            <artifactId>jackson-datatype-jdk8</artifactId>
            <version>${jackson.version}</version>
        </dependency>

        
    </dependencies>

</project>
`

**Comment by elucash** [comment]
I was able to compile the example. I guess, there's just a dependency mess, some of your dependencies might drag inappropriate versions of Jackson, for example. Attaching compilable and testable project.

[jax.zip](https://github.com/immutables/immutables/files/727778/jax.zip)

```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running TheTest
Thes{name=Eric, description=Teste, averageTicket=1, closed=false, enabled=true}
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.265 sec

Results :

Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
```

**Comment by ericsantosnascimento** [comment]
Ok guys, sorry about that, I'll take a look on my dependencies again.

**Comment by io7m** [comment]
Take a look at the output of `mvn dependency:tree`, it'll quickly show any conflicts that are occurring.

**Comment by kyegupov** [comment]
I have ran into the same problem (Value 2.5.6, Jackson 2.8.6). The error is legit, as far as I can tell: Jackson cannot use setters on the `...$Json` class, because it's not public. The question is, why is it even trying to do so?

**Comment by kyegupov** [comment]
Pinned it: it was `jackson-module-afterburner` 2.6.x pulled in by some other dependency. Forcing it to be 2.8.6 solved the problem. Hope this helps someone.

**Comment by mrybak** [comment]
Thanks @kyegupov! Ran into a similar issue with Value 2.5.6 and Jackson 2.9.2, your solution worked.
