### ISSUE TITLE
Kotlin Fun (or not fun with the new Kapt)

### ISSUE THREAD

**Issue by digitalbuddha** [immutables/immutables#497]
Top of the evening!
I'm started to use Kotlin rather than java and Immutables seem to work very well with the last Kotlin Annotation Processor but not the new one.

When using `apply plugin: 'kotlin-kapt'

I get the following exception, I know Kotlin isn't officially supported but was hoping this is something that is an easy fix:

```
org.immutables.value.internal.$processor$.$Processor threw org.immutables.value.internal.$guava$.collect.$Ordering$IncomparableValueException: Cannot compare value: ScheduledTime
        at org.immutables.value.internal.$guava$.collect.$ExplicitOrdering.rank($ExplicitOrdering.java:47)
        at org.immutables.value.internal.$guava$.collect.$ExplicitOrdering.compare($ExplicitOrdering.java:41)
        at java.util.TimSort.countRunAndMakeAscending(TimSort.java:360)
        at java.util.TimSort.sort(TimSort.java:220)
        at java.util.Arrays.sort(Arrays.java:1438)
        at org.immutables.value.internal.$guava$.collect.$Ordering.immutableSortedCopy($Ordering.java:888)
        at org.immutables.value.internal.$generator$.$SourceOrdering.getEnclosedElements($SourceOrdering.java:88)
        at org.immutables.value.internal.$generator$.$SourceOrdering$1CollectedOrdering.collectEnclosing($SourceOrdering.java:226)
        at org.immutables.value.internal.$generator$.$SourceOrdering$1CollectedOrdering.traverse($SourceOrdering.java:209)
        at org.immutables.value.internal.$generator$.$SourceOrdering$1CollectedOrdering.<init>($SourceOrdering.java:195)
        at org.immutables.value.internal.$generator$.$SourceOrdering.getAllAccessorsProvider($SourceOrdering.java:266)
        at org.immutables.value.internal.$processor$.meta.$AccessorAttributesCollector.collectGeneratedCandidateMethods($AccessorAttributesCollector.java:114)
        at org.immutables.value.internal.$processor$.meta.$AccessorAttributesCollector.collect($AccessorAttributesCollector.java:79)
        at org.immutables.value.internal.$processor$.meta.$ValueTypeComposer.compose($ValueTypeComposer.java:64)
        at org.immutables.value.internal.$processor$.meta.$Round.collectValues($Round.java:114)
        at org.immutables.value.internal.$processor$.$Processor.process($Processor.java:47)
        at org.immutables.value.internal.$generator$.$AbstractGenerator.process($AbstractGenerator.java:89)
        at org.jetbrains.kotlin.annotation.AbstractAnnotationProcessingExtension.doRound(AnnotationProcessingExtension.kt:346)
        at org.jetbrains.kotlin.annotation.AbstractAnnotationProcessingExtension.process(AnnotationProcessingExtension.kt:283)
        at org.jetbrains.kotlin.annotation.AbstractAnnotationProcessingExtension.doAnnotationProcessing(AnnotationProcessingExtension.kt:269)
        at org.jetbrains.kotlin.annotation.AbstractAnnotationProcessingExtension.analysisCompleted(AnnotationProcessingExtension.kt:140)
        at org.jetbrains.kotlin.resolve.jvm.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration(TopDownAnalyzerFacadeForJVM.kt:119)
        at org.jetbrains.kotlin.resolve.jvm.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegrationWithCustomContext(TopDownAnalyzerFacadeForJVM.kt:66)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.analyze(KotlinToJVMBytecodeCompiler.kt:365)
        at org.jetbrains.kotlin.cli.common.messages.AnalyzerWithCompilerReport.analyzeAndReport(AnalyzerWithCompilerReport.kt:126)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.analyze(KotlinToJVMBytecodeCompiler.kt:358)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules(KotlinToJVMBytecodeCompiler.kt:131)
        at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:183)
        at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:52)
        at org.jetbrains.kotlin.cli.common.CLICompiler.exec(CLICompiler.java:198)
        at org.jetbrains.kotlin.gradle.tasks.KotlinCompile.compileNotIncremental(Tasks.kt:261)
        at org.jetbrains.kotlin.gradle.tasks.KotlinCompile.callCompiler$kotlin_gradle_plugin(Tasks.kt:178)
        at org.jetbrains.kotlin.gradle.tasks.KotlinCompile.callCompiler$kotlin_gradle_plugin(Tasks.kt:105)
        at org.jetbrains.kotlin.gradle.tasks.AbstractKotlinCompile.execute(Tasks.kt:97)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$IncrementalTaskAction.doExecute(DefaultTaskClassInfoStore.java:155)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:126)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:115)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:74)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:55)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745) 
```

**Comment by elucash** [comment]
Sorry, I have no idea what `ScheduledTime` is and how it gets into the collection of class `Element`s  ¯\_(ツ)_/¯. If you need some stability, you may try to run vanilla java compiler/annotation processor before compiling code, like described here: https://groups.google.com/d/msg/immutables/LQonwnhXSOo/IEC2G3dbBwAJ (it's for Maven, but I guess Gradle should allow something similar)

**Comment by digitalbuddha** [comment]
ScheduledTime is an immutable value object in our codebase
```
@Value.Immutable
public abstract class ScheduledTime {
    public abstract int getStartHour();
    public abstract int getStartMinute();
    public abstract int getEndHour();
    public abstract int getEndMinute();

    public static ScheduledTime of(int... times) {
        return ImmutableScheduledTime
                .builder()
                .startHour(times[0])
                .startMinute(times[1])
                .endHour(times[2])
                .endMinute(times[3])
                .build();
    }
}
```

I guess what I'm saying is that Kapt previous worked and Kapt current does not. I'll file an issue with Jetbrains but I thought I'd bring it up here in case that stacktrace made sense to you.  Enjoy your day!

**Comment by elucash** [comment]
It will be funny if they'll like along the lines of "we don't care about what specific processor is doing, some other processors works well". Hell, just can't imagine debugging another buggy compiler (to the mix of Javac and ECJ). But I would definitely suggest to not use kapt with java code. One of the "advantage" of Kotlin is that you can use data classes, so no need for tools like Immutables in theory.
Just for completeness, what is the Kotlin/Kapt version you're using to reproduce this?

**Comment by digitalbuddha** [comment]
kotlin_version = '1.0.5-2'
apply plugin 'kotlin-kapt'

**Comment by R4md4c** [comment]
I'm using kotlin-kapt(v1.1.0) with Immutables, and it seems that it is working.
I guess this issue could be closed.

**Comment by elucash** [comment]
@R4md4c thank you for good news! well, yes, let's close it. if there will be more issues we can create new ticket
