### ISSUE TITLE
Attributes marked with JsonIgnore are still required during JSON deserialization

### ISSUE THREAD

**Issue by walterxiao** [immutables/immutables#503]
I am using version 2.3.10. My domain model is defined as
```
@Value.Immutable
@JsonSerialize(as = com.xxx.ImmutableJsonIgnoreTest.class)
@JsonDeserialize(as = com.xxx.JsonIgnoreTest.class)
@JsonInclude(JsonInclude.Include.NON_NULL)
public interface JsonIgnoreTest {
    @JsonIgnore
    String getFieldJsonIgnored();

    String getFieldNormal();

    @Nullable
    String getFieldNullable();
}
```
So I assign values into `fieldJsonIgnored` and `fieldNormal`, after serialization into json, I can only see attribute `fieldNormal` in json which is expected. However, using the same json string to convert it back to JsonIgnoreTest, it will throw exception as below
```
Exception in thread "main" com.fasterxml.jackson.databind.JsonMappingException: Instantiation of [simple type, class com.xxx.ImmutableJsonIgnoreTest] value failed: Cannot build JsonIgnoreTest, some of required attributes are not set [fieldJsonIgnored]
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.wrapException(StdValueInstantiator.java:440)
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createUsingDelegate(StdValueInstantiator.java:276)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1067)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:268)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:124)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:2993)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2098)
	at 
Caused by: java.lang.IllegalStateException: Cannot build JsonIgnoreTest, some of required attributes are not set [fieldJsonIgnored]
	at com.xxx.ImmutableJsonIgnoreTest$Builder.build(ImmutableJsonIgnoreTest.java:303)
	at com.cvent.qna.model.ImmutableJsonIgnoreTest.fromJson(ImmutableJsonIgnoreTest.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.fasterxml.jackson.databind.introspect.AnnotatedMethod.call1(AnnotatedMethod.java:125)
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createUsingDelegate(StdValueInstantiator.java:258)
	... 12 more
```
I see ImmutableJsonIgnoreTest.Builder.initBits still checks `fieldJsonIgnore`. Can we make JsonIgnore annotation implies that the attribute is Nullable?

**Comment by elucash** [comment]
Thank you for reporting this! In Immutables, an attribute can be declared as non-mandatory via `@Nullable`, `Optional` or `@Value.Default` which are all different in their effect. At the moment I don't see a benefit in coupling Jackson's `@JsonIgnore` annotation to specific behavior such as `@Nullable`: trading minor convenience for implicit behavior. For your case, simply putting `@Nullable` annotation will do the trick.
I agree that this is somewhat unexpected. Currently, I propose to mark it as a docbug to make a section in a JSON guide explaining this.
