### ISSUE TITLE
Compilation failure in maven when using own @NonNull Annotation

### ISSUE THREAD

**Issue by ctolkmit** [immutables/immutables#573]
The following input causes my project to no longer be compilable with maven:

```
package de.tolkmit.rpgrules.core;

import org.immutables.value.Value;
import com.ennit.sal.lang.lib.safety.NonNull;

@Value.Immutable(intern = true)
public interface EntityType {

    @NonNull
    String getName();

    ValueRules getValueRules();


}
```

When compiling the project with maven, I get the following exception:

```
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /home/ctolkmit/ennit-sal-ws/rpgrules/src/main/java/de/tolkmit/rpgrules/core/RuleSet.java:[9,48] package de.tolkmit.rpgrules.core.ImmutableValues does not exist
[ERROR] /home/ctolkmit/ennit-sal-ws/rpgrules/src/main/java/de/tolkmit/rpgrules/core/RuleSet.java:[27,35] cannot find symbol
  symbol:   class Builder
  location: class de.tolkmit.rpgrules.core.RuleSet
[ERROR] /home/ctolkmit/ennit-sal-ws/rpgrules/src/main/java/de/tolkmit/rpgrules/srd35/Srd35RuleSet.java:[3,32] cannot find symbol
  symbol:   class ImmutableDerivedValue
  location: package de.tolkmit.rpgrules.core
[ERROR] /home/ctolkmit/ennit-sal-ws/rpgrules/src/main/java/de/tolkmit/rpgrules/srd35/Srd35RuleSet.java:[4,32] cannot find symbol
  symbol:   class ImmutableEntityType
  location: package de.tolkmit.rpgrules.core
[ERROR] /home/ctolkmit/ennit-sal-ws/rpgrules/src/main/java/de/tolkmit/rpgrules/srd35/Srd35RuleSet.java:[5,32] cannot find symbol
  symbol:   class ImmutableRuleSet
  location: package de.tolkmit.rpgrules.core
[ERROR] /home/ctolkmit/ennit-sal-ws/rpgrules/src/main/java/de/tolkmit/rpgrules/srd35/Srd35RuleSet.java:[6,32] cannot find symbol
  symbol:   class ImmutableValueRules
  location: package de.tolkmit.rpgrules.core
[ERROR] org.immutables.value.internal.$processor$.$Processor threw java.lang.IllegalArgumentException: Cannot parse type from input string '(@com.ennit.sal.lang.lib.safety.NonNull :: java.lang.String)'. unexpected term '('
        at org.immutables.value.internal.$processor$.encode.$Type$Parser$1Reader.type($Type.java:751)
        at org.immutables.value.internal.$processor$.encode.$Type$Parser.doParse($Type.java:852)
        at org.immutables.value.internal.$processor$.encode.$Type$Parser.parse($Type.java:700)
        at org.immutables.value.internal.$processor$.meta.$FromSupertypesModel.isEligibleFromType($FromSupertypesModel.java:136)
        at org.immutables.value.internal.$processor$.meta.$FromSupertypesModel.<init>($FromSupertypesModel.java:82)
        at org.immutables.value.internal.$processor$.meta.$ValueType.getBuildFromTypes($ValueType.java:1228)
        at org.immutables.value.internal.$processor$.$Generator_Immutables._t18__generateBuilder($Generator_Immutables.java:4812)
        at org.immutables.value.internal.$processor$.$Generator_Immutables$FragmentDispatch.run($Generator_Immutables.java:16115)
        at org.immutables.value.internal.$generator$.$Templates$Fragment.invoke($Templates.java:248)
        at org.immutables.value.internal.$generator$.$Intrinsics.$($Intrinsics.java:96)
        at org.immutables.value.internal.$processor$.$Generator_Immutables._t4__generateImmutable($Generator_Immutables.java:579)
        at org.immutables.value.internal.$processor$.$Generator_Immutables$FragmentDispatch.run($Generator_Immutables.java:16101)
        at org.immutables.value.internal.$generator$.$Templates$Fragment.invoke($Templates.java:248)
        at org.immutables.value.internal.$generator$.$Intrinsics.$($Intrinsics.java:96)
        at org.immutables.value.internal.$processor$.$Generator_Immutables$1.run($Generator_Immutables.java:23)
        at org.immutables.value.internal.$generator$.$Templates$Fragment.invoke($Templates.java:248)
        at org.immutables.value.internal.$generator$.$Output$7.invoke($Output.java:163)
        at org.immutables.value.internal.$generator$.$Intrinsics.$($Intrinsics.java:96)
        at org.immutables.value.internal.$processor$.$Generator_Immutables._t0__generate($Generator_Immutables.java:20)
        at org.immutables.value.internal.$processor$.$Generator_Immutables$FragmentDispatch.run($Generator_Immutables.java:16097)
        at org.immutables.value.internal.$generator$.$Templates$Fragment.invoke($Templates.java:248)
        at org.immutables.value.internal.$generator$.$AbstractGenerator.invoke($AbstractGenerator.java:57)
        at org.immutables.value.internal.$processor$.$Processor.process($Processor.java:63)
        at org.immutables.value.internal.$generator$.$AbstractGenerator.process($AbstractGenerator.java:87)
        at org.immutables.processor.ProxyProcessor.process(ProxyProcessor.java:72)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:794)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:705)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1035)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1176)
        at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
        at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:856)
        at com.sun.tools.javac.main.Main.compile(Main.java:523)
        at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:129)
        at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:138)
        at org.codehaus.plexus.compiler.javac.JavaxToolsCompiler.compileInProcess(JavaxToolsCompiler.java:125)
        at org.codehaus.plexus.compiler.javac.JavacCompiler.performCompile(JavacCompiler.java:171)
        at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:886)
        at org.apache.maven.plugin.compiler.CompilerMojo.execute(CompilerMojo.java:129)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
```

When I remove my own `@NonNull` annotation, everything works fine.

**Comment by elucash** [comment]
the probable fix released in 2.4.6
