### ISSUE TITLE
2.4.6 breaks defaulted specialized optionals

### ISSUE THREAD

**Issue by zfernandez88** [immutables/immutables#585]
This seems to be triggered by the fix made for #570.

When the type is identified as a specialized optional, type introspection is never completed. However, later during validation in validateTypeAndAnnotations(), it is remarked as a regular type and during the scalar check in hasSimpleScalarElementType(), we get a NPE when checking extendedClassesNames. 

Naively feels like just re-ordering the check in the generator will fix (v.isSuppressedOptional || v.hasSimpleScalarElementType()). 

```Java
import org.immutables.value.Value;
import java.util.OptionalInt;

@Value.Immutable
public interface DefaultSpecializedOptionals {
    @Value.Default
    default OptionalInt value() {
        return OptionalInt.empty();
    }
}
```

```
[ERROR] org.immutables.value.internal.$processor$.$Processor threw java.lang.NullPointerException
  	at org.immutables.value.internal.$processor$.meta.$ValueAttribute.hasSimpleScalarElementType($ValueAttribute.java:161)
  	at org.immutables.value.internal.$processor$.$Generator_Immutables._t44__generateCopyMethods($Generator_Immutables.java:13246)
  	at org.immutables.value.internal.$processor$.$Generator_Immutables$FragmentDispatch.run($Generator_Immutables.java:16131)
  	at org.immutables.value.internal.$generator$.$Templates$Fragment.invoke($Templates.java:248)
  	at org.immutables.value.internal.$generator$.$Intrinsics.$($Intrinsics.java:96)
  	at org.immutables.value.internal.$processor$.$Generator_Immutables._t32__generateImmutableMembers($Generator_Immutables.java:10277)
  	at org.immutables.value.internal.$processor$.$Generator_Immutables$FragmentDispatch.run($Generator_Immutables.java:16119)
  	at org.immutables.value.internal.$generator$.$Templates$Fragment.invoke($Templates.java:248)
  	at org.immutables.value.internal.$generator$.$Intrinsics.$($Intrinsics.java:96)
  	at org.immutables.value.internal.$processor$.$Generator_Immutables._t4__generateImmutable($Generator_Immutables.java:447)
  	at org.immutables.value.internal.$processor$.$Generator_Immutables$FragmentDispatch.run($Generator_Immutables.java:16091)
  	at org.immutables.value.internal.$generator$.$Templates$Fragment.invoke($Templates.java:248)
  	at org.immutables.value.internal.$generator$.$Intrinsics.$($Intrinsics.java:96)
  	at org.immutables.value.internal.$processor$.$Generator_Immutables$1.run($Generator_Immutables.java:23)
  	at org.immutables.value.internal.$generator$.$Templates$Fragment.invoke($Templates.java:248)
  	at org.immutables.value.internal.$generator$.$Output$7.invoke($Output.java:163)
  	at org.immutables.value.internal.$generator$.$Intrinsics.$($Intrinsics.java:96)
  	at org.immutables.value.internal.$processor$.$Generator_Immutables._t0__generate($Generator_Immutables.java:20)
  	at org.immutables.value.internal.$processor$.$Generator_Immutables$FragmentDispatch.run($Generator_Immutables.java:16087)
  	at org.immutables.value.internal.$generator$.$Templates$Fragment.invoke($Templates.java:248)
  	at org.immutables.value.internal.$generator$.$AbstractGenerator.invoke($AbstractGenerator.java:57)
  	at org.immutables.value.internal.$processor$.$Processor.process($Processor.java:63)
  	at org.immutables.value.internal.$generator$.$AbstractGenerator.process($AbstractGenerator.java:87)
  	at org.immutables.processor.ProxyProcessor.process(ProxyProcessor.java:72)
  	at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:794)
```

**Comment by elucash** [comment]
indeed, have to be fixed. Thank you for reporting this!
