### ISSUE TITLE
Spring Data, MongoRepository and @Query causes InvalidPersistentPropertyPath exception

### ISSUE THREAD

**Issue by guardiande** [immutables/immutables#640]
Here's an Immutable

```$java
@Value.Immutable
public abstract class Person {
	@Id
	public abstract String getId();
	public abstract String getName();
}
```

I store persons in a Spring Data MongoRepository

```$java
public interface PersonRepository extends MongoRepository<Person, String> {
	@Query("{ 'name' : ?0 }")
	List<Person> findWithQuery(String userId);
}
```

When I try to retrieve entries from the database by calling `findWithQuery` I get the following exception:

```
org.springframework.data.mapping.context.InvalidPersistentPropertyPath: No property name found on test.mongo.Person!
	at org.springframework.data.mapping.context.AbstractMappingContext.getPersistentPropertyPath(AbstractMappingContext.java:262)
	at org.springframework.data.mapping.context.AbstractMappingContext.getPersistentPropertyPath(AbstractMappingContext.java:235)
	at org.springframework.data.mapping.context.AbstractMappingContext.getPersistentPropertyPath(AbstractMappingContext.java:210)
	at org.springframework.data.mongodb.core.convert.QueryMapper$MetadataBackedField.getPath(QueryMapper.java:867)
	at org.springframework.data.mongodb.core.convert.QueryMapper$MetadataBackedField.<init>(QueryMapper.java:758)
	at org.springframework.data.mongodb.core.convert.QueryMapper$MetadataBackedField.<init>(QueryMapper.java:735)
	at org.springframework.data.mongodb.core.convert.QueryMapper.createPropertyField(QueryMapper.java:231)
	at org.springframework.data.mongodb.core.convert.QueryMapper.getMappedObject(QueryMapper.java:129)
	at org.springframework.data.mongodb.core.MongoTemplate.doFind(MongoTemplate.java:1777)
	at org.springframework.data.mongodb.core.MongoTemplate.doFind(MongoTemplate.java:1767)
	at org.springframework.data.mongodb.core.MongoTemplate.find(MongoTemplate.java:641)
```

It seems that Spring Data (Mongo) does not recognize the attributes of the Person class (because setters are missing?).

Any helpers?

**Comment by guardiande** [comment]
And this also fails (and I guess because of the same reason):

```$java
public void run(String... args) throws Exception {
	Person peter = ImmutablePerson.builder().name("Peter").build();
	Person sally = ImmutablePerson.builder().name("Sally").build();
	
	repository.save(peter);
	repository.save(sally);

	Person person = repository.findAll().get(0);
	Person changedPerson = ImmutablePerson.copyOf(person).withName("Changed");
		
	repository.save(changedPerson);
}
```

Exception:

```
java.lang.IllegalStateException: Failed to execute CommandLineRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:779) [spring-boot-1.5.3.RELEASE.jar:1.5.3.RELEASE]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:760) [spring-boot-1.5.3.RELEASE.jar:1.5.3.RELEASE]
	at org.springframework.boot.SpringApplication.afterRefresh(SpringApplication.java:747) [spring-boot-1.5.3.RELEASE.jar:1.5.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) [spring-boot-1.5.3.RELEASE.jar:1.5.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1162) [spring-boot-1.5.3.RELEASE.jar:1.5.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1151) [spring-boot-1.5.3.RELEASE.jar:1.5.3.RELEASE]
	at test.mongo.Application.main(Application.java:33) [bin/:na]
Caused by: org.springframework.dao.DuplicateKeyException: Write failed with error code 11000 and error message 'E11000 duplicate key error collection: person.person index: _id_ dup key: { : ObjectId('594012408213f52f1cc48024') }'; nested exception is com.mongodb.DuplicateKeyException: Write failed with error code 11000 and error message 'E11000 duplicate key error collection: person.person index: _id_ dup key: { : ObjectId('594012408213f52f1cc48024') }'
	at org.springframework.data.mongodb.core.MongoExceptionTranslator.translateExceptionIfPossible(MongoExceptionTranslator.java:73) ~[spring-data-mongodb-1.10.3.RELEASE.jar:na]
	at org.springframework.data.mongodb.core.MongoTemplate.potentiallyConvertRuntimeException(MongoTemplate.java:2135) ~[spring-data-mongodb-1.10.3.RELEASE.jar:na]
	at org.springframework.data.mongodb.core.MongoTemplate.execute(MongoTemplate.java:481) ~[spring-data-mongodb-1.10.3.RELEASE.jar:na]
	at org.springframework.data.mongodb.core.MongoTemplate.insertDBObject(MongoTemplate.java:1046) ~[spring-data-mongodb-1.10.3.RELEASE.jar:na]
	at org.springframework.data.mongodb.core.MongoTemplate.doInsert(MongoTemplate.java:855) ~[spring-data-mongodb-1.10.3.RELEASE.jar:na]
	at org.springframework.data.mongodb.core.MongoTemplate.insert(MongoTemplate.java:796) ~[spring-data-mongodb-1.10.3.RELEASE.jar:na]
	at org.springframework.data.mongodb.repository.support.SimpleMongoRepository.save(SimpleMongoRepository.java:80) ~[spring-data-mongodb-1.10.3.RELEASE.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_131]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_131]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_131]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_131]
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.executeMethodOn(RepositoryFactorySupport.java:504) ~[spring-data-commons-1.13.3.RELEASE.jar:na]
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.doInvoke(RepositoryFactorySupport.java:489) ~[spring-data-commons-1.13.3.RELEASE.jar:na]
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.invoke(RepositoryFactorySupport.java:461) ~[spring-data-commons-1.13.3.RELEASE.jar:na]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:61) ~[spring-data-commons-1.13.3.RELEASE.jar:na]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92) ~[spring-aop-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.data.repository.core.support.SurroundingTransactionDetectorMethodInterceptor.invoke(SurroundingTransactionDetectorMethodInterceptor.java:57) ~[spring-data-commons-1.13.3.RELEASE.jar:na]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213) ~[spring-aop-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at com.sun.proxy.$Proxy51.save(Unknown Source) ~[na:na]
	at test.mongo.Application.run(Application.java:29) [bin/:na]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:776) [spring-boot-1.5.3.RELEASE.jar:1.5.3.RELEASE]
	... 6 common frames omitted
Caused by: com.mongodb.DuplicateKeyException: Write failed with error code 11000 and error message 'E11000 duplicate key error collection: person.person index: _id_ dup key: { : ObjectId('594012408213f52f1cc48024') }'
	at com.mongodb.operation.BaseWriteOperation.convertBulkWriteException(BaseWriteOperation.java:243) ~[mongodb-driver-core-3.4.2.jar:na]
	at com.mongodb.operation.BaseWriteOperation.access$300(BaseWriteOperation.java:60) ~[mongodb-driver-core-3.4.2.jar:na]
	at com.mongodb.operation.BaseWriteOperation$1.call(BaseWriteOperation.java:144) ~[mongodb-driver-core-3.4.2.jar:na]
	at com.mongodb.operation.BaseWriteOperation$1.call(BaseWriteOperation.java:133) ~[mongodb-driver-core-3.4.2.jar:na]
	at com.mongodb.operation.OperationHelper.withConnectionSource(OperationHelper.java:422) ~[mongodb-driver-core-3.4.2.jar:na]
	at com.mongodb.operation.OperationHelper.withConnection(OperationHelper.java:413) ~[mongodb-driver-core-3.4.2.jar:na]
	at com.mongodb.operation.BaseWriteOperation.execute(BaseWriteOperation.java:133) ~[mongodb-driver-core-3.4.2.jar:na]
	at com.mongodb.operation.BaseWriteOperation.execute(BaseWriteOperation.java:60) ~[mongodb-driver-core-3.4.2.jar:na]
	at com.mongodb.Mongo.execute(Mongo.java:845) ~[mongodb-driver-3.4.2.jar:na]
	at com.mongodb.Mongo$2.execute(Mongo.java:828) ~[mongodb-driver-3.4.2.jar:na]
	at com.mongodb.DBCollection.executeWriteOperation(DBCollection.java:342) ~[mongodb-driver-3.4.2.jar:na]
	at com.mongodb.DBCollection.insert(DBCollection.java:337) ~[mongodb-driver-3.4.2.jar:na]
	at com.mongodb.DBCollection.insert(DBCollection.java:328) ~[mongodb-driver-3.4.2.jar:na]
	at com.mongodb.DBCollection.insert(DBCollection.java:298) ~[mongodb-driver-3.4.2.jar:na]
	at com.mongodb.DBCollection.insert(DBCollection.java:264) ~[mongodb-driver-3.4.2.jar:na]
	at com.mongodb.DBCollection.insert(DBCollection.java:201) ~[mongodb-driver-3.4.2.jar:na]
	at org.springframework.data.mongodb.core.MongoTemplate$9.doInCollection(MongoTemplate.java:1051) ~[spring-data-mongodb-1.10.3.RELEASE.jar:na]
	at org.springframework.data.mongodb.core.MongoTemplate.execute(MongoTemplate.java:479) ~[spring-data-mongodb-1.10.3.RELEASE.jar:na]
	... 28 common frames omitted
```

Replacing the Immutable implementation with a "classical" one, works like a charm.

**Comment by elucash** [comment]
I cannot say about all the issues with spring data, but one of the things you may try is using spring's `@PersistenceConstructor` annotation, please see example in #456

**Comment by guardiande** [comment]
Thanks for the hint. Actually I already did that and it did not help:

```$java
@Value.Immutable
@Style(of = "new", allParameters = true, jdkOnly = true, passAnnotations = {PersistenceConstructor.class})
@JsonSerialize(as = ImmutablePerson.class)
@JsonDeserialize(as = ImmutablePerson.class)
public abstract class Person {
	@PersistenceConstructor
	public Person() {
	}
	
	@Id
	@Nullable
	public abstract String getId();
	public abstract String getName();
}
```

**Comment by elucash** [comment]
Can you, please, inspect generated code for the "wrong things". If generated constructor is correct (i.e. have all the parameters and annotations), it might be a problem with Spring Data

**Comment by guardiande** [comment]
Looks good to me...

```$java
@PersistenceConstructor
public ImmutablePerson(@Nullable String id, String name) {
    this.id = id;   this.name = Objects.requireNonNull(name, "name");
}
```

**Comment by guardiande** [comment]
But I don't think that it is a problem with the constructor but with the property identification. I did not yet dig into Spring Data to see how properties are discovered.

**Comment by elucash** [comment]
Would there be any difference if we add `passAnnotations = {PersistenceConstructor.class, Id.class}` ? Also I don't get why id is nullable. it should not be null, otherwise mongo will create `ObjectID` you can use `@Value.Default` to generate default random value, like `new ObjectID().toString()` or whatever

**Comment by guardiande** [comment]
Already tried to pass the Id annotation - same result. I thought having the id set to null tells mongodb to create a new instance (like in this example https://spring.io/guides/gs/accessing-data-mongodb/).

**Comment by elucash** [comment]
It's probably spring-data specific, mongo driver would create ObjectID instance if '_id' is null/absent and have no idea that null supposed to be string or anything else, so Spring creates it, most likely, as a string, crazy framework. Maybe, following line `List<Person> findWithQuery(String userId);` should refer to generated `ImmutablePerson` class and, overall, it should be ` extends MongoRepository<ImmutablePerson, String>`. Introspection of abstract class may give spring not enouph information.

**Comment by guardiande** [comment]
I digged a little into Spring Data but did not find the origin of the error quickly. I'll move away from Immutables for the moment.

Thank you for the support.
