### ISSUE TITLE
NoSuchFieldError: MODULE during APT-ing in Eclipse 4.8.0 DEV (Photon Milestone M2-M3)

### ISSUE THREAD

**Issue by vorburger** [immutables/immutables#701]
I'm seeing the problem below in the Error Log of a (bleeding edge, yes) Eclipse Photon..

Not sure if this is "just" an Eclipse bug, or something (too) fancy that Immutables.org is doing re. APT:

```
Exception:java.lang.Exception: java.lang.NoSuchFieldError: MODULE
	 at org.eclipse.jdt.internal.compiler.apt.dispatch.RoundDispatcher.handleProcessor(RoundDispatcher.java:169)
	 at org.eclipse.jdt.internal.compiler.apt.dispatch.RoundDispatcher.round(RoundDispatcher.java:121)
	 at org.eclipse.jdt.internal.compiler.apt.dispatch.BaseAnnotationProcessorManager.processAnnotations(BaseAnnotationProcessorManager.java:159)
	 at org.eclipse.jdt.internal.apt.pluggable.core.dispatch.IdeAnnotationProcessorManager.processAnnotations(IdeAnnotationProcessorManager.java:135)
	 at org.eclipse.jdt.internal.compiler.Compiler.processAnnotations(Compiler.java:933)
	 at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:443)
	 at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:419)
	 at org.eclipse.jdt.internal.core.builder.AbstractImageBuilder.compile(AbstractImageBuilder.java:372)
	 at org.eclipse.jdt.internal.core.builder.BatchImageBuilder.compile(BatchImageBuilder.java:187)
	 at org.eclipse.jdt.internal.core.builder.AbstractImageBuilder.compile(AbstractImageBuilder.java:305)
	 at org.eclipse.jdt.internal.core.builder.BatchImageBuilder.build(BatchImageBuilder.java:61)
	 at org.eclipse.jdt.internal.core.builder.JavaBuilder.buildAll(JavaBuilder.java:256)
	 at org.eclipse.jdt.internal.core.builder.JavaBuilder.build(JavaBuilder.java:175)
	 at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:735)
	 at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	 at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
	 at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
	 at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:301)
	 at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	 at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:304)
	 at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:360)
	 at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:383)
	 at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:142)
	 at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:232)
	 at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
Caused by: java.lang.NoSuchFieldError: MODULE
	 at org.eclipse.jdt.internal.compiler.apt.model.ModuleElementImpl.getKind(ModuleElementImpl.java:63)
	 at org.immutables.value.internal.$processor$.meta.$ImportRewriteDisabler.shouldDisableFor($ImportRewriteDisabler.java:66)
	 at org.immutables.value.internal.$processor$.meta.$ImportRewriteDisabler.shouldDisableFor($ImportRewriteDisabler.java:40)
	 at org.immutables.value.internal.$processor$.meta.$ValueType.sourceHeader($ValueType.java:99)
	 at org.immutables.value.internal.$processor$.$Generator_Immutables._t2__packageWhenTopLevel($Generator_Immutables.java:156)
	 at org.immutables.value.internal.$processor$.$Generator_Immutables$FragmentDispatch.run($Generator_Immutables.java:16050)
	 at org.immutables.value.internal.$generator$.$Templates$Fragment.invoke($Templates.java:248)
	 at org.immutables.value.internal.$generator$.$Intrinsics.$($Intrinsics.java:96)
	 at org.immutables.value.internal.$processor$.$Generator_Immutables._t4__generateImmutable($Generator_Immutables.java:303)
	 at org.immutables.value.internal.$processor$.$Generator_Immutables$FragmentDispatch.run($Generator_Immutables.java:16052)
	 at org.immutables.value.internal.$generator$.$Templates$Fragment.invoke($Templates.java:248)
	 at org.immutables.value.internal.$generator$.$Intrinsics.$($Intrinsics.java:96)
	 at org.immutables.value.internal.$processor$.$Generator_Immutables$1.run($Generator_Immutables.java:23)
	 at org.immutables.value.internal.$generator$.$Templates$Fragment.invoke($Templates.java:248)
	 at org.immutables.value.internal.$generator$.$Output$7.invoke($Output.java:163)
	 at org.immutables.value.internal.$generator$.$Intrinsics.$($Intrinsics.java:96)
	 at org.immutables.value.internal.$processor$.$Generator_Immutables._t0__generate($Generator_Immutables.java:20)
	 at org.immutables.value.internal.$processor$.$Generator_Immutables$FragmentDispatch.run($Generator_Immutables.java:16048)
	 at org.immutables.value.internal.$generator$.$Templates$Fragment.invoke($Templates.java:248)
	 at org.immutables.value.internal.$generator$.$AbstractGenerator.invoke($AbstractGenerator.java:57)
	 at org.immutables.value.internal.$processor$.$Processor.process($Processor.java:63)
	 at org.immutables.value.internal.$generator$.$AbstractGenerator.process($AbstractGenerator.java:87)
	 at org.immutables.processor.ProxyProcessor.process(ProxyProcessor.java:72)
	 at org.eclipse.jdt.internal.compiler.apt.dispatch.RoundDispatcher.handleProcessor(RoundDispatcher.java:139)
	 at org.eclipse.jdt.internal.compiler.apt.dispatch.RoundDispatcher.round(RoundDispatcher.java:121)
	 at org.eclipse.jdt.internal.compiler.apt.dispatch.BaseAnnotationProcessorManager.processAnnotations(BaseAnnotationProcessorManager.java:159)
	 at org.eclipse.jdt.internal.apt.pluggable.core.dispatch.IdeAnnotationProcessorManager.processAnnotations(IdeAnnotationProcessorManager.java:135)
	 at org.eclipse.jdt.internal.compiler.Compiler.processAnnotations(Compiler.java:933)
	 at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:443)
	 at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:419)
	 at org.eclipse.jdt.internal.core.builder.AbstractImageBuilder.compile(AbstractImageBuilder.java:372)
	 at org.eclipse.jdt.internal.core.builder.BatchImageBuilder.compile(BatchImageBuilder.java:187)
	 at org.eclipse.jdt.internal.core.builder.AbstractImageBuilder.compile(AbstractImageBuilder.java:305)
	 at org.eclipse.jdt.internal.core.builder.BatchImageBuilder.build(BatchImageBuilder.java:61)
	 at org.eclipse.jdt.internal.core.builder.JavaBuilder.buildAll(JavaBuilder.java:256)
	 at org.eclipse.jdt.internal.core.builder.JavaBuilder.build(JavaBuilder.java:175)
	 at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:735)
	 at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	 at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
	 at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
	 at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:301)
	 at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	 at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:304)
	 at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:360)
	 at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:383)
	 at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:142)
	 at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:232)
	 at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
```

**Comment by elucash** [comment]
I suspect the code in Immutables might assume that the top element should be package, not module, which might need to corrected. But there still a lot in this error for ECJ itself as it cannot find field it compiled against. Need to peek into latest ECJ source code to try to figure it out.

**Comment by davido** [comment]
Seems to be a similar problem as reported here: [1], here: [2] and here [3].

* [1] https://github.com/google/dagger/issues/898
* [2] https://github.com/google/dagger/issues/898
* [3] https://bugs.eclipse.org/bugs/show_bug.cgi?id=526288

**Comment by elucash** [comment]
thank you @davido for heads up.

In nutshell: this is Eclipse problem, preventing APT from working properly if not running under Java 9.

please, lmk if there are specific workaround we can put into Immutables (like not asking package for enclosing elements?)

**Comment by vorburger** [comment]
@elucash for me (as original issue reporter) I'm OK if you just close this, as based on [eclipse.org Bug 526288](https://bugs.eclipse.org/bugs/show_bug.cgi?id=526288) we now know it's clearly "just" an issue in Eclipse versions (apparently) 4.7.1a and later (but not affecting 4.7.0 and earlier), which I trust will get fixed there, sooner or later. 

PS: Note that the same bug says that running Eclipse under Java 9 works around that bug (works for me).

**Comment by elucash** [comment]
agree, but let it hang for a while, so less chance that we will get duplicates and can people more easily found workarounds.
