### ISSUE TITLE
Proguard removing static TypeToken.getParameterized(...) method call in generated GsonAdapter

### ISSUE THREAD

**Issue by REWmitenko** [immutables/immutables#704]
Hi All,

I'm hoping you'll be able to help with this. I have a related post up on [stackoverflow](https://stackoverflow.com/questions/46818195/fatal-error-applying-proguard-to-retrofit2-and-gsonadapters).

My understanding of what is happening is that, for some reason, Proguard is stripping out a method call despite my best efforts to tell it to retain this method.

Here's the error as it appears:
```
 java.lang.NoSuchMethodError: No static method getParameterized(Ljava/lang/reflect/Type;[Ljava/lang/reflect/Type;)Lcom/google/gson/reflect/TypeToken; in class Lcom/google/gson/reflect/TypeToken; or its super classes (declaration of 'com.google.gson.reflect.TypeToken' appears in /data/app/com.rw.crm.leads-1/base.apk)
                                                                                        at com.rw.crm.leads.model.response.GsonAdaptersResponse$ListResponseTypeAdapter.<init>(GsonAdaptersResponse.java:185)
                                                                                        at com.rw.crm.leads.model.response.GsonAdaptersResponse.create(GsonAdaptersResponse.java:36)
```

Here's my gson proguard rules:
```
# Gson uses generic type information stored in a class file when working with fields. Proguard
# removes such information by default, so configure it to keep all of it.
-keepattributes Signature

# For using GSON @Expose annotation
-keepattributes *Annotation*

# Gson specific classes
-dontwarn sun.misc.**
#-keep class com.google.gson.stream.** { *; }

# Prevent proguard from stripping interface information from TypeAdapterFactory,
# JsonSerializer, JsonDeserializer instances (so they can be used in @JsonAdapter)
-keep class * implements com.google.gson.TypeAdapterFactory
-keep class * implements com.google.gson.JsonSerializer
-keep class * implements com.google.gson.JsonDeserializer

-dontwarn com.google.gson.reflect.TypeToken
# why don't these work?
-keep class com.google.gson.reflect.TypeToken { *; }
-keep class * implements com.google.gson.reflect.TypeToken { *; }
```

What's really weird is that the dontwarn notation allows the code to compile, but the keep class rules don't appear to be working. If I remove the dontwarn rule, I get nine ```unresolved references to program class member``` errors like this:
```
Warning:com.rw.crm.leads.model.email.GsonAdaptersEmail$AgentSectionTypeAdapter: can't find referenced method 'com.google.gson.reflect.TypeToken getParameterized(java.lang.reflect.Type,java.lang.reflect.Type[])' in program class com.google.gson.reflect.TypeToken
```

I am explicitly registering the GsonAdapters, so they are referenced in the code.

**Comment by REWmitenko** [comment]
Hm.

Okay I managed to resolve this by adding the latest gson library to my gradle file.
```
    compile 'com.google.code.gson:gson:2.8.2'
```
