### ISSUE TITLE
APT fails in Eclipse because of JDK9-Dependency

### ISSUE THREAD

**Issue by bmhm** [immutables/immutables#727]
Hello Immutables-Team!

I got a standard maven & JDK8 project.

The APT fails with the following error message.
The odd part is, ElementKind.MODULE is available in JDK9, but not JDK8 (which I am using).

Any ideas what is wrong?

Using Immutables-2.5.6.

```
java.lang.Exception: java.lang.NoSuchFieldError: javax/lang/model/element/ElementKind.MODULE
	at org.eclipse.jdt.internal.compiler.apt.dispatch.RoundDispatcher.handleProcessor(RoundDispatcher.java:169)
	at org.eclipse.jdt.internal.compiler.apt.dispatch.RoundDispatcher.round(RoundDispatcher.java:121)
	at org.eclipse.jdt.internal.compiler.apt.dispatch.BaseAnnotationProcessorManager.processAnnotations(BaseAnnotationProcessorManager.java:159)
	at org.eclipse.jdt.internal.apt.pluggable.core.dispatch.IdeAnnotationProcessorManager.processAnnotations(IdeAnnotationProcessorManager.java:135)
	at org.eclipse.jdt.internal.compiler.Compiler.processAnnotations(Compiler.java:933)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:443)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:419)
	at org.eclipse.jdt.internal.core.builder.AbstractImageBuilder.compile(AbstractImageBuilder.java:372)
	at org.eclipse.jdt.internal.core.builder.BatchImageBuilder.compile(BatchImageBuilder.java:187)
	at org.eclipse.jdt.internal.core.builder.AbstractImageBuilder.compile(AbstractImageBuilder.java:305)
	at org.eclipse.jdt.internal.core.builder.BatchImageBuilder.build(BatchImageBuilder.java:61)
	at org.eclipse.jdt.internal.core.builder.JavaBuilder.buildAll(JavaBuilder.java:256)
	at org.eclipse.jdt.internal.core.builder.JavaBuilder.build(JavaBuilder.java:175)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:735)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:301)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:304)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:360)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:383)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:142)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:232)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
Caused by: java.lang.NoSuchFieldError: javax/lang/model/element/ElementKind.MODULE
	at org.eclipse.jdt.internal.compiler.apt.model.ModuleElementImpl.getKind(ModuleElementImpl.java:64)
	at org.immutables.value.internal.$processor$.meta.$ImportRewriteDisabler.shouldDisableFor($ImportRewriteDisabler.java:66)
	at org.immutables.value.internal.$processor$.meta.$ImportRewriteDisabler.shouldDisableFor($ImportRewriteDisabler.java:40)
	at org.immutables.value.internal.$processor$.meta.$ValueType.sourceHeader($ValueType.java:99)
	at org.immutables.value.internal.$processor$.$Generator_Immutables._t2__packageWhenTopLevel($Generator_Immutables.java:156)
	at org.immutables.value.internal.$processor$.$Generator_Immutables$FragmentDispatch.run($Generator_Immutables.java:16633)
	at org.immutables.value.internal.$generator$.$Templates$Fragment.invoke($Templates.java:248)
	at org.immutables.value.internal.$generator$.$Intrinsics.$($Intrinsics.java:96)
	at org.immutables.value.internal.$processor$.$Generator_Immutables._t4__generateImmutable($Generator_Immutables.java:320)
	at org.immutables.value.internal.$processor$.$Generator_Immutables$FragmentDispatch.run($Generator_Immutables.java:16635)
	at org.immutables.value.internal.$generator$.$Templates$Fragment.invoke($Templates.java:248)
	at org.immutables.value.internal.$generator$.$Intrinsics.$($Intrinsics.java:96)
	at org.immutables.value.internal.$processor$.$Generator_Immutables$1.run($Generator_Immutables.java:23)
	at org.immutables.value.internal.$generator$.$Templates$Fragment.invoke($Templates.java:248)
	at org.immutables.value.internal.$generator$.$Output$7.invoke($Output.java:163)
	at org.immutables.value.internal.$generator$.$Intrinsics.$($Intrinsics.java:96)
	at org.immutables.value.internal.$processor$.$Generator_Immutables._t0__generate($Generator_Immutables.java:20)
	at org.immutables.value.internal.$processor$.$Generator_Immutables$FragmentDispatch.run($Generator_Immutables.java:16631)
	at org.immutables.value.internal.$generator$.$Templates$Fragment.invoke($Templates.java:248)
	at org.immutables.value.internal.$generator$.$AbstractGenerator.invoke($AbstractGenerator.java:57)
	at org.immutables.value.internal.$processor$.$Processor.process($Processor.java:63)
	at org.immutables.value.internal.$generator$.$AbstractGenerator.process($AbstractGenerator.java:87)
	at org.immutables.processor.ProxyProcessor.process(ProxyProcessor.java:72)
	at org.eclipse.jdt.internal.compiler.apt.dispatch.RoundDispatcher.handleProcessor(RoundDispatcher.java:139)
	... 24 more

```

**Comment by elucash** [comment]
Hi Ben, as of now it's known eclipse issue and we expect to get the fix from there (updated version of Eclipse), as a workaround you can run Eclipse under JDK9.  Please see #701

**Comment by bmhm** [comment]
Hi @elucash, thanks for the hint.

I'll try the new IBM OSS JDK9 (J9) instead, which is now an Eclipse Project:
https://adoptopenjdk.net/releases.html?variant=openjdk9-openj9
(Former name: IBM J9).

You might want to include this in your tests as well. J9 is a very good JRE/JDK.

Thanks for the info, I'll close this as dup.
