### ISSUE TITLE
Caused by: java.lang.UnsupportedOperationException: Don't know how to write java.math.BigDecimal

### ISSUE THREAD

**Issue by darren014** [immutables/immutables#729]
Hi Immutables team,

BigDecimal serialization is ok in version 2.5.5.
I have encountered unsupportedOperation for BigDecimal serialization in  2.6.0-alpha1.

Kind regards,
Darren

java.util.concurrent.ExecutionException: java.lang.UnsupportedOperationException: Don't know how to write java.math.BigDecimal: 59.560001
	at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:476)
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:455)
	at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:79)
	at com.google.common.util.concurrent.ForwardingFuture.get(ForwardingFuture.java:63)
	at io.reactivex.internal.operators.flowable.FlowableFromFuture.subscribeActual(FlowableFromFuture.java:42)
	at io.reactivex.Flowable.subscribe(Flowable.java:13041)
	at io.reactivex.internal.operators.flowable.FlowableSingleSingle.subscribeActual(FlowableSingleSingle.java:39)
	at io.reactivex.Single.subscribe(Single.java:2779)
	at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:26)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.UnsupportedOperationException: Don't know how to write java.math.BigDecimal: 59.560001
	at org.immutables.mongo.repository.internal.BsonWriter.value(BsonWriter.java:157)
	at com.google.gson.internal.bind.TypeAdapters$17.write(TypeAdapters.java:423)
	at com.google.gson.internal.bind.TypeAdapters$17.write(TypeAdapters.java:409)
	at com.example.reactive.model.GsonAdaptersQuote$QuoteTypeAdapter.writeQuote(GsonAdaptersQuote.java:72)
	at com.example.reactive.model.GsonAdaptersQuote$QuoteTypeAdapter.write(GsonAdaptersQuote.java:55)
	at com.example.reactive.model.GsonAdaptersQuote$QuoteTypeAdapter.write(GsonAdaptersQuote.java:1)
	at com.example.reactive.model.GsonAdaptersHistoricalStockQuote$HistoricalStockQuoteTypeAdapter.writeHistoricalStockQuote(GsonAdaptersHistoricalStockQuote.java:75)
	at com.example.reactive.model.GsonAdaptersHistoricalStockQuote$HistoricalStockQuoteTypeAdapter.write(GsonAdaptersHistoricalStockQuote.java:53)
	at com.example.reactive.model.GsonAdaptersHistoricalStockQuote$HistoricalStockQuoteTypeAdapter.write(GsonAdaptersHistoricalStockQuote.java:1)
	at org.immutables.mongo.repository.internal.BsonEncoding$4.encode(BsonEncoding.java:124)
	at org.immutables.mongo.repository.internal.BsonEncoding$2.encode(BsonEncoding.java:80)
	at org.bson.codecs.BsonDocumentWrapperCodec.encode(BsonDocumentWrapperCodec.java:63)
	at org.bson.codecs.BsonDocumentWrapperCodec.encode(BsonDocumentWrapperCodec.java:29)
	at com.mongodb.connection.InsertCommandMessage.writeTheWrites(InsertCommandMessage.java:91)
	at com.mongodb.connection.InsertCommandMessage.writeTheWrites(InsertCommandMessage.java:43)
	at com.mongodb.connection.BaseWriteCommandMessage.encodeMessageBodyWithMetadata(BaseWriteCommandMessage.java:120)
	at com.mongodb.connection.RequestMessage.encodeWithMetadata(RequestMessage.java:147)
	at com.mongodb.connection.WriteCommandProtocol.sendMessage(WriteCommandProtocol.java:212)
	at com.mongodb.connection.WriteCommandProtocol.execute(WriteCommandProtocol.java:93)
	at com.mongodb.connection.InsertCommandProtocol.execute(InsertCommandProtocol.java:58)
	at com.mongodb.connection.InsertCommandProtocol.execute(InsertCommandProtocol.java:37)
	at com.mongodb.connection.DefaultServer$DefaultServerProtocolExecutor.execute(DefaultServer.java:159)
	at com.mongodb.connection.DefaultServerConnection.executeProtocol(DefaultServerConnection.java:289)
	at com.mongodb.connection.DefaultServerConnection.insertCommand(DefaultServerConnection.java:118)
	at com.mongodb.operation.MixedBulkWriteOperation$Run$2.executeWriteCommandProtocol(MixedBulkWriteOperation.java:465)
	at com.mongodb.operation.MixedBulkWriteOperation$Run$RunExecutor.execute(MixedBulkWriteOperation.java:656)
	at com.mongodb.operation.MixedBulkWriteOperation$Run.execute(MixedBulkWriteOperation.java:411)
	at com.mongodb.operation.MixedBulkWriteOperation$1.call(MixedBulkWriteOperation.java:177)
	at com.mongodb.operation.MixedBulkWriteOperation$1.call(MixedBulkWriteOperation.java:168)
	at com.mongodb.operation.OperationHelper.withConnectionSource(OperationHelper.java:424)
	at com.mongodb.operation.OperationHelper.withConnection(OperationHelper.java:415)
	at com.mongodb.operation.MixedBulkWriteOperation.execute(MixedBulkWriteOperation.java:168)
	at com.mongodb.operation.MixedBulkWriteOperation.execute(MixedBulkWriteOperation.java:74)
	at com.mongodb.Mongo.execute(Mongo.java:819)
	at com.mongodb.Mongo$2.execute(Mongo.java:802)
	at com.mongodb.MongoCollectionImpl.insertMany(MongoCollectionImpl.java:338)
	at com.mongodb.MongoCollectionImpl.insertMany(MongoCollectionImpl.java:322)
	at org.immutables.mongo.repository.Repositories$Repository$2.call(Repositories.java:141)
	at org.immutables.mongo.repository.Repositories$Repository$2.call(Repositories.java:138)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:108)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:41)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:77)
	... 3 more

**Comment by elucash** [comment]
Making fixes to code to allow BigDecimal serialization as before (in master, not released yet). While this will work, there's still some gimmick if someone wants to use something else than `String` type. For example, to support BSON's `Decimal128` as binding for `BigDecimal`, special type adapter have to be manually registered.
