### ISSUE TITLE
ClassCastException: org.immutables.value.internal.$processor$.$Processor cannot be cast to javax.annotation.processing.Processor in Eclipse 4.8 (Photon)

### ISSUE THREAD

**Issue by vorburger** [immutables/immutables#745]
Similarly to earlier https://github.com/immutables/immutables/issues/701, but this seems to be a new one AFAIK:

I'm seeing the problem below in the Error Log of a (bleeding edge, yes) Eclipse Photon..

Not sure if this is "just" an Eclipse bug, or something (too) fancy that Immutables.org is doing re. APT?

Note that in order to use Immutables APT with m2e in Eclipse, one needs the latest bleeding edge m2e-apt, see https://github.com/jbosstools/m2e-apt/issues/61. I'm guessing, but am not 100% sure, that this would probably also occur without m2e-apt or Maven and M2E at all, [if one manually configured Eclipse](https://immutables.github.io/apt.html)... unless this is some problem in m2e-apt... but I doubt it, as all that really does is just set the Preferences > Java Compiler > Annotation Processing > Factory Path.

```
java.lang.RuntimeException: java.lang.ClassCastException: org.immutables.value.internal.$processor$.$Processor cannot be cast to javax.annotation.processing.Processor
	at org.immutables.processor.ProxyProcessor.createClassLoaderDelegate(ProxyProcessor.java:97)
	at org.immutables.processor.ProxyProcessor.<init>(ProxyProcessor.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at org.eclipse.jdt.apt.core.internal.ClassServiceFactory.newInstance(ClassServiceFactory.java:27)
	at org.eclipse.jdt.internal.apt.pluggable.core.dispatch.IdeAnnotationProcessorManager.discoverNextProcessor(IdeAnnotationProcessorManager.java:93)
	at org.eclipse.jdt.internal.compiler.apt.dispatch.RoundDispatcher.round(RoundDispatcher.java:116)
	at org.eclipse.jdt.internal.compiler.apt.dispatch.BaseAnnotationProcessorManager.processAnnotations(BaseAnnotationProcessorManager.java:159)
	at org.eclipse.jdt.internal.apt.pluggable.core.dispatch.IdeAnnotationProcessorManager.processAnnotations(IdeAnnotationProcessorManager.java:135)
	at org.eclipse.jdt.internal.compiler.Compiler.processAnnotations(Compiler.java:933)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:443)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:419)
	at org.eclipse.jdt.internal.core.builder.AbstractImageBuilder.compile(AbstractImageBuilder.java:372)
	at org.eclipse.jdt.internal.core.builder.BatchImageBuilder.compile(BatchImageBuilder.java:187)
	at org.eclipse.jdt.internal.core.builder.AbstractImageBuilder.compile(AbstractImageBuilder.java:304)
	at org.eclipse.jdt.internal.core.builder.BatchImageBuilder.build(BatchImageBuilder.java:61)
	at org.eclipse.jdt.internal.core.builder.JavaBuilder.buildAll(JavaBuilder.java:256)
	at org.eclipse.jdt.internal.core.builder.JavaBuilder.build(JavaBuilder.java:175)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:744)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:301)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:304)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:360)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:383)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:142)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:232)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
Caused by: java.lang.ClassCastException: org.immutables.value.internal.$processor$.$Processor cannot be cast to javax.annotation.processing.Processor
	at org.immutables.processor.ProxyProcessor.createClassLoaderDelegate(ProxyProcessor.java:95)
	... 32 more
```

**Comment by vorburger** [comment]
Wait a second... I'm also using error-prone on the same project where this is happening, and that seems to be what is causing this problem - if I remove error-prone from the POM, then this does not happen anymore. A closer look at said Preferences > Java Compiler > Annotation Processing > Factory Path shows this, which look like all of error-prone and its dependencies, plus probably Immutables somewhere (can't see it), that doesn't seem right:

![immutables-bug745](https://user-images.githubusercontent.com/298598/35253342-298473ba-ffe5-11e7-8316-41ff09f025fa.png)

I suspect that this probably isn't Immutable.org's "fault" and there isn't much that can be done about this here, so will follow-up on m2e-apt side. Let me therefore close this here again immediately, for now.

**Comment by elucash** [comment]
Hi Michael, thank you for reporting this! Obviously, `$Processor` implements annotation processor interface, but the CCE, probably, comes from the fact that the interface was loaded from the incompatible classloader. `ProxyProcessors` job is to create special classloader wrapping for Immutables annotation processor to be able to access Eclipse`s internal structures to inspect to compensate for various compiler bugs and Eclipse/Javac discrepancies. The open question is how exactly error_prone might intervein with eclipse classloaders. Also, this behavior (upcasting eclipse classes) should be best effort behavior, so there's potential we can improve. Please, feel free to report any surrounding issues, it might give more info/context.

**Comment by vorburger** [comment]
@elucash thanks for feedback. More details in https://github.com/jbosstools/m2e-apt/issues/62 and work-around / solution FYI in https://git.opendaylight.org/gerrit/#/c/67537/. Not really Immutables' fault, so forget about it.. and thanks again for all your work on Immutables!!

**Comment by Stephan202** [comment]
I hit this same issue and can confirm that @vorburger's "profile trick" works. In our project a simpler change also worked: explicitly declare Immutables on the annotation processor classpath (relevant related issue: #750). I.e.:
```xml
...
<properties>
    <immutables.version>2.5.6</immutables.version>
</properties>
...
<dependencies>
    ...
    <dependency>
        <groupId>org.immutables</groupId>
        <artifactId>value</artifactId>
        <version>${immutables.version}</version>
        <classifier>annotations</classifier>
        <scope>provided</scope>
    </dependency>
    ...
</dependencies>
...
<build>
    <plugins>
        <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-compiler-plugin</artifactId>
            <version>3.7.0</version>
            <configuration>
                <annotationProcessorPaths>
                    <path>
                        <groupId>org.immutables</groupId>
                        <artifactId>value</artifactId> <!-- Or `value-processor` if shading isn't necessary. -->
                        <version>${immutables.version}</version>
                    </path>
                </annotationProcessorPaths>
            </configuration>
        </plugin>
    </plugins>
</build>
...
```

**Comment by wordlessly** [comment]
Just wanted to follow the "Getting Started" part. Downloaded the latest version of Eclipse: Version: 2019-03 M2 (4.11.0 M2)

Does not work.

> org.immutables.value.internal.$processor$.$Processor threw java.lang.ClassCastException: org.immutables.value.internal.$processor$.meta.$CachingElements$CachingTypeElement cannot be cast to org.eclipse.jdt.internal.compiler.apt.model.IElementInfo
	at org.eclipse.jdt.internal.apt.pluggable.core.dispatch.IdeProcessingEnvImpl.getEnclosingIFile(IdeProcessingEnvImpl.java:147)
	at org.eclipse.jdt.internal.apt.pluggable.core.filer.IdeFilerImpl.createSourceFile(IdeFilerImpl.java:186)
	at org.immutables.value.internal.$generator$.$Output$SourceFile.complete($Output.java:313)
	at org.immutables.value.internal.$generator$.$Output$7.invoke($Output.java:177)
	at org.immutables.value.internal.$generator$.$Intrinsics.$($Intrinsics.java:96)
	at org.immutables.value.internal.$processor$.$Generator_Immutables._t0__generate($Generator_Immutables.java:20)
	at org.immutables.value.internal.$processor$.$Generator_Immutables$FragmentDispatch.run($Generator_Immutables.java:19603)
	at org.immutables.value.internal.$generator$.$Templates$Fragment.invoke($Templates.java:248)
	at org.immutables.value.internal.$generator$.$AbstractGenerator.invoke($AbstractGenerator.java:57)
	at org.immutables.value.internal.$processor$.$Processor.process($Processor.java:77)
	at org.immutables.value.internal.$generator$.$AbstractGenerator.process($AbstractGenerator.java:87)
	at org.immutables.processor.ProxyProcessor.process(ProxyProcessor.java:72)
	at org.eclipse.jdt.internal.compiler.apt.dispatch.RoundDispatcher.handleProcessor(RoundDispatcher.java:142)
	at org.eclipse.jdt.internal.compiler.apt.dispatch.RoundDispatcher.round(RoundDispatcher.java:124)
	at org.eclipse.jdt.internal.compiler.apt.dispatch.BaseAnnotationProcessorManager.processAnnotations(BaseAnnotationProcessorManager.java:171)
	at org.eclipse.jdt.internal.apt.pluggable.core.dispatch.IdeAnnotationProcessorManager.processAnnotations(IdeAnnotationProcessorManager.java:138)
	at org.eclipse.jdt.internal.compiler.Compiler.processAnnotations(Compiler.java:940)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:450)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:426)
	at org.eclipse.jdt.internal.core.builder.AbstractImageBuilder.compile(AbstractImageBuilder.java:386)
	at org.eclipse.jdt.internal.core.builder.BatchImageBuilder.compile(BatchImageBuilder.java:214)
	at org.eclipse.jdt.internal.core.builder.AbstractImageBuilder.compile(AbstractImageBuilder.java:318)
	at org.eclipse.jdt.internal.core.builder.BatchImageBuilder.build(BatchImageBuilder.java:79)
	at org.eclipse.jdt.internal.core.builder.JavaBuilder.buildAll(JavaBuilder.java:264)
	at org.eclipse.jdt.internal.core.builder.JavaBuilder.build(JavaBuilder.java:182)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:833)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:220)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:263)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:316)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:319)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:371)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:392)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:154)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:244)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
