### ISSUE TITLE
Nested Immutables with @JsonUnwrapped doesn't work past one level of nesting.

### ISSUE THREAD

**Issue by matt-isaman** [immutables/immutables#747]
After getting the response to #693 I decided to try solving the issue I was having via a combination of stand alone types and Jackson annotations to get the desired serialized form.

Toying around with non-Immutable objects I ended up with this:
```java
package com.fu;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonUnwrapped;
import com.fasterxml.jackson.databind.ObjectMapper;

import org.apache.commons.lang3.builder.ToStringBuilder;
import org.apache.commons.lang3.builder.ToStringStyle;

public final class Fu {

    @JsonProperty("f")
    final String  fu  = "fu";

    @JsonUnwrapped(prefix = "bar")
    final Bar bar = new Bar();

    @Override
    public String toString() {
        return ToStringBuilder.reflectionToString(this, ToStringStyle.JSON_STYLE);
    }

    public static final class Bar {

        @JsonProperty("B")
        final String  bar = "bar";

        @JsonUnwrapped(prefix = "baz")
        final Baz baz = new Baz();

        @Override
        public String toString() {
            return ToStringBuilder.reflectionToString(this, ToStringStyle.JSON_STYLE);
        }
    }

    public static final class Baz {

        @JsonProperty("B")
        final String baz = "baz";

        @Override
        public String toString() {
            return ToStringBuilder.reflectionToString(this, ToStringStyle.JSON_STYLE);
        }
    }

    public static void main(String... args) throws Exception {
        final ObjectMapper mapper = new ObjectMapper();

        final Fu f0 = new Fu();
        System.out.println(f0);
        final String j = mapper.writeValueAsString(f0);
        System.out.println(j);
        final Fu f1 = mapper.readValue(j, Fu.class);
        System.out.println(f1);
    }
}
```
When I run the `main` method I end up with this output:
```
{"fu":"fu","bar":{"bar":"bar","baz":{"baz":"baz"}}}
{"bazB":"baz","barB":"bar","f":"fu"}
{"fu":"fu","bar":{"bar":"bar","baz":{"baz":"baz"}}}
```
Which is precisely the result I expect and need.

I then converted this to use the Immutables library like so:
```java
package com.foo;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonUnwrapped;
import com.fasterxml.jackson.databind.ObjectMapper;

import org.apache.commons.lang3.builder.ToStringBuilder;
import org.apache.commons.lang3.builder.ToStringStyle;
import org.immutables.value.Value.Immutable;
import org.immutables.value.Value.Style;

@Immutable(builder = false)
@Style(deepImmutablesDetection = true, privateNoargConstructor = true, allParameters = true)
public abstract class Foo {

    @JsonProperty("f")
    public abstract String foo();

    @JsonUnwrapped(prefix = "bar")
    public abstract Bar bar();

    @Override
    public String toString() {
        return ToStringBuilder.reflectionToString(this, ToStringStyle.JSON_STYLE);
    }

    @Immutable(builder = false)
    @Style(deepImmutablesDetection = true, privateNoargConstructor = true, allParameters = true)
    public static abstract class Bar {

        @JsonProperty("B")
        public abstract String bar();

        @JsonUnwrapped(prefix = "baz")
        public abstract Baz baz();

        @Override
        public String toString() {
            return ToStringBuilder.reflectionToString(this, ToStringStyle.JSON_STYLE);
        }
    }

    @Immutable(builder = false)
    @Style(deepImmutablesDetection = true, privateNoargConstructor = true, allParameters = true)
    public static abstract class Baz {

        @JsonProperty("B")
        public abstract String baz();

        @Override
        public String toString() {
            return ToStringBuilder.reflectionToString(this, ToStringStyle.JSON_STYLE);
        }
    }

    public static void main(String... args) throws Exception {
        final ObjectMapper mapper = new ObjectMapper();

        final ImmutableFoo f0 = ImmutableFoo.of("foo", ImmutableBar.of("bar", ImmutableBaz.of("baz")));
        System.out.println(f0);
        final String j = mapper.writeValueAsString(f0);
        System.out.println(j);
        final ImmutableFoo f1 = mapper.readValue(j, ImmutableFoo.class);
        System.out.println(f1);
    }
}
```
When I run the `main` method I end up with this output:
```
{"foo":"foo","bar":{"bar":"bar","baz":{"baz":"baz"}}}
{"bazB":"baz","barB":"bar","f":"foo"}
Exception in thread "main" java.lang.NullPointerException
	at com.foo.ImmutableBaz.hashCode(ImmutableBaz.java:78)
	at com.foo.ImmutableBar.hashCode(ImmutableBar.java:104)
	at java.util.WeakHashMap.hash(WeakHashMap.java:298)
	at java.util.WeakHashMap.put(WeakHashMap.java:449)
	at org.apache.commons.lang3.builder.ToStringStyle.register(ToStringStyle.java:221)
	at org.apache.commons.lang3.builder.ToStringStyle.appendInternal(ToStringStyle.java:506)
	at org.apache.commons.lang3.builder.ToStringStyle.append(ToStringStyle.java:474)
	at org.apache.commons.lang3.builder.ToStringStyle$JsonToStringStyle.append(ToStringStyle.java:2557)
	at org.apache.commons.lang3.builder.ToStringBuilder.append(ToStringBuilder.java:846)
	at org.apache.commons.lang3.builder.ReflectionToStringBuilder.appendFieldsIn(ReflectionToStringBuilder.java:642)
	at org.apache.commons.lang3.builder.ReflectionToStringBuilder.toString(ReflectionToStringBuilder.java:829)
	at org.apache.commons.lang3.builder.ReflectionToStringBuilder.toString(ReflectionToStringBuilder.java:301)
	at org.apache.commons.lang3.builder.ReflectionToStringBuilder.toString(ReflectionToStringBuilder.java:158)
	at org.apache.commons.lang3.builder.ToStringBuilder.reflectionToString(ToStringBuilder.java:163)
	at com.foo.Foo.toString(Foo.java:30)
	at java.lang.String.valueOf(String.java:2994)
	at java.io.PrintStream.println(PrintStream.java:821)
	at com.foo.Foo.main(Foo.java:71)
```
It turns out that the `baz` property was not being set and was `null` which caused the NPE. Just to confirm things and get a non-error result I updated the Baz object to:
```java
...
@JsonProperty("B")
@Nullable
public abstract String baz();
...
```
Which resulted in this output when I re-ran `main`:
```
{"foo":"foo","bar":{"bar":"bar","baz":{"baz":"baz"}}}
{"bazB":"baz","barB":"bar","f":"foo"}
{"foo":"foo","bar":{"bar":"bar","baz":{"baz":null}}}
```
I then wanted to check on whether or not this was a level of nesting issue. So I removed the `Baz` class from the `Bar` class. Re-running `main` resulted in this:
```
{"foo":"foo","bar":{"bar":"bar"}}
{"barB":"bar","f":"foo"}
{"foo":"foo","bar":{"bar":"bar"}}
```
So it seems that a single nested structure of Immutables based objects and JsonUnwrapped works, but adding another layer breaks. I tried adding `additionalJsonAnnotations = { JsonUnwrapped.class }` to the Style annotation just in case that mattered but nothing changed. Also just in case there was an issue related to the classes being declared as member classes of `Foo` I pulled `Bar` and `Baz` out into their own files and re-ran `main` which still resulted in a `null` `baz` field.

I am using immutables 2.5.5:
```groovy
apt(
  'org.immutables:value:2.5.5', // https://immutables.github.io
)

compileOnly(
  'org.immutables:value:2.5.5:annotations', // https://immutables.github.io
)
```

**Comment by elucash** [comment]
Tried this back and forth with different mechanism immutables have like (`@JsonDeserialize(as = ImmutableFoo.class)` or `@JsonDeserialize(builder = ImmutableFoo.Builder.class)`). It has a problem recognizing the "double embedded" pattern even with somewhat tweaked annotations. I consider that a lot of mapping in Jackson are bean/POJO centric and the inherently wrong way to use Immutables is to create non-direct mappings to JSON. It's always better to have 1:1 (or so) correspondence for message objects, and avoid any complex embedding/flattening/lifting/wrapping as those will backfire in different places also.
