### ISSUE TITLE
Race condition in StaticEnvironment

### ISSUE THREAD

**Issue by k21** [immutables/immutables#77]
The following exception sometimes randomly shows up when we use Buck to build code that uses the Immutables library:

    java.lang.IllegalStateException: Static environment should be initialized
        at org.immutables.value.internal.google.common.base.Preconditions.checkState(Preconditions.java:173)
        at org.immutables.value.internal.generator.StaticEnvironment.checkInitialized(StaticEnvironment.java:69)
        at org.immutables.value.internal.generator.StaticEnvironment.getInstance(StaticEnvironment.java:43)
        at org.immutables.value.internal.generator.Output.getFiles(Output.java:245)
        at org.immutables.value.internal.generator.Output.access$000(Output.java:43)
        at org.immutables.value.internal.generator.Output$3.invoke(Output.java:84)
        at org.immutables.value.internal.generator.Intrinsics.$(Intrinsics.java:91)
        at org.immutables.value.internal.processor.Generator_Immutables$1.run(Generator_Immutables.java:20)
        at org.immutables.value.internal.generator.Templates$Fragment.invoke(Templates.java:274)
        at org.immutables.value.internal.generator.AbstractGenerator.invoke(AbstractGenerator.java:60)
        at org.immutables.value.internal.processor.Processor.process(Processor.java:45)
        at org.immutables.value.internal.generator.AbstractGenerator.process(AbstractGenerator.java:90)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:793)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:722)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1700(JavacProcessingEnvironment.java:97)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1029)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1163)
        at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1108)
        at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:824)
        at com.sun.tools.javac.main.Main.compile(Main.java:439)
        at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:132)

It looks like the issue is caused by the `StaticEnvironment` class assuming that there will only be a single instance of the generator at any time, while we are creating and running multiple instances concurrently in a single process [using JSR199 to call the Java compiler in-process](https://github.com/facebook/buck/blob/4528b366500ce64b4295c23f45bf6eed13365b11/src/com/facebook/buck/java/JavacInMemoryStep.java#L179).

cc @coneko

**Comment by elucash** [comment]
Thanks! I guess this place should be thoroughtly revised. I'll be back after investigation.

**Comment by elucash** [comment]
I release version 1.1.2 with a quick-fix, available on Central. Can you try to reproduce this with 1.1.2?

**Comment by k21** [comment]
Thanks a lot! I will try to reproduce the issue and get back to you by tomorrow.

**Comment by k21** [comment]
Unfortunately I am not able to reproduce the error with version 1.1.1 anymore, so it's hard to tell whether this has fixed the issue. But I didn't see the issue happening with 1.1.2 yet, so I am closing this for now. Thanks again for your help!
