### ISSUE TITLE
Annotation processing error when processing classes with Bean Validation annotations

### ISSUE THREAD

**Issue by SimY4** [immutables/immutables#798]
After updating to 2.6.x version of immutables this class here:
```
@Value.Immutable(copy = false)
@JsonSerialize(as = ImmutableEntity.class)
@JsonDeserialize(as = ImmutableEntity.class)
public interface Entity {

    @javax.validation.constraints.NotNull
    @Value.Parameter
    @JsonProperty
    String getSlug();

}
```
resolves in this error during project compilation: 
```
[ERROR] org.immutables.value.internal.$processor$.$Processor threw java.lang.IllegalArgumentException: Cannot parse type from input string '(@javax.validation.constraints.NotNull :: java.lang.String)'. unexpected term '('
[ERROR] at org.immutables.value.internal.$processor$.encode.$Type$Parser$1Reader.type($Type.java:767)
[ERROR] at org.immutables.value.internal.$processor$.encode.$Type$Parser.doParse($Type.java:891)
[ERROR] at org.immutables.value.internal.$processor$.encode.$Type$Parser.parse($Type.java:715)
[ERROR] at org.immutables.value.internal.$processor$.meta.$FromSupertypesModel.isEligibleFromType($FromSupertypesModel.java:137)
[ERROR] at org.immutables.value.internal.$processor$.meta.$FromSupertypesModel.<init>($FromSupertypesModel.java:78)
[ERROR] at org.immutables.value.internal.$processor$.meta.$ValueType.getBuildFromTypes($ValueType.java:1358)
[ERROR] at org.immutables.value.internal.$processor$.$Generator_Immutables._t18__generateBuilder($Generator_Immutables.java:5008)
[ERROR] at org.immutables.value.internal.$processor$.$Generator_Immutables$FragmentDispatch.run($Generator_Immutables.java:19510)
[ERROR] at org.immutables.value.internal.$generator$.$Templates$Fragment.invoke($Templates.java:248)
[ERROR] at org.immutables.value.internal.$generator$.$Intrinsics.$($Intrinsics.java:96)
[ERROR] at org.immutables.value.internal.$processor$.$Generator_Immutables._t4__generateImmutable($Generator_Immutables.java:601)
[ERROR] at org.immutables.value.internal.$processor$.$Generator_Immutables$FragmentDispatch.run($Generator_Immutables.java:19496)
[ERROR] at org.immutables.value.internal.$generator$.$Templates$Fragment.invoke($Templates.java:248)
[ERROR] at org.immutables.value.internal.$generator$.$Intrinsics.$($Intrinsics.java:96)
[ERROR] at org.immutables.value.internal.$processor$.$Generator_Immutables$1.run($Generator_Immutables.java:23)
[ERROR] at org.immutables.value.internal.$generator$.$Templates$Fragment.invoke($Templates.java:248)
[ERROR] at org.immutables.value.internal.$generator$.$Output$7.invoke($Output.java:174)
[ERROR] at org.immutables.value.internal.$generator$.$Intrinsics.$($Intrinsics.java:96)
[ERROR] at org.immutables.value.internal.$processor$.$Generator_Immutables._t0__generate($Generator_Immutables.java:20)
[ERROR] at org.immutables.value.internal.$processor$.$Generator_Immutables$FragmentDispatch.run($Generator_Immutables.java:19492)
[ERROR] at org.immutables.value.internal.$generator$.$Templates$Fragment.invoke($Templates.java:248)
[ERROR] at org.immutables.value.internal.$generator$.$AbstractGenerator.invoke($AbstractGenerator.java:57)
[ERROR] at org.immutables.value.internal.$processor$.$Processor.process($Processor.java:63)
[ERROR] at org.immutables.value.internal.$generator$.$AbstractGenerator.process($AbstractGenerator.java:87)
[ERROR] at org.immutables.processor.ProxyProcessor.process(ProxyProcessor.java:72)
```
If I remove Bean Validation constraint annotation this class will be generated fine.

I get the same issue if immutables is defined as abstract class.

I'm using latest java 1.8_172 and maven 3.5.0 to reproduce this issue.

**Comment by SimY4** [comment]
I was fixed in 2.6.3
