### ISSUE TITLE
EnumMap and empty Map<Enum,?> throws exception

### ISSUE THREAD

**Issue by arakelian** [immutables/immutables#821]
Immutables will fail to create a bean which has a property of type Map<Enum,?> that is empty.

This code will reproduce the problem:

```
import java.util.Map;

import org.immutables.value.Value;

import com.google.common.collect.ImmutableMap;

public class TestMe {
	@Value.Immutable
	public static class Bean {
		public enum Gender {
			MALE, FEMALE
		};

		@Value.Default
		public Map<Gender, String> getGenderNames() {
			return ImmutableMap.of();
		}
	}

	public static void main(String[] args) {
		ImmutableBean.builder().build();
	}
}
```

The exception throw at runtime is:

```
Exception in thread "main" java.lang.IllegalArgumentException: Specified map is empty
	at java.util.EnumMap.<init>(EnumMap.java:177)
	at ImmutableBean.createUnmodifiableEnumMap(ImmutableBean.java:231)
	at ImmutableBean.<init>(ImmutableBean.java:34)
	at ImmutableBean.<init>(ImmutableBean.java:31)
	at ImmutableBean$Builder.build(ImmutableBean.java:222)
	at TestMe.main(TestMe.java:23)
```

**Comment by arakelian** [comment]
@elucash Thank you for Immutables. Love it!
