### ISSUE TITLE
MongoDB 4.0 Support

### ISSUE THREAD

**Issue by arouel** [immutables/immutables#830]
Are there any plans to support MongoDB 4.0? We would have to update the Java driver to version 3.8.x according to the [compatibilty table](https://docs.mongodb.com/ecosystem/drivers/driver-compatibility-reference/#java-driver-compatibility).

When updating the driver version in the `pom.xml` we get the following error:
```
java.lang.NullPointerException
	at com.mongodb.Mongo.createOperationExecutor(Mongo.java:790)
	at com.mongodb.MongoClient.createListDatabasesIterable(MongoClient.java:521)
	at com.mongodb.MongoClient.createListDatabaseNamesIterable(MongoClient.java:462)
	at com.mongodb.MongoClient.listDatabaseNames(MongoClient.java:444)
	at org.immutables.mongo.fixture.MongoContext.<init>(MongoContext.java:75)
	at org.immutables.mongo.fixture.MongoContext.create(MongoContext.java:132)
	at org.immutables.mongo.fixture.SimpleUpdaterTest.<init>(SimpleUpdaterTest.java:31)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.junit.runners.BlockJUnit4ClassRunner.createTest(BlockJUnit4ClassRunner.java:195)
	at org.junit.runners.BlockJUnit4ClassRunner$1.runReflectiveCall(BlockJUnit4ClassRunner.java:244)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.BlockJUnit4ClassRunner.methodBlock(BlockJUnit4ClassRunner.java:241)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
```

**Comment by asereda-gs** [comment]
We have changed our mongo integration testing to use [mongo-java-server](https://github.com/bwaldvogel/mongo-java-server) current mongo java driver for immutables is 3.10

Also all tests are passing with 4.x
