### ISSUE TITLE
JSON Deserialize - Could not find a suitable constructor 

### ISSUE THREAD

**Issue by johno1985** [immutables/immutables#841]
I am using the following versions:
Jackson - 2.8.10
Immutables - 2.5.6

My immutable object is defined as followed:

```
package com.myorg.model;

import org.immutables.value.Value;

import com.fasterxml.jackson.databind.annotation.JsonDeserialize;

@Value.Immutable
@Value.Style(privateNoargConstructor = true, builder = "new")
@JsonDeserialize(builder = ImmutableValidateInventoryRequest.Builder.class)
public interface ValidateInventoryRequest {
	String clientId();

	String clientSecret();

	String inventoryKey();
}
```

When I attempt to deserialize, I get the following error:

```
java.lang.NoSuchMethodException: Could not find a suitable constructor in com.myorg.ValidateInventoryRequest class.
        at org.glassfish.jersey.inject.hk2.JerseyClassAnalyzer.getConstructor(JerseyClassAnalyzer.java:192) ~[jersey-hk2-2.27.jar:?]
        at org.jvnet.hk2.internal.Utilities.getConstructor(Utilities.java:180) ~[hk2-locator-2.5.0-b42.jar:?]
        at org.jvnet.hk2.internal.ClazzCreator.initialize(ClazzCreator.java:129) ~[hk2-locator-2.5.0-b42.jar:?]
        at org.jvnet.hk2.internal.ClazzCreator.initialize(ClazzCreator.java:180) ~[hk2-locator-2.5.0-b42.jar:?]
        at org.jvnet.hk2.internal.SystemDescriptor.internalReify(SystemDescriptor.java:740) ~[hk2-locator-2.5.0-b42.jar:?]
        at org.jvnet.hk2.internal.SystemDescriptor.reify(SystemDescriptor.java:694) ~[hk2-locator-2.5.0-b42.jar:?]
        at org.jvnet.hk2.internal.ServiceLocatorImpl.reifyDescriptor(ServiceLocatorImpl.java:464) ~[hk2-locator-2.5.0-b42.jar:?]
        ... 45 more
```

Please can someone point out what I am doing wrong?

**Comment by johno1985** [comment]
Apologies, I was being stupid, I was trying to marshal the JSON into a Jersey Bean object!
