### ISSUE TITLE
NPE in TypeAdaptersMirror constructor in 6da80f47

### ISSUE THREAD

**Issue by bgertzfield** [immutables/immutables#90]
I updated from 1.1.2 release to the latest snapshot 6da80f475c532dc17eadf9f667f6465a4d3cd1fb today and built the latest snapshot using javac 1.8.0_40 with `mvn package`.

I now get an NPE in `TypeAdaptersMirror` when running the annotation processor on a simple interface:

```
% cat Foo.java
import org.immutables.value.Value;

@Value.Immutable
public interface Foo {
  int bar();
}

% javac -cp third-party/java/immutables/value-1.1.2.jar -processorpath third-party/java/immutables/value-standalone-1.1.2.jar -proc:only -s build/foo Foo.java 
```

(works)

```
% javac -cp third-party/java/immutables/value-2.0-SNAPSHOT.jar -processorpath third-party/java/immutables/value-standalone-2.0-SNAPSHOT.jar -proc:only -s build/foo Foo.java              
error: org.immutables.value.internal.$processor$.$Processor threw java.lang.NullPointerException
  	at org.immutables.value.internal.$processor$.meta.$TypeAdaptersMirror.<init>($TypeAdaptersMirror.java:108)
  	at org.immutables.value.internal.$processor$.meta.$TypeAdaptersMirror.from($TypeAdaptersMirror.java:91)
  	at org.immutables.value.internal.$processor$.meta.$Proto$Environment.defaultTypeAdapters($Proto.java:114)
  	at org.immutables.value.internal.$processor$.meta.$ImmutableProto$Environment.<init>($ImmutableProto.java:1117)
  	at org.immutables.value.internal.$processor$.meta.$ImmutableProto$Environment.of($ImmutableProto.java:1270)
  	at org.immutables.value.internal.$processor$.meta.$Round.environment($Round.java:71)
  	at org.immutables.value.internal.$processor$.meta.$ImmutableRound.environment($ImmutableRound.java:293)
  	at org.immutables.value.internal.$processor$.meta.$Round$ProtoclassCollecter.collectIncludedAndDefinedBy($Round.java:200)
  	at org.immutables.value.internal.$processor$.meta.$Round$ProtoclassCollecter.collect($Round.java:148)
  	at org.immutables.value.internal.$processor$.meta.$Round.collectProtoclasses($Round.java:127)
  	at org.immutables.value.internal.$processor$.meta.$Round.collectValues($Round.java:75)
  	at org.immutables.value.internal.$processor$.$Processor.process($Processor.java:43)
  	at org.immutables.value.internal.$generator$.$AbstractGenerator.process($AbstractGenerator.java:89)
  	at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:794)
  	at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:705)
  	at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)
  	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1035)
  	at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1176)
  	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
  	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:856)
  	at com.sun.tools.javac.main.Main.compile(Main.java:523)
  	at com.sun.tools.javac.main.Main.compile(Main.java:381)
  	at com.sun.tools.javac.main.Main.compile(Main.java:370)
  	at com.sun.tools.javac.main.Main.compile(Main.java:361)
  	at com.sun.tools.javac.Main.compile(Main.java:56)
  	at com.sun.tools.javac.Main.main(Main.java:42)
1 error
```

Here's a more verbose log:

https://gist.github.com/bgertzfield/9fee96fcdc125d00940b

**Comment by elucash** [comment]
Hi Ben, thank you for the report, staying on the cutting edge of development and trying snapshots!
Runtime dependency on optional jar has crept in. Please, try newer snapshot, it should be fixed now.

**Comment by bgertzfield** [comment]
Looks good, thanks.

Has `Value.Nested` changed to `Value.Enclosing`, by the way? It appears 83eadf5a8ca9285cd14eb39f5e84dd909b2c9443 got rid of it—is the plan to bring it back, or is it gone?

**Comment by elucash** [comment]
Yeah, `Value.Nested` was renamed to `Value.Enclosing`. There's couple of other API changes in 2.0, but they are not drastic (yet breaking, so major version increment).
See #74 as explanation. I can't wait to release an RC and update documentation site.
