### ISSUE TITLE
Referring to generated classes in specification interfaces: Null Pointer Exception during project clean on Eclipse.

### ISSUE THREAD

**Issue by joe-thurbon** [immutables/immutables#961]
We are trying Immutables, and definitely want to use it. It's working well in both Gradle and Eclipse, but we have one issue which manifests as a NPE on a project clean inside eclipse (and have no issues in gradle). The stack trace is included at the bottom of this issue.

We have identified a possible cause as when we have two specification interfaces, one of which refers to the generated class of the other. We're not sure whether this should be possible or not (it's certainly useful to us, but as new users we don't know it it's an anti-pattern).

Here's an example
```
@Immutable
public interface Container
{
    public ImmutableContents getContents();
}

@Immutable
public interface Contents
{
    public Integer getSomeContentSpecificThing();
}
```
It appears that you may need a couple of other classes in the same package to coerce the exception during a clean-and-build, and given the NPE below, it appears that the processor has trouble working out which order to process things.

In the interim, we're just using the specifying interfaces directly, but then needing to use the from() methods to get access to the fluent withX methods seems a little less parsimonious than the rest of the library, which seems excellent thus far.

We'd love to get a read on this from people more experienced with the library.

```
org.immutables.value.internal.$processor$.$Processor threw java.lang.NullPointerException
	at org.immutables.value.internal.$generator$.$SourceOrdering$1CollectedOrdering.compare($SourceOrdering.java:260)
	at org.immutables.value.internal.$generator$.$SourceOrdering$1CollectedOrdering.compare($SourceOrdering.java:183)
	at java.util.TimSort.countRunAndMakeAscending(TimSort.java:351)
	at java.util.TimSort.sort(TimSort.java:216)
	at java.util.Arrays.sort(Arrays.java:1438)
	at org.immutables.value.internal.$guava$.collect.$Ordering.immutableSortedCopy($Ordering.java:888)
	at org.immutables.value.internal.$generator$.$SourceOrdering.getAllAccessorsProvider($SourceOrdering.java:268)
	at org.immutables.value.internal.$processor$.meta.$AccessorAttributesCollector.collectGeneratedCandidateMethods($AccessorAttributesCollector.java:108)
	at org.immutables.value.internal.$processor$.meta.$AccessorAttributesCollector.collect($AccessorAttributesCollector.java:78)
	at org.immutables.value.internal.$processor$.meta.$ValueTypeComposer.compose($ValueTypeComposer.java:65)
	at org.immutables.value.internal.$processor$.meta.$Round.composeValue($Round.java:181)
	at org.immutables.value.internal.$processor$.meta.$Round.collectValues($Round.java:95)
	at org.immutables.value.internal.$processor$.$Processor.process($Processor.java:72)
	at org.immutables.value.internal.$generator$.$AbstractGenerator.process($AbstractGenerator.java:87)
	at org.immutables.processor.ProxyProcessor.process(ProxyProcessor.java:72)
	at org.eclipse.jdt.internal.compiler.apt.dispatch.RoundDispatcher.handleProcessor(RoundDispatcher.java:142)
	at org.eclipse.jdt.internal.compiler.apt.dispatch.RoundDispatcher.round(RoundDispatcher.java:124)
	at org.eclipse.jdt.internal.compiler.apt.dispatch.BaseAnnotationProcessorManager.processAnnotations(BaseAnnotationProcessorManager.java:171)
	at org.eclipse.jdt.internal.apt.pluggable.core.dispatch.IdeAnnotationProcessorManager.processAnnotations(IdeAnnotationProcessorManager.java:138)
	at org.eclipse.jdt.internal.compiler.Compiler.processAnnotations(Compiler.java:940)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:450)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:426)
	at org.eclipse.jdt.internal.core.builder.AbstractImageBuilder.compile(AbstractImageBuilder.java:386)
	at org.eclipse.jdt.internal.core.builder.BatchImageBuilder.compile(BatchImageBuilder.java:214)
	at org.eclipse.jdt.internal.core.builder.AbstractImageBuilder.compile(AbstractImageBuilder.java:318)
	at org.eclipse.jdt.internal.core.builder.BatchImageBuilder.build(BatchImageBuilder.java:79)
	at org.eclipse.jdt.internal.core.builder.JavaBuilder.buildAll(JavaBuilder.java:262)
	at org.eclipse.jdt.internal.core.builder.JavaBuilder.build(JavaBuilder.java:180)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:833)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:220)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:263)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:316)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:319)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:371)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:392)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:154)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:244)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by elucash** [comment]
Thank you for reporting this! On one hand, this should be fixed (we probably had this fixed at some point, but after some recent changes it might have regressed. It will take some time to precisely fix it, or at least make sure that NPE fix would not cause other problems.

Having said that in theory (and in practice for many users of Immutables) using yet-to-be-generated classes should generally work (due to many arcane workarounds around compiler inconsistencies we implemented over years), I would still recommend you to try to limit yet-to-be-generated types usage: the downside of using such types are not only spurious bugs like this one, but also compilation becomes more fragile like having many "unknown symbol" errors caused by other unrelated errors.

There many creative ways to use immutables with styles (http://immutables.github.io/style.html).
I'll focus here on one of the patterns I use myself really often is "sandwich" style, it's illustrated at the top of the readme file (the guide have many similar examples, but not necessary in that combination)

```java
// Define abstract value type using interface, abstract class or annotation
@Value.Immutable
public interface ValueObject extend WithValueObject {
  // extend not-yet-generated WithValueObject to inherit `with*` method signatures
  String getName();
  List<Integer> getCounts();
  Optional<String> getDescription();

  class Builder extends ImmutableValueObject.Builder {}
  // ImmutableValueObject.Builder will be generated and
  // our builder will inherit and reexport methods as it's own
}

// Use generated immutable implementation and builder
ValueObject v =
    new ValueObject.Builder()
        .name("Nameless")
        .description("present")
        .addCounts(1)
        .addCounts(2)
        .build();

v = v.withName("Doe");
```

In this way, you can freely use abstract value type in almost all contexts, especially in signatures of methods and fields of other types using it, narrowing the amount or even eliminating direct usages of generated `ImmutableValueObject`.
In particular implementing `With*` interface (to be generated by the fact of using it) covers the issue with having `with` methods accessible.  This can be used without inner "extending" Builder class, many way how to use it!

**Comment by joe-thurbon** [comment]
Thanks heaps for the pointers. Just checking - is it @Style.typeWith that makes those WithValueObject style interfaces?

Looking really forward to seeing the bug fix :)

**Comment by elucash** [comment]
these `WithValueObject` are generated automatically when you trying to extend it, like you type it while it doesn't exist, then recompile and it will appear generated in the package. `@Style.typeWith` only allows you to customize name pattern by which this special interface is recognized and generated: for example, when `@Style(typeWith = "CopyWith*")` you would write `public interface ValueObject extend CopyWithValueObject {`.

**Comment by billccn** [comment]
Through debugging I think I found the bug:

The `SourceOrdering.getAllAccessorsProvider(...).CollectedOrdering.toElement()` method only accepts `getKind()=DECLARED` types and not the `ERROR` kind (i.e. `ErrorType` which is a sub-type of `DeclaredType`).

In my case, `ERROR` would be returned when the `TypeElement` (circularly) extends a parameterised type with an Immutables-generated class as a type argument. Eclipse might have cleaned that class before triggering Immutables processing.

Adding ` || type.getKind() == TypeKind.ERROR` made my code compile again, but probably the `traverse()` method needs to be beefed up to not throw new kinds of exceptions when processing an `ErrorType`.

**Comment by marc-guenther** [comment]
I just got the exact same NullPointerException: #1268

Has this ever been fixed?
